---
title: "discrete probability"
author: "Evangeline Reynolds"
date: "11/14/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r roulette}
c(3800, 200, 0, -100, - 300) %>% 
  data.frame(payout = .) %>% 
  mutate(prob = c(1/38, 5/38, 6/38, 12/38, 14/38)) %>% 
  mutate(ev_contribution = prob*payout) %>% 
  mutate(ev = sum(ev_contribution)) %>% 
  mutate(var_contribution = (payout - ev)^2 * prob ) %>%
  mutate(variance = sum(var_contribution)) %>% 
  mutate(sd = sqrt(variance)) ->
roulette_example


roulette_example %>% 
  ggplot() + 
  aes(x = payout, y = prob) + 
  geom_point() + 
  geom_segment(aes(xend = payout, yend = 0)) + 
  geom_rect(aes(xmin = 0, xmax = payout, 
                ymin = 0, ymax = prob),
            alpha = .2) + 
  geom_vline(xintercept = -15.789, linetype = "dashed") ->
picture_ev

roulette_example %>% 
  ggplot() + 
  aes(x = payout - ev, y = payout - ev) + 
  geom_point() + 
  coord_equal() +
  geom_segment(aes(xend = payout - ev, yend = 0)) + 
  geom_rect(aes(xmin = ev, xmax = payout - ev, 
                ymin = 0, ymax = payout - ev,
            alpha = prob)) +
  geom_rect(aes(xmin = 0, ymin = 0, xmax = sd, ymax = sd),
            fill = "darkred") ->
picture_variance
```




```{r insurance}
c(20000, 5000, 0) %>% 
  data.frame(payout = .) %>% 
  mutate(situation = c("car totaled", 
                       "car repairs", 
                       "no accidents")) %>% 
  mutate(prob = c(1/100, 9/100, 90/100))  %>%
  mutate(ev_contribution = prob*payout) %>% 
  mutate(ev = sum(ev_contribution)) %>% 
  mutate(var_contribution = (payout - ev)^2 * prob ) %>%
  mutate(variance = sum(var_contribution)) %>% 
  mutate(sd = sqrt(variance)) ->
insurance_example
```
