---
title: "Exploded code"
subtitle: "Using flipbookr and xaringan"
author: "Me"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: [default, hygge, ninjutsu]
    nature:
      ratio: 16:9
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---


```{r, include = F}
# This is the recommended set up for flipbooks
# you might think about setting cache to TRUE as you gain practice --- building flipbooks from scratch can be time consuming
knitr::opts_chunk$set(fig.width = 6, fig.height = 4, message = F, warning = FALSE, comment = "", cache = F)

options(tibble.print_min = 55)
options(knitr.duplicate.label = "allow")
options(width=300) # prevents data wrapping
```


```{css, eval = TRUE, echo = FALSE}
.remark-code{line-height: 1.5; font-size: 70%}

@media print {
  .has-continuation {
    display: block;
  }
}

code.r.hljs.remark-code{
  position: relative;
  overflow-x: hidden;
}


code.r.hljs.remark-code:hover{
  overflow-x:visible;
  width: 500px;
  border-style: solid;
}
```


---


`r flipbookr::chunk_reveal("prep", left_assign = "detect")`


```{r prep, message=F, warning=F, include = FALSE}
library(tidyverse)
library(Lahman)

Teams %>%
  filter(yearID == 2000) %>%
  select(teamID, franchID,
         divID, lgID, W, L, R, G, RA) %>% 
  rename(wins = W, losses = L,
         runs = R, games = G,
         runs_opponent = RA) %>%
  mutate(win_pct = wins/games) %>%
  mutate(runs_differential = runs - runs_opponent) ->
my_data
```

---


`r flipbookr::chunk_reveal("glimpse", left_assign = "detect")`


```{r glimpse, include = FALSE}
my_data %>% 
  head()
```


---


`r flipbookr::chunk_reveal("viz", left_assign = "detect")`


```{r viz, include = FALSE}
my_data %>%
  ggplot() +
  aes(y = wins) +
  aes(x = runs_differential) +
  geom_rug() +
  geom_point() +
  geom_smooth(method = lm, se = F) +
  ggxmean::geom_lm_formula() +
  aes(color = lgID) +
  facet_wrap(facets = vars(lgID))
```


---


`r flipbookr::chunk_reveal("model", left_assign = "detect")`


```{r model, include = FALSE}
my_data %>%
  lm(formula = wins ~ 
       runs_differential + lgID +
       lgID*runs_differential, data = .) %>% 
  summary
```


