---
title: "ISI data"
subtitle: "Scrape code"
author: ""
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: [default, hygge, ninjutsu]
    nature:
      ratio: 16:9
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---


```{r, include = F}
# This is the recommended set up for flipbooks
# you might think about setting cache to TRUE as you gain practice --- building flipbooks from scratch can be time consuming
knitr::opts_chunk$set(fig.width = 6, message = FALSE, warning = FALSE, comment = "", cache = F)
library(flipbookr)
library(tidyverse)
```








<!-- get a flipbook version of the my_cars code chunk - pauses are where parentheses are balanced -->
---

`r chunk_reveal("txt")`

```{r txt, include = FALSE}
# identify txt in in html page 
readLines("http://www.isi-stats.com/isi/data.html") %>%
  tibble(text = .) %>%
  filter(str_detect(text, "\\.txt")) %>%
  mutate(href = 
           str_extract(text, "http.+\\.txt"), 
         .before = 1) %>%
  mutate(dataset_name = 
           str_extract(href, "\\w+\\.txt"), 
         .before = 1) %>%
  mutate(dataset_name = 
           str_remove(dataset_name, "\\.txt")) ->
href_df
 
href_df %>%
  .$href %>%
  .[1] %>%
  readr::read_delim(delim = "\t") %>%
  janitor::clean_names() %>%
  write_rds(path = paste0(href_df$dataset_name[1], ".Rds"))
```

---

# For loop that will try to collect *all* data

```{r, eval = F}
for (i in 1:nrow(href_df)){
 
try(  
href_df %>%
  .$href %>%
  .[i] %>%
  readr::read_delim(delim = "\t") %>%
  janitor::clean_names() %>%
  write_rds(path = paste0(href_df$dataset_name[i], ".Rds"))
 
)
 
}
```


---

# Write documentation

--

# in the end will not be very rich!

---

An example from .R file done right

```{r}
#' Taste scores of 31 bottled water and tap water samples
#'
#' A dataset containing the scores of 31 subjects rating of bottled and tap water
#'
#' @format A data frame with 31 rows and 2 variables:
#' \describe{
#'   \item{Tap}{Score for tap water}
#'   \item{Bottled}{Score for bottled water}
#'   ...
#' }
#' @source \url{http://www.isi-stats.com/isi/data/chap7/AP/BottledWater.txt}
"AP.BottledWater"
```

---


```{r}
"#' {{dataset_name}}
#'
#' A dataset containing the scores of 31 subjects rating of bottled and tap water
#'
#' @format A data frame with {{number_of_rows}} rows and {{number_of_vars}} variables:
#' \describe{
#'   \item{}{See your book}
#'   \item{}{See your book}
#'   ...
#' }
#' @source \url{http://www.isi-stats.com/isi/data/chap7/AP/BottledWater.txt}
'AP.BottledWater'" ->
generic_documentation
```





<!-- adjust font size in this css code chunk, currently 80 -->

```{css, eval = TRUE, echo = FALSE}
.remark-code{line-height: 1.5; font-size: 80%}

@media print {
  .has-continuation {
    display: block;
  }
}

code.r.hljs.remark-code{
  position: relative;
  overflow-x: hidden;
}


code.r.hljs.remark-code:hover{
  overflow-x:visible;
  width: 500px;
  border-style: solid;
}
```

