---
title: "another experiment"
author: "Evangeline Reynolds"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(tidyverse.quiet = TRUE)
```




## Intro Thoughts


## Status Quo

```{r cars}
library(tidyverse)

```

## Experiment

```{r}
outer_space_objects <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2024/2024-04-23/outer_space_objects.csv')


outer_space_objects %>% 
  filter(Entity != "World") %>% 
  mutate(EntityLump = fct_lump_min(f = Entity, 
                                   w = num_objects, min = 150, 
                                   other_level = "Other")) %>% 
  mutate(entity_year = paste(Entity, Year, sep = "-")) %>% 
ggplot() + 
  aes(Year, num_objects) + 
  geom_point(shape = 21, color = "white",
             size = 5, alpha = .8) +
  # geom_line(linewidth = .2) + 
  aes(fill = EntityLump, color = EntityLump) + 
  aes(group = Entity) + 
  scale_fill_viridis_d() + 
  scale_color_viridis_d() +
  scale_y_log10() + 
  ggcallout:::geom_labellink(label = "Russia",
                             which_id = "Belarus-2023",
                             aes(id = entity_year)
                             )


+ 
  ggchalkboard::theme_chalkboard(board_color = "white", chalk_color = "gray10")



outer_space_objects
```



## Closing remarks, Other Relevant Work, Caveats
