---
title: "another experiment"
author: "Evangeline Reynolds"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, error = T)
options(tidyverse.quiet = TRUE)
```




## Intro Thoughts


## Campitelli:  stat_rasa 

https://eliocamp.github.io/codigo-r/en/2018/05/how-to-make-a-generic-stat-in-ggplot2/

### Backend StatRasa, stat_rasa() 

```{r}
library(tidyverse)

StatRasa <- ggplot2::ggproto("StatRasa", ggplot2::Stat,
  compute_group = function(data, scales, compute_group_fun, fun.args) {
     # Change default arguments of the function to the 
     # values in fun.args
     args <- formals(compute_group_fun)
     for (i in seq_along(fun.args)) {
        if (names(fun.args[i]) %in% names(fun.args)) {
           args[[names(fun.args[i])]] <- fun.args[[i]]
        } 
     }
     formals(compute_group_fun) <- args
     
     # Apply function to data
     compute_group_fun(data)
})

# stat function used in ggplot
stat_rasa <- function(mapping = NULL, data = NULL,
                      geom = "point", 
                      position = "identity",
                      compute_group_fun = NULL,
                      ...,
                      show.legend = NA,
                      inherit.aes = TRUE) {
   # Check arguments 
   if (!is.function(compute_group_fun)) stop("compute_group_fun must be a function")
   
   # Pass dotted arguments to a list
   fun.args <- match.call(expand.dots = FALSE)$`...`
   
   ggplot2::layer(
      data = data,
      mapping = mapping,
      stat = StatRasa,
      geom = geom,
      position = position,
      show.legend = show.legend,
      inherit.aes = inherit.aes,
      check.aes = FALSE,
      check.param = FALSE,
      params = list(
         compute_group_fun = compute_group_fun, 
         fun.args = fun.args,
         na.rm = FALSE,
         ...
      )
   )
}
```


### stat_rasa(fun = summarize_xy)

```{r}
group_means <- function(data){
  
 data %>% 
    summarise(x = mean(x),
              y = mean(y))
  
}

geom_means <- function(...){
  stat_rasa(compute_group_fun = group_means, ...)
}

mtcars |>
  ggplot() + 
  aes(x = wt,
      y = mpg) + 
  geom_point() + 
  geom_means(size = 6)

last_plot() + 
  aes(color = factor(cyl))
```

```{r}
group_label_at_center <- function(data){
  
 data %>% 
    group_by(label) %>% 
    summarise(x = mean(x, na.rm = T),
              y = mean(y, na.rm = T))
  
}

geom_center_label <- function(...){
  stat_rasa(compute_group_fun = group_label_at_center, geom = GeomLabel, ...)
}


palmerpenguins::penguins |>
  ggplot() +
  aes(x = bill_length_mm,
      y = bill_depth_mm) +
  geom_point() +
  aes(label = "All") +
  geom_center_label()


last_plot() +
  aes(color = species, label = species)


geom_center_text <- function(...){
  stat_rasa(compute_group_fun = group_label_at_center, geom = GeomText, ...)
}


palmerpenguins::penguins |>
  ggplot() +
  aes(x = bill_length_mm,
      y = bill_depth_mm) +
  geom_point() +
  aes(color = species) +
  geom_center_text(aes(label = species), 
                    color = "Black", 
                    alpha = .8,
                   size = 5, 
                   fontface = "bold")

layer_data(i = 2)
```


```{r}
compute_post <- function(data){
  
  data %>% 
    mutate(xend = x,
           yend = 0)
  
}

geom_post <- function(...){
  stat_rasa(compute_group_fun = compute_post, geom = "segment", ...)
}


data.frame(outcome = 0:1, prob = c(.4, .6)) |>
  ggplot() + 
  aes(x = outcome,
      y = prob) + 
  geom_post() + 
  geom_point() + 
  labs(title = "probability by outcome")


```


```{r}
compute_xmean <- function(data){
  
  data %>% 
    summarize(xintercept = mean(x))
  
}

geom_xmean <- function(...){
  stat_rasa(compute_group_fun = compute_xmean, geom = "vline", ...)
}

mtcars |>
  ggplot() + 
  aes(x = wt,
      y = mpg) + 
  geom_point() + 
  geom_xmean(linetype = "dashed")

last_plot() + 
  aes(color = factor(cyl))
```

```{r}
compute_xy_quantile <- function(data, q = .25){
  
  data %>% 
    summarise(x = quantile(x, q),
              y = quantile(y, q)) 
  
}

geom_quantile <- function(...){
  stat_rasa(compute_group_fun = compute_xy_quantile, geom = "point", ...)
}

mtcars |>
  ggplot() + 
  aes(x = wt,
      y = mpg) + 
  geom_point() + 
  geom_quantile(size = 8) + 
  geom_quantile(size = 8, q = .75)

```


### UI, stat_rasa(fun = detrend)

```{r}
# using .75 span to match ggplot2 geom_smooth
Detrend <- function(data, method = "lm", span = 0.75) {
   if (method == "lm") {
      data$y <- resid(lm(y ~ x, data = data))
   } else {
      data$y <- resid(loess(y ~ x, span = span, data = data))
   }
   as.data.frame(data)
   }
   
   
library(ggplot2)
set.seed(42)
x <- seq(-1, 3, length.out = 30)
y <- x^2 + rnorm(30)*0.5
df <- data.frame(x = x, y = y)

ggplot(df, aes(x, y)) +
  geom_line(aes(color = "raw data")) +
  geom_smooth(aes(color = "loess smoothing"),
              alpha = .3) + 
  stat_smooth(geom = "point", 
              aes(color = "loess smoothing"),
              xseq = df$x) +
  stat_rasa(geom = "line", 
             compute_group_fun = Detrend, 
             method = "smooth",
             aes(color = "detrended")) +
  geom_hline(yintercept = 0, 
             linetype = "dashed") + 
  scale_color_discrete(breaks = 
                         fct_inorder(c("raw data",
                                       "loess smoothing",
                                       "detrended"))) +
  labs(title = "detrending with loess smoothing")
```  
  
### UI, stat_rasa -> stat_detrend
  
```{r}  
stat_detrend <- function(...) {
   stat_rasa(compute_group_fun = Detrend, geom = "line", ...)
}

ggplot(df, aes(x, y)) + 
  geom_line(aes(color = "raw data")) +
  geom_smooth(method = "lm", 
              aes(color = "linear model")) +
  stat_smooth(method = "lm", geom = "segment",
              xend = df$x, yend = df$y,
              xseq = df$x, alpha = .2
              ) +
  stat_detrend(method = "lm", 
                aes(color = "detrended")) +
  geom_hline(yintercept = 0, 
             linetype = "dashed") + 
  scale_color_discrete(breaks = 
                         fct_inorder(c("raw data",
                                       "linear model",
                                       "detrended"))) + 
  labs(title = "Linear detrending",
       color = NULL)
```


## Stat Rasa one-liners

if we reorganize, we can use positioning for arguments, and we can do one-liners.

```{r}
rasa_g <- function(compute_group_fun, geom, ...){
  
  stat_rasa(compute_group_fun = compute_group_fun, geom = geom, ...)
  
}
```

```{r, warning=F}
library(tidyverse)
geom_xmean <- function(...){rasa_g(function(df) df |> summarize(xintercept = mean(x)), "vline", ...)}

ggplot(cars) +
  aes(speed, dist) + 
  geom_point() + 
  geom_xmean(linetype = 'dashed')
  
last_plot() + 
  aes(color = dist > 50)
```



## Status Quo

```{r cars}
geom_post <- function(...){rasa_g(function(df) df |> mutate(xend = x, yend = 0), "segment", ...)}

data.frame(prob = c(.4,.6), outcome = c(0, 1)) %>% 
ggplot(data = .) +
  aes(outcome, prob) + 
  geom_post() +
  geom_point() 

geom_expectedvalue <- function(...){rasa_g(function(df) df |> summarise(x = sum(x*y), y = 0), "point", ...)} 

last_plot() + 
  geom_expectedvalue()

geom_expectedvalue_label <- function(...){rasa_g(function(df) df |> summarise(x = sum(x*y), y = 0) |> mutate(label = round(x, 2)), "text", hjust = 1, vjust = 0, ...)} 

last_plot() +
  geom_expectedvalue_label()
```

```{r}
rep(1, 15) |> 
  c(0) %>% 
  data.frame(outcome = .) |>
  ggplot() + 
  aes(x = outcome, y = 0) + 
  geom_dotplot()

geom_proportion <- function(...){rasa_g(function(df) df |> summarise(x = sum(x)/length(x), y = 0), "point", ...)}   # this should work for T/F too when rasa_p is in play

last_plot() + 
  geom_proportion()

geom_proportion_label <- function(...){rasa_g(function(df) df |> summarise(x = sum(x)/length(x), y = 0) |> mutate(label = round(x)), vjust = 0, "text", ...)}   # this should work for T/F too when rasa_p is in play

last_plot() + 
  geom_proportion_label()

last_plot()

```


## Experiment

```{r}
geom_means <- function(...){rasa_g(function(df) df |> summarize(x = mean(x, na.rm = T), y = mean(y, na.rm = T)), "point", ...)}

palmerpenguins::penguins %>% 
  ggplot() + 
  aes(bill_length_mm, bill_depth_mm) + 
  geom_point() + 
  geom_means(size = 7)
```


```{r}
geom_grouplabel <-  function(...){rasa_g(function(df) df |> group_by(label) |> summarize(x = mean(x, na.rm = T), y = mean(y, na.rm = T)), "label", ...)}

palmerpenguins::penguins %>% 
  ggplot() + 
  aes(bill_length_mm, bill_depth_mm, label = species, group = species) + 
  geom_point() + 
  geom_grouplabel(size = 7)
```



## Closing remarks, Other Relevant Work, Caveats
