---
title: "another experiment"
author: "Evangeline Reynolds"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(tidyverse.quiet = TRUE)
```




## Intro Thoughts


## Status Quo

```{r}
library(tidyverse)
emissions <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2024/2024-05-21/emissions.csv')
options(scipen = 10)

emissions %>% 
  group_by(parent_entity, year) %>% 
  summarise(total_emissions_MtCO2e = sum(total_emissions_MtCO2e)) %>% 
  mutate(cummulative = cumsum(total_emissions_MtCO2e)) %>% 
  # arrange(-total_cum) %>% 
  ggplot() + 
  aes(year, cummulative) + 
  geom_line(color = "grey") +
  aes(group = parent_entity) + 
  scale_y_log10()  +
  NULL

last_plot() + 
  geom_line(data = . %>% 
              filter(parent_entity %in% 
                       c("Abu Dhabi National Oil Company",
                         "Adani Enterprises",
                         "Adaro Energy")), 
            aes(color = parent_entity),
            linewidth = 2)

last_plot() +
  aes(id = paste(parent_entity, year)) +  ggcallout:::geom_labellink_swss(which_id = "Adaro Energy 1992", 
                                  link_prop = .25)  
  


last_plot() + 
  guides(color = "none") + 

  ggcallout:::geom_labellink_nww(which_id = "Abu Dhabi National Oil Company 1976",
                                 link_prop = .3) +
  ggcallout:::geom_labellink_south(which_id = "Adani Enterprises 2012",
                                   link_prop = .2) +
  aes(label = parent_entity %>% str_wrap(12)) + 
  labs(x = NULL)


```

## Experiment

```{r}

```



## Closing remarks, Other Relevant Work, Caveats
