---
title: "another experiment"
author: "Evangeline Reynolds"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(tidyverse.quiet = TRUE)
```




## Intro Thoughts


## Status Quo

```{r cars, error = T}
library(tidyverse)
names(ggplot2::StatCount)

StatPie <- ggproto("StatPie", StatCount)

ggplot(diamonds) + 
  aes(y = .5, fill = cut) + 
  layer(geom = "bar", stat = "pie", position = "stack") + 
  coord_polar()

ggplot2::StatCount$default_aes

StatPie$default_aes <- aes(x = after_stat(count), y = .5, weight = 1)

ggplot(diamonds) + 
  aes(y = .5, fill = cut) + 
  layer(geom = "bar", stat = "pie", position = "stack") + 
  coord_polar()

ggplot(diamonds) + 
  aes(fill = cut) + 
  layer(geom = "bar", stat = "pie", position = "stack") + 
  coord_polar()

ggplot(diamonds) + 
  aes(fill = cut) + 
  layer(geom = "bar",  
        stat = "pie", 
        position = "stack",
        mapping = aes(y = .5)) + 
  coord_polar()


geom_pie <- function(...){
  
  aes_y = aes(y = .5)
  
  layer(geom = "bar",  
        stat = "pie", 
        position = "stack",
        mapping = aes(..., !!!aes_y), 
        params = list(...)) 
  
}


ggplot(diamonds) + 
  geom_pie() + 
  coord_polar()

last_plot() + 
  aes(fill = color)
  
ggplot(diamonds) + 
  geom_pie(aes(fill = color)) + 
  coord_polar()


```

## Experiment

```{r}

```



## Closing remarks, Other Relevant Work, Caveats
