---
title: "another experiment"
author: "Evangeline Reynolds"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(tidyverse.quiet = TRUE)
```




## Intro Thoughts


## Status Quo

```{r, error = T}
library(tidyverse)

compute_panel_wedge <- function(data, scales, vertices = 5){
  
  data |>
    mutate(prop = area/sum(area)) |>
    mutate(cumprop = cumsum(prop)) |>
    mutate(lagcumprop = lag(cumprop, default = 0)) ->
  props_vertices; props_vertices
  
  data.frame(around = 0:vertices/vertices) %>%
    crossing(props_vertices) %>%
    group_by(id) %>%
    filter(lagcumprop <= around &
           cumprop >= around) ->
  arcs; arcs

  props_vertices %>%
    mutate(around = cumprop) %>%
    bind_rows(arcs) %>%
    bind_rows(props_vertices %>%
                 mutate(around = lagcumprop)) |>
    arrange(id, around) %>% 
    mutate(x = cos(2*pi*around)) %>% 
    mutate(y = sin(2*pi*around)) ->
  circle_points; circle_points

  data |>
    distinct(id, area) |>
    mutate(x = 0) |>
    mutate(y = 0) %>%
    mutate(around = -1) %>% 
    mutate(prop = -1, 
           cumprop = -1,
           lagcumprop = -1) ->
  middle; middle

  data |>
    distinct(id, area) |>
    mutate(x = 0) |>
    mutate(y = 0) %>%
    mutate(around = 2) %>% 
    mutate(prop = 2, 
           cumprop = 2,
           lagcumprop = 2) ->
  middle2; middle2

  bind_rows(middle, 
            circle_points) %>% 
    bind_rows(middle2) %>% 
    arrange(around) %>% 
    ungroup()

  }


diamonds %>% 
  count(cut) %>% 
  select(id = cut, area = n) ->
data

data %>% 
  compute_panel_wedge() %>% 
  data.frame()


diamonds %>% 
  count(cut) %>% 
  select(id = cut, area = n) %>% 
  compute_panel_wedge() %>% 
  ggplot() + 
  aes(x = x, y = y, color = id) + 
  geom_point() + 
  geom_path() + 
  coord_equal()


StatWedge <- ggproto("StatWedge",
                     Stat,
                     compute_panel = 
                       compute_panel_wedge)




diamonds |>
  count(cut) |>
  ggplot() + 
  aes(id = cut, area = n) + 
  geom_point(stat = StatWedge) + 
  aes(color = after_stat(id)) +
  aes(fill = after_stat(id)) +
  geom_polygon(stat = StatWedge) +
  coord_equal()




compute_panel_wedge <- function(data, scales, vertices = 5){
  
  data |>
    mutate(prop = area/sum(area)) |>
    mutate(cumprop = cumsum(prop)) |>
    mutate(lagcumprop = lag(cumprop, default = 0)) ->
  props_vertices; props_vertices
  
  data.frame(around = 0:vertices/vertices) %>%
    crossing(props_vertices) %>%
    group_by(id) %>%
    filter(lagcumprop <= around &
           cumprop >= around) ->
  arcs; arcs

  props_vertices %>%
    mutate(around = cumprop) %>%
    bind_rows(arcs) %>%
    bind_rows(props_vertices %>%
                 mutate(around = lagcumprop)) |>
    arrange(id, around) %>% 
    mutate(x = cos(2*pi*around)) %>% 
    mutate(y = sin(2*pi*around)) ->
  circle_points; circle_points

  data |>
    distinct() |>
    mutate(x = 0) |>
    mutate(y = 0) %>%
    mutate(around = -1) %>%
    mutate(prop = -1,
           cumprop = -1,
           lagcumprop = -1) ->
  middle; middle

  data |>
    distinct() |>
    mutate(x = 0) |>
    mutate(y = 0) %>%
    mutate(around = 2) %>%
    mutate(prop = 2,
           cumprop = 2,
           lagcumprop = 2) ->
  middle2; middle2

  bind_rows(middle,
            circle_points) %>%
    bind_rows(middle2) %>%
    arrange(around) %>%
    ungroup()

}


StatWedge$compute_panel <- compute_panel_wedge

diamonds |>
  count(cut) |>
  ggplot() + 
  aes(id = cut, area = n) + 
  geom_point(stat = StatWedge) + 
  aes(color = after_stat(id)) +
  aes(fill = after_stat(id)) +
  geom_polygon(stat = StatWedge, vertices = 10) +
  coord_equal()


layer_data(i = 2)

```



## Closing remarks, Other Relevant Work, Caveats
