---
title: "another experiment"
author: "Evangeline Reynolds"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(tidyverse.quiet = TRUE)
```


```{r}
# gene_data |> #where A,B, and C are indicator variables
#   ggplot() + 
#   aes(dims = dims(A:C)) + 
#   geom_venn()  # Warn without

# y talk
# ggplot() +
#   aes(dims = dims(A:B)) + 
#   geom_venn()


```



```{r}
library(tidyverse)

genes <- paste("gene", 1:1000, sep="")


x <- list(A = sample(genes,300),
          B = sample(genes,525),
          C = sample(genes,440),
          D = sample(genes, 50))

ggVennDiagram::ggVennDiagram(x = x)

layer_data(i = 1) |> 
  ggplot() +
  aes(x,y, group = group, fill = fill) + 
  geom_polygon()

```


```{r}
library(ggVennDiagram)
# three dimension Venn plot
ggVennDiagram(x[1:3],label = "none")

layer_data(i = 1) |> 
  # filter(fill == "#132B43") |> 
  ggplot() + 
  aes(x,y, label = group,
      fill = group, group = group) + 
  geom_text() + 
  coord_equal() + 
  geom_polygon()
```

## Experiment

```{r}
gene_data <- tribble(~A, ~B, ~C,
                      T, T, F, 
                      T, T, T,
                      T, F, T)

library(tidyverse)

df_conditions_inclusion_list <- function(df){

  conditions <- df |> names()
  
  conditions
  
  out <- list()

  for(i in 1:length(conditions)){

    out[[i]] <- which(df[conditions[i]] |> pull())

  }

  out
}




features_to_venn <- function(data, scales){
  
df <- data |> 
  df_conditions_inclusion_list() |>
  Venn() |> 
  process_data(shape_id = NULL) 
  

left_join(ggVennDiagram:::get_shape_regionedge(df),
            ggVennDiagram:::venn_region(df)) |> 
  rename(x = X,
         y = Y,
         group = id)

}



# compute_panel_venn_label <- function(data, scales){
#   
# df <- data |> 
#   df_conditions_inclusion_list() |>  ## dims go here
#   Venn() |> 
#   process_data(shape_id = NULL) 
#   
# 
# left_join(ggVennDiagram:::get_shape_regionedge(df),
#             ggVennDiagram:::venn_regionlabel(df)) |> 
#   rename(x = X,
#          y = Y,
#          group = id)
# 
# }


gene_data |> 
  compute_panel_venn() |>
  ggplot() + 
  aes(x, y, group = group) + 
  geom_point()


gene_data |> 
  compute_panel_venn() |>
  ggplot() + 
  aes(x,y, group = group, fill = group) + 
  geom_polygon()

# gene_data |> 
#   compute_panel_venn_label()


library(ggdims)





```



## Closing remarks, Other Relevant Work, Caveats
