---
title: "another experiment"
author: "Evangeline Reynolds"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(tidyverse.quiet = TRUE)
```




## Intro Thoughts


## Status Quo

```{r}
library(tidyverse)

```

## Experiment

```{r}
library(tidyverse)

harvest_2021 <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2024/2024-05-28/harvest_2021.csv')

harvest_2021 %>% 
  distinct(vegetable) %>% 
  ggplot() + 
  aes(id = vegetable) + 
  ggcirclepack::geom_circlepack() + 
  ggcirclepack::geom_circlepack_text() + 
  coord_equal() + 
  aes(fill = I("aliceblue")) + 
  aes(color = I("midnightblue"))
  

layer_data(i = 2) ->
circle_data

library(ggcircumscribe)

ggwipe::last_plot_wipe_last() +   
  ggcircumscribe::geom_circumscribe(data = circle_data, 
                    aes(id = NULL, x= x, y = y, label = label), 
                    radius = grid::unit(10, "mm"), grow = TRUE) 

# harvest_2021 %>% 
#   distinct(vegetable) %>% 
#   ggplot() + 
#   aes(id = vegetable) + 
#   ggcirclepack::geom_circlepack() + 
# + 
#   coord_equal() + 
#   aes(fill = I("aliceblue")) + 
#   aes(color = I("midnightblue"))
```



## Closing remarks, Other Relevant Work, Caveats
