---
title: "Exploded code"
subtitle: "Using flipbookr and xaringan"
author: "Me"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: [default, hygge, ninjutsu]
    nature:
      ratio: 16:9
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---


```{r, include = F}
# This is the recommended set up for flipbooks
# you might think about setting cache to TRUE as you gain practice --- building flipbooks from scratch can be time consuming
knitr::opts_chunk$set(fig.width = 6, message = F, warning = FALSE, comment = "", cache = F)

options(tibble.print_min = 55)
options(knitr.duplicate.label = "allow")
options(width=300) # prevents data wrapping
```


```{css, eval = TRUE, echo = FALSE}
.remark-code{line-height: 1.5; font-size: 70%}

@media print {
  .has-continuation {
    display: block;
  }
}

code.r.hljs.remark-code{
  position: relative;
  overflow-x: hidden;
}


code.r.hljs.remark-code:hover{
  overflow-x:visible;
  width: 500px;
  border-style: solid;
}
```


---


`r flipbookr::chunk_reveal("setup", left_assign = "detect")`


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



---


`r flipbookr::chunk_reveal("cars", left_assign = "detect")`


```{r cars, include = FALSE}
library(tidyverse)
library(ggstamp)  
set.seed(1243)
tibble::tibble(x = rnorm(40000, sd = .7),
       y = rnorm(40000, sd = .7)) %>% 
  ggplot() + 
  aes(x = x, y = y) +
  geom_hex(show.legend = F, color = alpha("white", 0)) + 
  coord_equal(xlim = c(-3,3), ylim = c(-2.3, 2.3)) + 
  stamp_polygon_inverse(radius = 2, radius_outer = Inf, 
                        fill = "green", color = "red"
                        ) +
  stamp_polygon(alpha = .2, n = 5, size = 1.75,
                fill = "magenta", color = "grey15",
                rotation = -.55) + 
  stamp_polygon(radius = .4, n = 3,
                x0 = .3, y0 = .77, rotation = -.4,
                alpha = 1, fill = "orange", size = 0) + 
  stamp_text(angle = 30, label = "ggstamp",
             x = .7, y = -1,
             color = "snow1") + 
  stamp_text(angle = 30, label = "github.com/EvaMaeRey/ggstamp",
             x = .7, y = -1.45, size = 1.8,
             color = "grey85") + 
  stamp_polygon(radius = 2, 
                alpha = 0, size = 2,
                color = "plum3") + 
  theme_void_fill(fill = "green") +
  ggxmean::stamp_normal_dist(sd = .2, alpha = .8, height = 1.5) + 
  stamp_point(xy = pos_wrap(n = 22, ncol = 6, width = .15, x0 = -.95, y0 = -.3), size = 3,
              color = "seagreen2") ->
g; g
```


---


`r flipbookr::chunk_reveal("magick", left_assign = "detect")`


```{r magick, include = FALSE}
ggsave("hex_sticker_ggstamp.png", plot = g, dpi = 320) 

magick::image_read("hex_sticker_ggstamp.png") %>% 
  magick::image_fill("transparent",  "+40+40", fuzz = 40) %>% 
  magick::image_write("hex_sticker_ggstamp2.png")
```

