---
title: "another experiment"
author: "Evangeline Reynolds"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(tidyverse.quiet = TRUE)
```


## Intro Thoughts


## Status Quo

```{r}
library(tidyverse)
library(ggswitzerland)
library(ggregions)

options(ggregions.ref.regions = ggswitzerland::muni_prod_geo)



ggplot(ggswitzerland::muni_income_data) + 
  aes(region = municipality) + 
  geom_region()

# ggswitzerland::canton_geo %>%
#    mutate(across(-geometry, as.character)) 
# 
# 
# ggswitzerland::canton_geo |>
#   ggplot() + 
#   aes(geometry = geometry) + 
#   geom_sf()
# 
# swiss_ref_data <- ggswitzerland::canton_geo |> mutate(name = canton_name) |> select(-canton_num) |>
#   bind_rows(ggswitzerland::country_geo |> mutate(name = "Switzerland")) |>
#   bind_rows(ggswitzerland::lake_geo |> mutate(name = lake_name)) |>
#   bind_rows(ggswitzerland::muni_prod_geo |> mutate(name = muni_name) |> select(-muni_id)) |>
#   select(name, everything())
# # 
# #   # heyfuckhead(swiss_ref_data)
# # 
# options(ggregions.ref.regions = swiss_ref_data |> select(everything(), geometry))
# # 
# # 
# # 
# # 
# ggswitzerland::muni_income_data |>
#   ggplot() +
#   aes(region = municipality) +
#   # stamp_relief() +
#   geom_region()
# 
# 
# usmap <- usmapdata::us_map() |> mutate(geometry = geom)
# 
#   
# options(ggregions.ref.regions = usmap)
# 
# 
# USArrests |> 
#   rownames_to_column() |> 
#   ggplot() + 
#   aes(region = rowname) + 
#   geom_region()

```

## Experiment

```{r}

```



## Closing remarks, Other Relevant Work, Caveats
