---
title: "another experiment"
author: "Evangeline Reynolds"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(tidyverse.quiet = TRUE)
```




## Intro Thoughts


## Status Quo

```{r}
library(tidyverse)
library(ggsoiltexture)


```

## Experiment

```{r}
ggsoiltexture(tibble(sand = c(20, 80),
                     silt = c(15, 10),
                     clay = c(65, 10)),
              show_grid = T,
              class = NULL)

# palmerpenguins::penguins |>
#   remove_missing() |>
#   mutate(bill_length_mm = bill_length_mm / mean(bill_length_mm),
#          bill_depth_mm = bill_depth_mm / mean(bill_depth_mm),
#          flipper_length_mm = flipper_length_mm / mean(flipper_length_mm)) |>
#   mutate(total_length = bill_length_mm + bill_depth_mm + flipper_length_mm) |>
#   mutate(sand = 100*bill_length_mm/total_length) |> 
#   mutate(silt = 100*bill_depth_mm/total_length) |>
#   mutate(clay = 100*flipper_length_mm/total_length) |>
#   ggsoiltexture() + 
#   geom_point(aes(color = species))


snapshot <- ggplyr::intercept

compute_tern_shift <- function(data, scales){
  
  out <- data |> 
    mutate(x = x + y/2)
  
  if(!is.null(out$xend)){
    
    out <- out |> 
      mutate(xend = xend + yend/2)
    
  }
  
  out
  
  
}


tibble(clay = runif(1000, 0, 100),
       silt = runif(1000, 0, 100),
       sand_random = runif(1000, 0, 100),
       sand_computed = 100 - clay - silt) |> 
  ggplot() + 
  aes(y = clay) + 
  geom_rug() + labs(title = "first dimention, random 0% to 100%") +
  snapshot("p1") +
  scale_x_continuous(position = "top") +
  aes(x = silt) + 
  coord_fixed(sqrt(3)/2) +
  geom_point() +   
  labs(title = "second dimention, random 0% to 100%") +
  snapshot("p2") +
  aes(alpha = (clay + silt) < 100) + 
  labs(title = "highlight possible (does not exceed 100%)") + 
  snapshot("p3") +
  ggplyr::data_filter((clay + silt) < 100) + aes(alpha = NULL) + 
  labs(title = "remove impossible (drop > 100%)") + 
  snapshot("p4") +
  scale_color_viridis_c() +
  aes(color = sand_random) + 
  labs(title = "third dimension, random 0 to 100") + 
  snapshot("p5") +
  aes(color = sand_computed) + 
  labs(title = "third component computed") +
  snapshot("p6") 


ggplyr::last_plot_wipe_last() + 
  geom_point(stat = ggproto("hi", Stat, compute_group = compute_tern_shift)) +
  snapshot("p7")  +
  NULL

# ggram:::gif_from_ggplots(list(p1, p2, p3, p4, p5, p6, p7))



```

```{r, fig.width=18, fig.height=12}
library(patchwork)
((p1 + p2)/
(p3 + p4)/
(p5 + p6)) + patchwork::plot_annotation(tag_levels = "A")

```



```{r}
library(ggsoiltexture)
library(tidyverse)

tibble(clay = runif(1000, 0, 100),
       silt = runif(1000, 0, 100),
       sand_random = runif(1000, 0, 100),
       sand_computed = 100 - clay - silt) |> 
  ggplot() + 
  aes(y = clay) + # axis 1
  aes(x = silt) + # axis 2
  geom_point() +  
  aes(alpha = (clay + silt) < 100) + # highlight possible
  scale_color_viridis_c(limits = c(0,100)) + 
  aes(color = sand_computed) # axis 3

tibble(sand = runif(1000, 0, 100),
       silt = runif(1000, 0, 100), 
       clay = 100 - sand - silt) |>
  filter((sand+silt) < 100) |>
  ggsoiltexture() + 
  geom_point(aes(color = sand)) + 
  coord_equal() + 
  scale_color_viridis_c() + 
  NULL

```


```{r}
library(tidyverse)

compute_tern_shift <- function(data, scales){
  
  out <- data |> 
    mutate(x = x + y/2)
  
  if(!is.null(out$xend)){
    
    out <- out |> 
      mutate(xend = xend + yend/2)
    
  }
  
  out
  
  
}

StatTernShift <- ggproto("StatTernShift", Stat, 
                         compute_group = compute_tern_shift)

tern_axes <- tibble(x = 0, y = 0:10*10, label = y) |> 
  bind_rows(tibble(x = 10:0*10, y = 0:10*10, label = x)) |>
  bind_rows(tibble(x = 0:10*10, y = 0, label = x)) 

ggplot(tern_axes) + 
  aes(x,y) + 
  geom_point(color = "lightgrey") +
  geom_point(data = tern_axis, stat = StatTernShift, color = "grey35", linetype = "dashed")



tibble(y = 9:1*10, x = 0, yend = 9:1*10, xend = 1:9*10) |>
  bind_rows(tibble(x = 1:9*10, y = 9:1*10, xend = 1:9*10, yend = 0)) |>
  bind_rows(tibble(x = 0, y = 9:1*10, xend = 9:1*10, yend = 0)) |>
  ggplot() + 
  aes(x = x, y = y, xend = xend, yend = yend) + 
  geom_segment() +
  geom_segment(stat = StatTernShift, color = "grey", linetype = "dashed")

```

