---
title: "another experiment"
author: "Evangeline Reynolds"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, dev = "ragg_png", dpi = 300)
options(tidyverse.quiet = TRUE)
```




## Intro Thoughts


## Status Quo

```{r}
library(tidyverse)
gapminder_2002 <- gapminder::gapminder |> 
  filter(year == 2002)

theme(geom = element_geom(pointshape = 21, 
                          pointsize = 3)) |>
  theme_set()

update_geom_defaults("point",  aes(shape = 21, size = 3,  color = "white", fill = "grey"))

'
gapminder_2002 |>
  ggplot() + 
  aes(gdpPercap/1000, 
      lifeExp) + 
  geom_point(layout = "fixed") + #<<
  geom_point(fill = "magenta4") + 
  facet_wrap(~continent)' |> 
ggram::ggram(title = "Fond of reference shadows in facets?  A snap with ggplot2 v4.0's new 'layout' arg! 🫰", 
             caption = "Note, geom updates prior to plotting: 'update_geom_defaults( \"point\",  aes(shape = 21, size = 3,  color = \"white\", fill = \"grey\"))'",
             subtitle = "And 'fixed_cols' and 'fixed_rows' are options with facet_grid()! 🚀🔥", code = _)


  
  
```

## Experiment

```{r}
theme(geom = element_geom(pointshape = 21, 
                          pointsize = 3)) |>
  theme_set()

ggplot() + 
  aes() 

```



## Closing remarks, Other Relevant Work, Caveats
