---
title: "another experiment"
author: "Evangeline Reynolds"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(tidyverse.quiet = TRUE)
```




## Intro Thoughts


## Status Quo

```{r}
library(tidyverse)


compute_split <- function(data = cars, scales, seed = getOption("seed", 1999), step = getOption("tt_step", "train")){
  
  set.seed(seed)
  n <- nrow(data)
  n_train = (n/2) |> round()
  which_train_num <- sample(1:n, size = n_train,  replace = F)
  
  data |> 
    mutate(train_test = ifelse(row_number() %in% which_train_num, "train", "test")) |>
    mutate(ind_step = train_test == step)
  
  # 
  #   mutate()
  #   
  #   
  # which_train <- 1:n %in% which_train_num 
  # which_test <- !which_train
  # 
  # if(step == "train"){
  #   data |> _[which_train, ]
  # }else{
  #     data |> _[which_test, ]
  #   }
  
}

StatSplit <- ggproto("StatSplit", Stat,
                           compute_panel = compute_split,
                           default_aes = aes(alpha = after_stat(ind_step)))

cars |>
  rename(x = speed, y = dist) |>
  compute_split() |>
  head()



compute_split_lm <- function(data, scales, step = getOption("tt_step", "train")){
  
  data <- data |> compute_split(step = step)

  data$yend = data$y
  data$xend = data$x

  model <- lm(y ~ x, data = data |> filter(train_test == "train"))

  data$y = predict(model, data)

  data
}


StatLmSplit <- ggproto("StatLmSplit", Stat,
                        compute_panel = compute_split_lm,
                        default_aes = aes(alpha = after_stat(ind_step)))

cars |>
  rename(x = speed, y = dist) |>
  compute_split_lm() |>
  head()
```





```{r}
# train
ggplot(cars) + 
  aes(speed, dist) +
  geom_point(stat = StatSplit) + 
  geom_line(stat = StatLmSplit, step = "test", alpha = 1) + 
  geom_point(stat = StatLmSplit) + 
  geom_segment(stat = StatLmSplit, lty = "dashed") + 
  labs(title = "training step") ->
p_test

# test
ggplot(cars) + 
  aes(speed, dist) +
  geom_point(stat = StatSplit, step = "test") + 
  geom_line(stat = StatLmSplit, step = "test", alpha = 1) + 
  # geom_point(stat = StatLmSplit, step = "test") +
  geom_segment(stat = StatLmSplit, step = "test", lty = "dashed") + 
  labs(title = "testing step")  ->
p_train


library(patchwork)
p_test + p_train

```


```{r}
compute_split_lm_se <- function(data, scales, step = getOption("tt_step", "train")){
  
  data <- data |> compute_split_lm(step = step)
  data

  data$residual = data$yend - data$y

  data$x = data$residual/2
  data$y = data$residual/2
  data$width = data$residual
  data$height = data$residual

  data |> select(residual, x, y, width, height, ind_step)
  
  }


cars |>
  rename(x = speed, y = dist) |>
  compute_split_lm_se() |>
  head()

StatLmSplitSE <- ggproto("StatLmSplitSE", Stat,
                        compute_panel = compute_split_lm_se,
                        default_aes = aes(alpha = after_stat(ind_step)))

ggplot(cars) +
  aes(speed, dist) +
  geom_rect(stat = StatLmSplitSE, linetype = "dashed") +
  coord_equal() +
  scale_alpha(range = c(0,.6)) ->
squared_error_train

ggplot(cars) +
  aes(speed, dist) +
  geom_rect(stat = StatLmSplitSE, step = "test", linetype = "dashed") +
  coord_equal() +
  scale_alpha(range = c(0,.6)) ->
squared_error_test

squared_error_train + squared_error_test

```


## Experiment

```{r}
compute_split_lm_rmse <- function(data, scales, step = getOption("tt_step", "train")){
  
  data <- data |> 
    compute_split_lm_se(step = step) |>
    group_by(ind_step) |>
    summarise(rootmeansquarederror = sqrt(mean(residual^2)))

  data$x = data$rootmeansquarederror/2
  data$y = data$rootmeansquarederror/2
  data$width = data$rootmeansquarederror
  data$height = data$rootmeansquarederror

  data |>
    select(rootmeansquarederror, x,y, width, height, ind_step)

}

cars |>
  rename(x = speed, y = dist) |>
  compute_split_lm_rmse() |>
  head()


StatLmSplitRMSE <- ggproto("StatLmSplitRMSE", Stat,
                        compute_panel = compute_split_lm_rmse,
                        default_aes = aes(alpha = after_stat(ind_step)))


ggplot(cars) +
  aes(speed, dist) +
  geom_rect(stat = StatLmSplitSE, linetype = "dashed") +
  geom_rect(stat = StatLmSplitRMSE, fill = "blue") +
  coord_equal() +
  scale_alpha(range = c(0,.6)) ->
squared_error_train

ggplot(cars) +
  aes(speed, dist) +
  geom_rect(stat = StatLmSplitSE, step = "test", linetype = "dashed") +
  geom_rect(stat = StatLmSplitRMSE, step = "test", fill = "blue") +
  coord_equal() +
  scale_alpha(range = c(0,.6)) ->
squared_error_test

squared_error_train + squared_error_test

layer_data(i = 2)
```



## Closing remarks, Other Relevant Work, Caveats
