---
title: "another experiment"
author: "Evangeline Reynolds"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(tidyverse.quiet = TRUE)
```




## Intro Thoughts


## Status Quo

```{r}

```

## Experiment

```{r}
library(tidyverse)


ggtable <- function(data){
  
  ggplot(data) + 
    aes(x = "All", y = "All") + 
    geom_count() ->>
  p
  
  layer_data(p)
  
}


set_cols <- function(pipe_spacer, cols){
  
  p + 
    aes(x = {{cols}}) ->>
  p

  x_values_df <- layer_data(p, i = 1) %>%  .[,c("x", "group")] |> distinct()
  x_var_name <- p$mapping$x |> capture.output() %>% .[2] %>% str_extract("\\^.+") %>% str_remove("\\^")
  x_var_df <- p$data[x_var_name] %>% distinct()
  names(x_var_df) <- "x_var"
  x_var_df <- mutate(x_var_df, group = as.numeric(x_var))
  x_numeric_cat_crosswalk <- left_join(x_values_df, x_var_df, by = join_by(group))
  
  
  y_values_df <- layer_data(p, i = 1) %>%  .[,c("y", "group")] |> distinct()
  y_var_name <- p$mapping$y |> capture.output() %>% .[2] %>% str_extract("\\^.+") %>% str_remove("\\^")
  y_var_df <- p$data[y_var_name] %>% distinct()
  names(y_var_df) <- "y_var"
  y_var_df <- mutate(y_var_df, group = as.numeric(y_var))
  y_numeric_cat_crosswalk <- left_join(y_values_df, y_var_df, by = join_by(group))
  
  # print(p)
   layer_data(p) %>% 
     mutate(x = factor(x, 
                       levels = x_numeric_cat_crosswalk$group, 
                       labels = x_numeric_cat_crosswalk$x_var)) %>% 
    mutate(y = factor(y,  
                      levels = y_numeric_cat_crosswalk$group, 
                      labels = y_numeric_cat_crosswalk$y_var)) %>% 
     select(x, y, n) %>% 
     pivot_wider(names_from = x, values_from = n)
  
}

set_rows <- function(pipe_spacer, rows){
  
  p + 
    aes(y = {{rows}}) ->>
  p
  
  x_values_df <- layer_data(p, i = 1) %>%  .[,c("x", "group")] |> distinct()
  x_var_name <- p$mapping$x |> capture.output() %>% .[2] %>% str_extract("\\^.+") %>% str_remove("\\^")
  x_var_df <- p$data[x_var_name] %>% distinct()
  names(x_var_df) <- "x_var"
  x_var_df <- mutate(x_var_df, group = as.numeric(x_var))
  x_numeric_cat_crosswalk <- left_join(x_values_df, x_var_df, by = join_by(group))
  
  y_values_df <- layer_data(p, i = 1) %>%  .[,c("y", "group")] |> distinct()
  y_var_name <- p$mapping$y |> capture.output() %>% .[2] %>% str_extract("\\^.+") %>% str_remove("\\^")
  y_var_df <- p$data[y_var_name] %>% distinct()
  names(y_var_df) <- "y_var"
  y_var_df <- mutate(y_var_df, group = as.numeric(y_var))
  y_numeric_cat_crosswalk <- left_join(y_values_df, y_var_df, by = join_by(group))
  
  layer_data(p) %>% 
    mutate(x = factor(x,  
                      levels = x_numeric_cat_crosswalk$group, 
                      labels = x_numeric_cat_crosswalk$x_var)) %>% 
    mutate(y = factor(y,  
                      levels = y_numeric_cat_crosswalk$group, 
                      labels = y_numeric_cat_crosswalk$y_var)) %>% 
    select(x, y, n) %>% 
    pivot_wider(names_from = x, values_from = n)
  
}


library(palmerpenguins)

ggtable(penguins) 
  set_rows(species) 
  set_cols(island)





```



## Closing remarks, Other Relevant Work, Caveats
