---
title: "another experiment"
author: "Evangeline Reynolds"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(tidyverse.quiet = TRUE)
```




## Intro Thoughts


## Status Quo

```{r}
library(tidyverse)

```

## A code chunk named 'carsplot' follows


```{r carsplot}
ggplot(cars) + 
  aes(speed, dist) + 
  geom_point() + 
  aes(size = dist)
```



```{r}
knitrExtra::chunk_code_get("carsplot")

knitrExtra::chunk_code_get("carsplot") ->
  code

unconnected_code <- code %>% str_trim() %>% str_remove("\\+$")


partialcode <- c()



for(i in 1:length(code)){
  
  partialcode[i] <- paste(unconnected_code[1:i], collapse = " + ")
  
}


p <- list()
for(i in 1:length(partialcode)){
  
  p[[i]] <- eval(parse(text = partialcode[i]))
  
 label <- ifelse(i > 1, paste("+", unconnected_code[i]), unconnected_code[i])
 
  p[[i]] <- p[[i]] + annotate(geom = "text",
                              x = I(.025),
                              y = I(.95), 
                              hjust = 0,
                              vjust = 1,
                              label = label,
                              color = "red"
                              )
  # 
}


patchwork::wrap_plots(p, ncol = 2)

```


```{r}
knitr::knit_exit()

```



```{r}
co <- function(x) paste(x, collapse = " ")

flipbookr:::chunk_code_get("carsplot") %>% 
  flipbookr:::code_parse() %>% 
  flipbookr:::parsed_return_partial_code_sequence(
    which_highlight = NULL) %>% 
  lapply(., co) %>% 
  unlist() ->
plot_code

plot_code

str(plot_code)

flipbookr:::chunk_code_get("carsplot") %>% 
  flipbookr:::code_parse() %>% 
  flipbookr:::parsed_return_partial_code() ->
last_add

last_add
```





```{r}

p <- list()
for(i in 1:length(plot_code)){
  
  p[[i]] <- i
  
  p[[i]] <- eval(parse(text = plot_code[i]))
  
 print(eval(parse(text = plot_code[i]))
       
       )
  
  p[[i]] <- p[[i]] + annotate(geom = "text",
                              x = I(.05),
                              y = I(.95), 
                              hjust = 0,
                              vjust = 1,
                              label = last_add[i],
                              color = "red"
                              )
  # 
}


p


# eval(parse(text = "ggplot(cars)"))
```





## Closing remarks, Other Relevant Work, Caveats
