---
title: "another experiment"
author: "Evangeline Reynolds"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(tidyverse.quiet = TRUE)
```




## Intro Thoughts


## Status Quo

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">We can answer her question with statistics! <a href="https://t.co/cJ5ADaLXDj">https://t.co/cJ5ADaLXDj</a> <a href="https://t.co/zCA9mghCGF">pic.twitter.com/zCA9mghCGF</a></p>&mdash; 🔥 Kareem Carr 🔥 (@kareem_carr) <a href="https://twitter.com/kareem_carr/status/1707061044865012179?ref_src=twsrc%5Etfw">September 27, 2023</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>



## Experiment

One step further discussion... 45 degrees is the limit of what's possible here...  blah blah blah stats nerds keep the discussion going!

```{r}
library(tidyverse)
set.seed(124)
n = 100
data.frame(x = rnorm(n), y = rnorm(n)) %>% 
  mutate(cutoff = x) %>% 
  mutate(above = y > cutoff ) %>% 
  ggplot() + 
  aes(x = x, y = y) + 
  coord_fixed(ratio = 1) +
  geom_point(shape = 21, size = 6, stroke = 2)

last_plot() + 
  geom_line(aes(y = cutoff),
            linetype = "dashed") + 
  aes(alpha = above) 

last_plot() +
  geom_smooth(data = . %>% filter(above),
              method = lm,
              se = FALSE) + 
  geom_smooth(method = lm,
              se = FALSE,
              color = alpha("blue", .25), 
              aes(alpha = NULL))
```



## Closing remarks, Other Relevant Work, Caveats
