---
title: "gtsummary2"
subtitle: ""
author: ""
output:
  xaringan::moon_reader:
    seal: FALSE
    lib_dir: libs
    css: [default, hygge, ninjutsu]
    nature:
      ratio: 16:9
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---



```{r, include = F}
options(knitr.duplicate.label = "allow")
knitr::opts_chunk$set(fig.width = 6, message = FALSE, warning = FALSE, comment = "", cache = F)
library(flipbookr)
library(tidyverse)
load("current_image.Rdata")
```


```{r, echo = F, eval = FALSE , message = F, warning = F}
xaringanExtra::use_share_again()
```


```{r the_chunk, include = F}
trial |>
  tbl_summary(
    include = age,
    type = all_continuous() ~ "continuous2",
    statistic = all_continuous() ~ c("{mean} ({sd})",
                                     "{median} ({p25}, {p75})",
                                     "{min}, {max}"),
    digits = age ~ list(sd = 2), # show the SD to 2 decimal places
    missing = "no"
  ) ->
out

trial |>
 tbl_summary(
    include = c(age, grade, response),
    by = trt, # split table by group
    missing = "no" # dont list missing data separately
  ) |>
  add_n() %>% # add column with total number of non-missing observations
  modify_header(label = "**Variable**") %>% # update the column header
  bold_labels() ->
gtstable

names(gtstable)

str(gtstable$table_body) ->
  shhh; str(gtstable$table_styling) ->
  shhh; str(gtstable$call_list) ->
  shhh; str(gtstable$cards) ->
  shhh; str(gtstable$inputs)


```

`r chunk_reveal(chunk_name = "the_chunk", break_type = "auto")`



```{css, eval = TRUE, echo = FALSE}
.remark-code{line-height: 1.5; font-size: 120%}

@media print {
  .has-continuation {
    display: block;
  }
}

code.r.hljs.remark-code{
  position: relative;
  overflow-x: hidden;
}


code.r.hljs.remark-code:hover{
  overflow-x:visible;
  width: 500px;
  border-style: solid;
}
```

