---
title: "or pyramid"
subtitle: ""
author: ""
output:
  xaringan::moon_reader:
    seal: FALSE
    lib_dir: libs
    css: [default, hygge, ninjutsu]
    nature:
      ratio: 16:9
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---



```{r, include = F}
options(knitr.duplicate.label = "allow")
knitr::opts_chunk$set(fig.width = 6, message = FALSE, warning = FALSE, comment = "", cache = F)
library(flipbookr)
library(tidyverse)
load("current_image.Rdata")
```


```{r, echo = F, eval = FALSE , message = F, warning = F}
xaringanExtra::use_share_again()
```


```{r the_chunk, include = F}
oregon_population_pyramid_data %>%
  filter(county == "Baker") %>%
  ggplot() + 
  aes(x = percent*100, 
      y = fct_inorder(age), 
      pyramid_cat = gender) +
  geom_rect(stat = StatPyramid,
            sep = 1) + 
  aes(label = age)  + 
  geom_text(stat = StatPyramidlabel) + 
  scale_x_continuous(breaks = c(-10:0 - 1, 0:10 + 1),
                     labels = paste0(c(10:0, 0:10), "%"),
                     limits = c(-10,10)) + 
  labs(y = NULL, x = NULL) + 
  theme(axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        legend.position = "top",
        legend.justification = "left"
        )
```

`r chunk_reveal(chunk_name = "the_chunk", break_type = "auto")`



```{css, eval = TRUE, echo = FALSE}
.remark-code{line-height: 1.5; font-size: 120%}

@media print {
  .has-continuation {
    display: block;
  }
}

code.r.hljs.remark-code{
  position: relative;
  overflow-x: hidden;
}


code.r.hljs.remark-code:hover{
  overflow-x:visible;
  width: 500px;
  border-style: solid;
}
```

