---
title: "another experiment"
author: "Evangeline Reynolds"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, dev = "ragg_png")
options(tidyverse.quiet = TRUE)
```




## Intro Thoughts


## Status Quo

```{r}
library(tidyverse)

```

## Experiment

```{r, fig.width=8, fig.height=4.5}
'gapminder::gapminder |> 
  filter(year == 2002) |>
  ggplot() +
  aes(x = gdpPercap/1000, 
      y = lifeExp) + 
  facet_wrap(vars(continent)) + 
  geom_point(   
      layout = "fixed", #<<
      color = "grey"
      ) + 
  geom_point(aes(color = continent)) +
  theme(legend.position = "none") +
  annotate( #<<
      "text", 
      x = I(.8), y = I(.2),
      label = "🥳", #<<
      layout = 5, #<<
      size = 6
           )' |>
  ggram::ggram(code = _, 
               title = "🚨🥳 *Not only* can ggplot2 v4.0's 'layout' argument be used for shadow layers across facets,\nit *also* can be used to specify panel-specific annotations! ", widths = c(1.4,1.6))
```



## Closing remarks, Other Relevant Work, Caveats
