---
title: "Untitled"
author: "Evangeline Reynolds"
date: "5/23/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r cars}
library(tidyverse)



tidytitanic::passengers %>% 
  ggplot() + 
  aes(x = survived) + 
  geom_bar()


tidytitanic::passengers %>% 
  count(survived)

tidytitanic::passengers %>% 
  mutate(cat_survived = ifelse(survived, "survived", "not survived"), .before = 1)

  

indicator_recode <- function(var, pos_cat = NULL, negator = "not", neg_cat = NULL){
  
  if(is.null(pos_cat)){
    cat_true = deparse(substitute(var))
  }else{
    cat_true = pos_cat
  }
  
  if(is.null(neg_cat)){
    cat_false = paste(negator, cat_true)
  }else{
    cat_false = neg_cat
  }

  
  ifelse({{var}}, cat_true, cat_false) %>% 
    factor(levels = c(cat_false, cat_true))
  
}


tidytitanic::passengers %>% 
  mutate(cat_survived = indicator_recode(survived))

tidytitanic::passengers %>% 
ggplot() + 
  aes(x = indicator_recode(survived)) + 
  geom_bar() + 
  aes(x = indicator_recode(survived, neg_cat = "perished"))

```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
