---
title: "another experiment"
author: "Evangeline Reynolds"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, error = T)
options(tidyverse.quiet = TRUE)
```




## Intro Thoughts


## Status Quo

```{r cars}
library(ggplot2)
library(tidyverse)

# a minimal pie w geom bar
ggplot(diamonds) + 
  aes(y = .5, fill = cut) + 
  geom_bar() + 
  coord_polar()

  


ggplot(diamonds) + 
  aes(y = .5, fill = cut) + 
  layer(geom = "bar", stat = "count", position = "stack") + 
  coord_polar()
```


```{r}
names(ggplot2::StatCount)

StatPie <- ggproto("StatPie", StatCount)

ggplot(diamonds) + 
  aes(y = .5, fill = cut) + 
  layer(geom = "bar", stat = "pie", position = "stack") + 
  coord_polar()

ggplot2::StatCount$default_aes

StatPie$default_aes <- aes(x = after_stat(count), y = .5, weight = 1)

ggplot(diamonds) + 
  aes(y = .5, fill = cut) + 
  layer(geom = "bar", stat = "pie", position = "stack") + 
  coord_polar()

ggplot(diamonds) + 
  aes(fill = cut) + 
  layer(geom = "bar", stat = "pie", position = "stack") + 
  coord_polar()

ggplot(diamonds) + 
  aes(fill = cut) + 
  layer(geom = "bar",  
        stat = "pie", 
        position = "stack",
        mapping = aes(y = .5)) + 
  coord_polar()


ggplot2::StatCount$setup_params

StatPie$setup_params <- function (self, data, params) 
{
    params$flipped_aes <- has_flipped_aes(data, params, main_is_orthogonal = FALSE)
    has_x <- !(is.null(data$x) && is.null(params$x))
    has_y <- !(is.null(data$y) && is.null(params$y))
    # if (!has_x && !has_y) {
    #     cli::cli_abort("{.fn {snake_class(self)}} requires an {.field x} or {.field y} aesthetic.")
    # }
    # if (has_x && has_y) {
    #     cli::cli_abort("{.fn {snake_class(self)}} must only have an {.field x} {.emph or} {.field y} aesthetic.")
    # }
    if (is.null(params$width)) {
        x <- if (params$flipped_aes) 
            "y"
        else "x"
        params$width <- resolution(data[[x]]) * 0.9
    }
    params
}

ggplot(diamonds) + 
  aes(fill = cut) + 
  layer(geom = "bar", stat = "pie", position = "stack") + 
  coord_polar()

ggplot2::StatCount$required_aes

StatPie$required_aes <- character

ggplot(diamonds) + 
  aes(fill = cut) + 
  layer(geom = "bar", stat = "pie", position = "stack") + 
  coord_polar()

ggplot2::StatCount$extra_params
ggplot2::StatCount$super
ggplot2::StatCount$compute_group
ggplot2::StatCount$required_aes




ggplot2::StatCount$dropped_aes

names(ggplot2::GeomBar)


ggplot2::GeomBar$setup_data
ggplot2::GeomBar$rename_size
ggplot2::GeomBar$non_missing_aes
ggplot2::GeomBar$extra_params
ggplot2::GeomBar$super
ggplot2::GeomBar$required_aes
ggplot2::GeomBar$draw_panel
ggplot2::GeomBar$setup_params



```

## ggplot2::geom_point

```{r}
ggplot2::geom_point
```

### look at StatIdentity

```{r}
names(ggplot2::StatIdentity)

ggplot2::StatIdentity$compute_layer
ggplot2::StatIdentity$super
```

### look at GeomPoint


```{r}
names(ggplot2::GeomPoint)
ggplot2::GeomPoint$non_missing_aes
ggplot2::GeomPoint$draw_key
ggplot2::GeomPoint$default_aes
ggplot2::GeomPoint$super
ggplot2::GeomPoint$required_aes
ggplot2::GeomPoint$draw_panel

```

