---
title: "another experiment"
author: "Evangeline Reynolds"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, dev = "ragg_png")
options(tidyverse.quiet = TRUE)
```




## Intro Thoughts


## Status Quo

```{r}
library(tidyverse)

lyrics_twinkle_mandarin_pinyin <- 
"yī shǎn yī shǎn liàng jīng jīng
mǎn tiān dū shì xiǎo xīng xīng
guà zài tiān biān fàng guāng míng
hǎo xiàng xǔ duō xiǎo yǎn jīng
yī shǎn yī shǎn liàng jīng jīng
mǎn tiān dū shì xiǎo xīng xīng"

lyrics_twinkle_mandarin <- 
"一 闪 一 闪 亮 晶 晶
满 天 都 是 小 星 星
挂 在 天 边 放 光 明
好 像 许 多 小 眼 睛
一 闪 一 闪 亮 晶 晶
满 天 都 是 小 星 星"

melody_twinkle_mandarin <- "ddsslls
ffmmrrd
ssffmmr
ssffmmr
ddsslls
ffmmrrd"


lyrics_twinkle_german <- 
"Fun-kel fun-kel klein-er Stern
Ach wie bist du mir so fern
Wun-der-schön und un-be-kannt
Wie ein strah-lend Di-a-mant
Fun-kel fun-kel klein-er Stern
Ach wie bist du mir so fern"


lyrics_twinkle_danish <- "Fra den fjer-ne mælk-e-vej
Fra den fjer-ne mælk-e-vej,
tit-ter stjern-en ned til mig.
Sølv og guld på him-len står,
ly-ser for os hvor vi går.
Fra den fjer-ne mælk-e-vej,
tit-ter stjer-nen ned til mig"

ggplot() + 
  annotate(geom = "label", x = 0, y = 0, 
           label = lyrics_twinkle_mandarin)
```

## Experiment

```{r}

```



## Closing remarks, Other Relevant Work, Caveats
