---
title: "american-idol"
subtitle: ""
author: ""
output:
  xaringan::moon_reader:
    seal: FALSE
    lib_dir: libs
    css: [default, hygge, ninjutsu]
    nature:
      ratio: 16:9
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---



```{r, include = F}
options(knitr.duplicate.label = "allow")
knitr::opts_chunk$set(fig.width = 6, message = FALSE, warning = FALSE, comment = "", cache = F)
library(flipbookr)
library(tidyverse)
load("current_image.Rdata")
```


```{r, echo = F, eval = FALSE , message = F, warning = F}
xaringanExtra::use_share_again()
```


```{r the_chunk, include = F}
library(ggcirclepack)
songs %>%
  ggplot() + 
  aes(id = "All") +
  geom_circlepack() + 
  geom_circlepack_text(aes(lineheight = I(.7))) +
  aes(fill = I("aliceblue")) +
  coord_equal() +
  aes(id = artist) +
  aes(label = after_stat(area)) + 
  data_mutate_filter(n(), c(artist), .value >= 15) +
  aes(label = str_wrap(after_stat(id), 12)) + 
  data_filter(artist == "Stevie Wonder") + 
  aes(fill = I("plum1")) +
  aes(id = song) +
  aes(label = str_wrap(after_stat(paste0(id, " ", 
                                         area, "X")), 12)) +
  scale_size(range = c(2,3)) +
  data_replace(data = songs |> 
                 filter(artist == "Stevie Wonder") |>
                 mutate(song = str_remove(song, "\\(Stevie Wonder\\)")) |>
                 mutate(song = str_replace(song, "bout", "Bout"))) ->
  p
                

p$data ->
songs_stevie_cleaned

```

`r chunk_reveal(chunk_name = "the_chunk", break_type = "auto")`



```{css, eval = TRUE, echo = FALSE}
.remark-code{line-height: 1.5; font-size: 90%}

@media print {
  .has-continuation {
    display: block;
  }
}

code.r.hljs.remark-code{
  position: relative;
  overflow-x: hidden;
}


code.r.hljs.remark-code:hover{
  overflow-x:visible;
  width: 500px;
  border-style: solid;
}
```

