---
title: "another experiment"
author: "Evangeline Reynolds"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(tidyverse.quiet = TRUE)
```




## Intro Thoughts


## Status Quo

```{r}
library(tidyverse)

compute_group_wax <- function(data, scales){
  
  data %>% 
    mutate(xend = x, 
           y = open, 
           yend = close) %>% 
    mutate(loss_gain =  
             ifelse(close > open, "gain", "loss") |> 
             factor(levels = c("loss", "gain")))
  
}

compute_group_wick <- function(data, scales){
  
  data %>% 
    mutate(xend = x, 
           y = high, 
           yend = low) %>% 
    mutate(loss_gain = 
             ifelse(close > open, "gain", "loss") |> 
             factor(levels = c("loss", "gain")))
  
}


stock_data <- read_csv("https://raw.githubusercontent.com/business-science/tidyquant/ae5a6ee60f58fd2fa0e4b811682601bcc5d96b0b/data-raw/FANG.csv") 

head(stock_data)


library(statexpress)

stock_data %>% 
  slice(1:30) ->
to_plot

to_plot %>% 
  ggplot() + 
  aes(x = date,
      open = open,
      close = close,
      high = high,
      low = low) + 
  # geom_wax sketch
  qlayer(stat = qstat(compute_group_wax,
                      default_aes = aes(color = after_stat(loss_gain))),
         geom = qproto_update(GeomSegment, aes(linewidth = 3))) +
  # geom_wick sketch
  qlayer(stat = qstat(compute_group_wick,
                      default_aes = aes(color = after_stat(loss_gain))),
         geom = GeomSegment)

  
  

       
       

```

## Experiment

```{r}

```



## Closing remarks, Other Relevant Work, Caveats
