---
title: "holiday card with ggstamp"
author: "Evangeline Reynolds"
date: "12/24/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```


```{r card}
url <- "https://images.unsplash.com/photo-1612036795959-6e3e21a015c8?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1471&q=80"
image_credit <- "Jody Confer, Columbia, Missouri" # via unsplash
magick::image_read(url) %>% 
  magick::image_scale(geometry = 400) %>% 
  magick::image_write(format = "png") %>% 
  ggstamp::ggbackdrop(png = .) +
  ggstamp::stamp_tile(height = 60:64,
             width = 93:97,
             x = 50, y = 33,
             alpha = 0, #fill
             size = c(.5,.75,1,.75,.5),
             color = alpha("darkred", .7)) +
  ggstamp::stamp_text(x = 53, y = 12:1*5, 
                      label = paste(1:12, "X")) +
  ggstamp::stamp_png2(png = "noun-partridge-3016488.png", 
                      width = 6, y0 = 60, x0 = 60) +
  ggstamp::stamp_png2(png = "noun-dove-165472.png", 
                      width = 6, y0 = 55, x0 = 60) +
  ggstamp::stamp_png2(png = "noun-hen-703301.png", 
                      width = 6, y0 = 50, x0 = 60) +
  ggstamp::stamp_png2(png = "noun-bird-52580.png", 
                      width = 6, y0 = 45, x0 = 60) +
  ggstamp::stamp_png2(png = "noun-ring-147802.png", 
                      width = 6, y0 = 40, x0 = 60) +
  ggstamp::stamp_png2(png = "noun-goose-38207.png", 
                      width = 7, y0 = 34, x0 = 60) +
  ggstamp::stamp_png2(png = "noun-swan-1200565.png", 
                      width = 7, y0 = 29.5, x0 = 60) +
  ggstamp::stamp_png2(png = "noun-woman-feeding-baby-with-milk-bottle-1922307.png", 
                      width = 6, y0 = 25, x0 = 60) +
  ggstamp::stamp_png2(png = "noun-ballerina-1381034.png", 
                      width = 8, y0 = 20, x0 = 60) +
  ggstamp::stamp_png2(png = "noun-happy-dance-152595.png", 
                      width = 6, y0 = 15, x0 = 60) +
  ggstamp::stamp_text(label = "%>%", size = 5,
                      y = 10, x = 61) +
  ggstamp::stamp_png2(png = "noun-drummer-20148.png", 
                      width = 7, y0 = 5, x0 = 60) +
  theme_void()
```
```{r tree}

my_seq <- rep(1:12, 1:12)

my_pos <- ggstamp::pos_branching(n = length(my_seq), 
                                 width = 1, height = 2)


images <- c("noun-partridge-3016488.png", 
 "noun-dove-165472.png", 
 "noun-hen-703301.png", 
 "noun-bird-52580.png", 
 "noun-ring-147802.png", 
 "noun-goose-38207.png", 
 "noun-swan-1200565.png", 
 "noun-woman-feeding-baby-with-milk-bottle-1922307.png", 
 "noun-ballerina-1381034.png", 
 "noun-happy-dance-152595.png", 
 "noun-pied-piper-2199126.png",
 "noun-drummer-20148.png")


ggstamp::ggcanvas() %>% 
  reduce(
  1:nrow(my_pos),
  ~ .x + ggstamp::stamp_png2(png = images[my_seq][.y],
                    x0y0 = my_pos[.y,]),
  .init = .
) 
```
```{r}
url <- "https://images.unsplash.com/photo-1612037262026-ef4ff27708e7?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80"

my_seq <- rep(1:12, 1:12)

my_pos <- ggstamp::pos_branching(n = length(my_seq), x0 = 40, y0 = 130,
                                 width = 5, height = 10)

image_credit <- "Jody Confer, Columbia, Missouri" # via unsplash
magick::image_read(url) %>% 
  magick::image_scale(geometry = 400) %>% 
  magick::image_write(format = "png") %>% 
  ggstamp::ggbackdrop(png = .) +
  ggstamp::stamp_tile(height = 142:146,
             width = 93:97,
             x = 50, y = 75,
             alpha = 0, #fill
             size = c(.5,.75,1,.75,.5),
             color = alpha("darkred", .7)) ->
my_card; my_card

my_card %>% 
  reduce(
  1:nrow(my_pos),
  ~ .x + ggstamp::stamp_png2(png = images[my_seq][.y], width = 7,
                             # color = rep(c("darkolivegreen", "darkgreen"), 39)[.y],
                    x0y0 = my_pos[.y,]),
  .init = .
)  +
  theme_void()
```

