---
title: "another experiment"
author: "Evangeline Reynolds"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: TRUE
---

```{r setup, include=T}
knitr::opts_chunk$set(echo = TRUE)
options(tidyverse.quiet = TRUE)



library(ggplot2)
p <- ggplot(mtcars, 
            aes(x = factor(cyl), 
                fill = factor(cyl))) +
  geom_bar() + 
  geom_point(stat = StatCount, size = 7) + 
  geom_tile(aes(y = -2, fill = NULL))

p +
  theme_void(ink = "plum", paper = "cornsilk", base_size = 18)

last_plot() + 
  theme(geom = element_geom(ink = "plum")) + 
  theme(plot.background = element_rect(fill = "whitesmoke", 
                                       linewidth = 0
                                       ))
```



```{r}
library(ggplot2)
theme_void2 <- function (base_size = 11, base_family = "", header_family = NULL, 
    base_line_size = base_size/22, 
    # base_rect_size = base_size/22
    base_rect_size = 0, #<< 1. change the border size
    ink = "black", 
    paper = alpha("white", 0) #<< 2. change the paper color
    ) 
{
    half_line <- base_size/2
    t <- theme(line = element_blank(), 
               rect = element_blank(), 
               # rect = element_rect(fill = paper, colour = ink, #<< 3. change the rectangle setting
                                   # linewidth = base_rect_size, linetype = 1), 
        text = element_text(family = base_family, face = "plain", 
            colour = ink, size = base_size, lineheight = 0.9, 
            hjust = 0.5, vjust = 0.5, angle = 0, margin = margin(), 
            debug = FALSE), title = element_text(family = header_family), 
        spacing = unit(half_line, "pt"), margins = margin(half_line, 
            half_line, half_line, half_line), axis.text = element_blank(), 
        axis.title = element_blank(), axis.ticks.length = rel(0), 
        axis.ticks.length.x = NULL, axis.ticks.length.x.top = NULL, 
        axis.ticks.length.x.bottom = NULL, axis.ticks.length.y = NULL, 
        axis.ticks.length.y.left = NULL, axis.ticks.length.y.right = NULL, 
        axis.minor.ticks.length = NULL, legend.box = NULL, 
        legend.key.size = unit(1.2, "lines"), legend.position = "right", 
        legend.text = element_text(size = rel(0.8)), 
        legend.title = element_text(hjust = 0), legend.key.spacing = rel(1), 
        legend.margin = rel(0), legend.box.margin = rel(0), legend.box.spacing = unit(0.2, 
            "cm"), legend.ticks.length = rel(0.2), strip.clip = "on", 
        strip.text = element_text(size = rel(0.8)), strip.switch.pad.grid = rel(0.5), 
        strip.switch.pad.wrap = rel(0.5), panel.ontop = FALSE, 
        panel.spacing = NULL, 
        
        plot.margin = rel(0), plot.title = element_text(size = rel(1.2), 
            hjust = 0, vjust = 1, margin = margin(t = half_line)), 
        plot.title.position = "panel", plot.subtitle = element_text(hjust = 0, 
            vjust = 1, margin = margin(t = half_line)), plot.caption = element_text(size = rel(0.8), 
            hjust = 1, vjust = 1, margin = margin(t = half_line)), 
        plot.caption.position = "panel", plot.tag = element_text(size = rel(1.2), 
            hjust = 0.5, vjust = 0.5), plot.tag.position = "topleft", 
        # try to make plot.background more flexible
        plot.background = element_rect(fill = paper),  #<< 4. add the plot background
            # try to make geom responsive
        geom = element_geom(ink = ink, paper = paper, accent = "#3366FF", linewidth = base_line_size, 
            borderwidth = base_line_size, linetype = 1L, bordertype = 1L, 
            family = base_family, fontsize = base_size, pointsize = (base_size/11) * 
                1.5, pointshape = 19), 
        complete = TRUE)
    ggplot2:::ggplot_global$theme_all_null %+replace% t
}


ggplot(mtcars, 
            aes(x = factor(cyl), 
                fill = factor(cyl))) +
  geom_bar() + 
  geom_point(stat = StatCount, size = 7) + 
  geom_tile(aes(y = -2, fill = NULL))

last_plot() + 
  theme_void()

last_plot() + 
  theme_void2()

last_plot() + 
  theme_void(ink = "plum", paper = "cornsilk")

last_plot() + 
  theme_void2(ink = "plum", paper = "cornsilk")

last_plot() + 
  ggraph::theme_graph(background = "cornsilk") + 
  theme(geom = element_geom(ink = "plum"))
  
```


```{r}

theme_grey = function (base_size = 11, base_family = "", header_family = NULL, 
    base_line_size = base_size/22, base_rect_size = base_size/22, 
    ink = "black", paper = "white") 
{
    half_line <- base_size/2
    t <- theme(
      line = element_line(colour = ink, linewidth = base_line_size, 
        linetype = 1, lineend = "butt"), 
        rect = element_rect(fill = paper, colour = ink, linewidth = base_rect_size, linetype = 1), ## update
        text = element_text(family = base_family, face = "plain", 
            colour = ink, size = base_size, lineheight = 0.9, 
            hjust = 0.5, vjust = 0.5, angle = 0, margin = margin(), 
            debug = FALSE), title = element_text(family = header_family), 
        spacing = unit(half_line, "pt"), 
      margins = margin(half_line, 
            half_line, half_line, half_line), 
      geom = element_geom(ink = ink, paper = paper, accent = "#3366FF", linewidth = base_line_size, 
            borderwidth = base_line_size, linetype = 1L, bordertype = 1L, 
            family = base_family, fontsize = base_size, pointsize = (base_size/11) * 
                1.5, pointshape = 19), 
      axis.line = element_blank(), 
        axis.line.x = NULL, axis.line.y = NULL, axis.text = element_text(size = rel(0.8), 
            colour = col_mix(ink, paper, 0.305)), axis.text.x = element_text(margin = margin(t = 0.8 * 
            half_line/2), vjust = 1), axis.text.x.top = element_text(margin = margin(b = 0.8 * 
            half_line/2), vjust = 0), axis.text.y = element_text(margin = margin(r = 0.8 * 
            half_line/2), hjust = 1), axis.text.y.right = element_text(margin = margin(l = 0.8 * 
            half_line/2), hjust = 0), axis.text.r = element_text(margin = margin(l = 0.8 * 
            half_line/2, r = 0.8 * half_line/2), hjust = 0.5), 
        axis.ticks = element_line(colour = col_mix(ink, paper, 
            0.2)), axis.ticks.length = rel(0.5), axis.ticks.length.x = NULL, 
        axis.ticks.length.x.top = NULL, axis.ticks.length.x.bottom = NULL, 
        axis.ticks.length.y = NULL, axis.ticks.length.y.left = NULL, 
        axis.ticks.length.y.right = NULL, axis.minor.ticks.length = rel(0.75), 
        axis.title.x = element_text(margin = margin(t = half_line/2), 
            vjust = 1), axis.title.x.top = element_text(margin = margin(b = half_line/2), 
            vjust = 0), axis.title.y = element_text(angle = 90, 
            margin = margin(r = half_line/2), vjust = 1), axis.title.y.right = element_text(angle = -90, 
            margin = margin(l = half_line/2), vjust = 1), legend.background = element_rect(colour = NA), 
        legend.spacing = rel(2), legend.spacing.x = NULL, legend.spacing.y = NULL, 
        legend.margin = NULL, legend.key = NULL, legend.key.size = unit(1.2, 
            "lines"), legend.key.height = NULL, legend.key.width = NULL, 
        legend.key.spacing = NULL, legend.text = element_text(size = rel(0.8)), 
        legend.title = element_text(hjust = 0), legend.ticks.length = rel(0.2), 
        legend.position = "right", legend.direction = NULL, legend.justification = "center", 
        legend.box = NULL, legend.box.margin = rel(0), legend.box.background = element_blank(), 
        legend.box.spacing = rel(2), panel.background = element_rect(fill = col_mix(ink, 
            paper, 0.925), colour = NA), panel.border = element_blank(), 
        panel.grid = element_line(colour = paper), panel.grid.minor = element_line(linewidth = rel(0.5)), 
        panel.spacing = NULL, panel.spacing.x = NULL, panel.spacing.y = NULL, 
        panel.ontop = FALSE, strip.background = element_rect(fill = col_mix(ink, 
            paper, 0.854), colour = NA), strip.clip = "on", strip.text = element_text(colour = col_mix(ink, 
            paper, 0.105), size = rel(0.8), margin = margin(0.8 * 
            half_line, 0.8 * half_line, 0.8 * half_line, 0.8 * 
            half_line)), strip.text.x = NULL, strip.text.y = element_text(angle = -90), 
        strip.text.y.left = element_text(angle = 90), strip.placement = "inside", 
        strip.placement.x = NULL, strip.placement.y = NULL, strip.switch.pad.grid = unit(half_line/2, 
            "pt"), strip.switch.pad.wrap = unit(half_line/2, 
            "pt"), plot.background = element_rect(colour = paper), 
        plot.title = element_text(size = rel(1.2), hjust = 0, 
            vjust = 1, margin = margin(b = half_line)), plot.title.position = "panel", 
        plot.subtitle = element_text(hjust = 0, vjust = 1, margin = margin(b = half_line)), 
        plot.caption = element_text(size = rel(0.8), hjust = 1, 
            vjust = 1, margin = margin(t = half_line)), plot.caption.position = "panel", 
        plot.tag = element_text(size = rel(1.2), hjust = 0.5, 
            vjust = 0.5), plot.tag.position = "topleft", plot.margin = NULL, 
        complete = TRUE)
    ggplot_global$theme_all_null %+replace% t
}
```




## Intro Thoughts


## Status Quo

```{r}
library(tidyverse)

```

## Experiment

```{r}
ggraph::theme_graph()
```



## Closing remarks, Other Relevant Work, Caveats
