---
title: "tablebuildup"
subtitle: ""
author: ""
output:
  xaringan::moon_reader:
    seal: FALSE
    lib_dir: libs
    css: [default, hygge, ninjutsu]
    nature:
      ratio: 16:9
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---



```{r, include = F}
options(knitr.duplicate.label = "allow")
knitr::opts_chunk$set(fig.width = 6, message = FALSE, warning = FALSE, comment = "", cache = F)
library(flipbookr)
library(tidyverse)
load("current_image.Rdata")
```


```{r, echo = F, eval = FALSE , message = F, warning = F}
xaringanExtra::use_share_again()
```


```{r the_chunk, include = F}
tidytitanic::tidy_titanic |>
  ggtable() |>
  set_rows(sex) |>
  set_cols(survived) |>
  set_cols(age) |>
  set_rows(NULL) |>
  set_rows(c(sex, survived)) |>
  set_cols(c(age, class)) |>
  set_cols(class) |>
  set_rows(survived) |>
  set_cols(NULL)
```

`r chunk_reveal(chunk_name = "the_chunk", break_type = "auto", )`


---


`r chunk_reveal(chunk_name = "the_chunk2")`


```{r the_chunk2, include = F}
tidytitanic::tidy_titanic |>
  ggtable()

last_table() |>
  set_cols(sex)

last_table() |>
  set_rows(survived)

last_table() |>
  set_cols(NULL)
```

```




```{css, eval = TRUE, echo = FALSE}
.remark-code{line-height: 1.5; font-size: 80%}

@media print {
  .has-continuation {
    display: block;
  }
}

code.r.hljs.remark-code{
  position: relative;
  overflow-x: hidden;
}


code.r.hljs.remark-code:hover{
  overflow-x:visible;
  width: 500px;
  border-style: solid;
}
```

