---
title: "Logit"
subtitle: "Using flipbookr and xaringan"
author: ""
output:
  xaringan::moon_reader:
    lib_dir: libs
    seal: false
    css: [default, hygge, ninjutsu]
    nature:
      ratio: 16:9
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---


class: inverse, middle
background-image: url(https://images.unsplash.com/photo-1586165368502-1bad197a6461?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=958&q=80)
background-size: cover




# Logit

### Gina Reynolds

<br>
<br>
<br>

```{r, include = F}
# This is the recommended set up for flipbooks
# you might think about setting cache to TRUE as you gain practice --- building flipbooks from scratch can be time consuming
knitr::opts_chunk$set(fig.width = 7, fig.height = 5, message = F, warning = FALSE, comment = "", cache = T)

options(tibble.print_min = 55)
options(knitr.duplicate.label = "allow")
options(width=300) # prevents data wrapping
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

---

`r flipbookr::chunk_reveal("hotel")`

```{r hotel, include = F}
library(tidyverse)
library(broom)

read_csv('https://tidymodels.org/start/case-study/hotels.csv') %>%
  mutate(across(where(is.character), as.factor)) ->
hotels  

dim(hotels)

hotels %>% 
  mutate(ind_children = as.numeric(children == "children") ) %>% 
  glm(ind_children ~ lead_time, 
  family = binomial(link = "logit"),
  data = .) %>%
  augment() %>% 
  ggplot() + 
  aes(x = lead_time, y = ind_children) +
  geom_jitter(height = .1) + 
  geom_point(aes(y = exp(.fitted)/(1+exp(.fitted))), alpha = .01, color = "blue")
```

---

`r flipbookr::chunk_reveal("mtcars")`


```{r mtcars, include=F}
library(tidyverse)
library(broom)

glm(am ~ disp, 
  family = binomial(link = "logit"),
  data = mtcars
) %>%
  augment() %>% 
  mutate(linked = 
           exp(.fitted)/(1+exp(.fitted))) %>% 
  mutate(force = (linked > .5) %>% 
           as.numeric()) ->
logistic_augmented
  
logistic_augmented %>% 
  ggplot() + 
  aes(x = disp, y = am, color = am) +
  geom_point() + 
  geom_point(aes(y = linked, 
                 shape = am == force)) + 
  scale_shape_manual(values = c(4, 1)) + 
  scale_color_viridis_c(end = .7)
```
