---
title: "legendry"
subtitle: ""
author: ""
output:
  xaringan::moon_reader:
    seal: FALSE
    lib_dir: libs
    css: [default, hygge, ninjutsu]
    nature:
      ratio: 16:9
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---



```{r, include = F}
options(knitr.duplicate.label = "allow")
knitr::opts_chunk$set(fig.width = 6, message = FALSE, warning = FALSE, comment = "", cache = F)
library(flipbookr)
library(tidyverse)
load("current_image.Rdata")
```


```{r, echo = F, eval = FALSE , message = F, warning = F}
xaringanExtra::use_share_again()
```


```{r the_chunk, include = F}
library(tidyverse)
library(legendry)
data.frame(
  category = c("Meat", "Meat", "Vegetables", "Vegetables", "Dairy"),
  food     = c("Beef", "Chicken", "Carrots", "Onions", "Cheese"),
  gram     = c(85,  85, 150, 210, 225),
  calories = c(245, 185, 45, 80, 240)) %>% 
  mutate(food_category = interaction(food, category)) |>
  mutate(category_food = paste(category, food)) |>
  ggplot() +
  aes(x = food_category, 
      y = calories) +
  theme_classic(base_size = 15) + #BREAK
  geom_col() + #BREAK
  guides(x = "axis_nested") + #BREAK
  aes(fill = category_food) + #BREAK
  guides(fill = "legend_group") + #BREAK
  labs(x = NULL, fill = NULL) + #BREAK
  guides(y = guide_axis_nested(
    key_range_manual(start = 0, end = 100, 
                     name = "low calories"))
    ) + #BREAK
  theme(axis.text.y.left = 
          element_text(angle = 90, hjust = 0.5)) + 
  theme(axis.ticks.x = element_blank()) +
  scale_y_continuous(expand = expansion(mult = c(0, .2))) #BREAK
```

`r chunk_reveal(chunk_name = "the_chunk", break_type = "user", widths = c(2,3))`



```{css, eval = TRUE, echo = FALSE}
.remark-code{line-height: 1.5; font-size: 100%}

@media print {
  .has-continuation {
    display: block;
  }
}

code.r.hljs.remark-code{
  position: relative;
  overflow-x: hidden;
}


code.r.hljs.remark-code:hover{
  overflow-x:visible;
  width: 500px;
  border-style: solid;
}
```

