---
format: revealjs
editor: source
---



```{r, include = F}
options(knitr.duplicate.label = "allow")
knitr::opts_chunk$set(fig.width = 6, message = FALSE, warning = FALSE, comment = "", cache = F)
library(flipbookr)
library(tidyverse)
load("current_image.Rdata")
```



```{r the_chunk, include = F}
library(infer)

gss |> tibble() |>
  specify(age ~ partyid) |>
  calculate(stat = "F") ->
F_hat

gss |>
  specify(age ~ partyid) |>
  hypothesize(null = "independence") |>
  generate(reps = 1000, 
           type = "permute") |>
  calculate(stat = "F") |> 
  visualize() +
  shade_p_value(obs_stat = F_hat, 
                direction = "greater")
```

`r chunq_reveal(chunk_name = "the_chunk", break_type = "auto")`



```{css, eval = TRUE, echo = FALSE}
.remark-code{line-height: 1.5; font-size: 120%}

@media print {
  .has-continuation {
    display: block;
  }
}

code.r.hljs.remark-code{
  position: relative;
  overflow-x: hidden;
}


code.r.hljs.remark-code:hover{
  overflow-x:visible;
  width: 500px;
  border-style: solid;
}
```

