---
title: "another experiment"
author: "Evangeline Reynolds"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, dev = "ragg_png")
options(tidyverse.quiet = TRUE)
```




## Intro Thoughts


## Status Quo

```{r}
library(tidyverse)
```

## Experiment

```{r}
PAIR_code_umap_mammoth_url <- "https://raw.githubusercontent.com/PAIR-code/understanding-umap/refs/heads/master/raw_data/mammoth_3d.json"

library(ggdims)



mammoth_df <- PAIR_code_umap_mammoth_url |>
  jsonlite::fromJSON() |>
  as.data.frame() 
```


```{r, fig.height=5, dpi = 300}

setup_data_confetti <- function(data, params){
  
  data$fill <-  sample(
          x = colors(),
          size = nrow(data), 
          replace = TRUE
          ) 
  
  data
    
}

new_mapping <- aes(fill = "grey", shape = 21,
               size = 4, color = from_theme(paper),
               stroke = .2, alpha = .5)

GeomConfetti <- ggproto("GeomConfetti",
                        GeomPoint,
                        default_aes = GeomPoint$default_aes |>
                          modifyList(new_mapping),
                        setup_data = setup_data_confetti
                        )

geom_confetti <- make_constructor(GeomConfetti)


library(ggplot2)
ggplot(cars) + 
  aes(speed, dist) + 
  geom_confetti()
```

```{r, fig.width=10, fig.height=5, dpi = 300}

'
mammoth_df <- 
  PAIR_code_umap_mammoth_url |> #<<
  jsonlite::fromJSON() |>
  as.data.frame() 

mammoth_df |> #<<
  ggplot() + 
  aes(x = V1, y = V2) + 
  geom_confetti() ' |>
  ggram::ggram(code = _, widths = c(1,1.3), "First two dimensions of the 3D Smithsonian Mammoth dataset, 10000 observations 🦣", subtitle = "The now-canonical mammoth dataset can be a fun first-taste when exploring dimension reduction techniques,\nfor going from still-familiar and friendly 3 dimentional data to the lower-dim representations.",
               caption = "geom_confetti is a variant of geom_point, whose colors randomly sampled from R colors() which 'returns the built-in color names'")# 

```



```{r}
update_geom_defaults("point", aes(fill = "grey", color = "white", size = 1))

'
colors_random <-
        sample(
          x = colors(),
          size = nrow(mammoth_df), 
          replace = TRUE
          )
          

ggplot(data = mammoth_df) + 
  aes(x = V1, y = V2) + 
  geom_point(
    alpha = .5,
    fill = colors_random #<< 
  )' |>
  ggram::ggram(code = _, widths = c(1,1.3), "First two dimensions of the 3D Smithsonian Mammoth dataset, 10000 observations 🦣", subtitle = "The now-canonical mammoth dataset can be a fun first-taste when exploring dimension reduction techniques, for going from familiar and friendly 3 dimentional data to the lower-dim representations.",
               caption = "Point colors randomly sampled from R colors() which 'returns the built-in color names'")# + 
  
  # annotate("label", x = I(.2), y = I(.2), size = 1.7,
  #          label = "ggplot2 is a system for declaratively creating graphics, based on The Grammar of Graphics. You provide the data, tell ggplot2 how to map variables to aesthetics, what graphical primitives to use, and it takes care of the details." |> str_wrap(30))

# library(patchwork)

# patchwork::plot_annotation()
```


```{r, cache = T}
colors_random <- colors() |> 
        sample(
          nrow(mammoth_df), 
          replace = T
          )


p1 <- mammoth_df |> 
  ggplot() + 
  aes(dims = dims(V1:V3),
      fill = I(colors_random)) + 
  geom_pca() + 
  labs(title = "PCA")

p2 <- mammoth_df |> 
  ggplot() + 
  aes(dims = dims(V1:V3),
      fill = I(colors_random)) + 
  geom_tsne() + 
  labs(title = "t-SNE")

p3 <- mammoth_df |> 
  ggplot() + 
  aes(dims = dims(V1:V3),
      fill = I(colors_random)) + 
  geom_umap() + 
  labs(title = "UMAP")



p1 + p2 + p3
```



## Closing remarks, Other Relevant Work, Caveats
