---
title: "another experiment"
author: "Evangeline Reynolds"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(tidyverse.quiet = TRUE)
```




## Intro Thoughts


## Status Quo

```{r cars}
library(tidyverse)

nudge_x = -1
nudge_y = 12
pad_x = 0
pad_y = 0

ggplot(cars) + 
  aes(x = speed, y = dist) + 
  geom_point() + 
  geom_text(data = . %>% slice(15),
            label = "my insight",
            nudge_x = nudge_x,
            nudge_y = nudge_y, 
            vjust = -sign(nudge_y),
            hjust = -sign(nudge_x),
            ) +
  geom_segment(data = . %>% slice(15),
               aes(xend = after_stat(x) + nudge_x + pad_x,
                   yend = after_stat(y) + nudge_y + pad_y))
```


```{r}
add_callout <- function(data = data, 
                        label = "Hello World!", 
                        nudge_x = .00001, # no zero length allowed for curves.
                        nudge_y = .00001, 
                        prop_pad_x = .1, 
                        prop_pad_y = .1, 
                        curvature = 0, 
                        hjust = NULL, 
                        vjust = NULL, ... ){

  if(is.null(hjust)){hjust = -sign(nudge_x) == 1}
  if(is.null(vjust)){vjust = -sign(nudge_y) == 1}

  
  list(
    geom_text(data = data,
            label = label,
            nudge_x = nudge_x,
            nudge_y = nudge_y, 
            vjust = vjust,
            hjust = hjust,
            ...
            ),
    geom_curve(data = data,
               aes(xend = after_stat(x) + nudge_x - prop_pad_x*nudge_x,
                   yend = after_stat(y) + nudge_y - prop_pad_y*nudge_y,
                   # x = after_scale(x) + prop_pad_x*nudge_x,
                   # y = after_scale(y) + prop_pad_y*nudge_y
                   ),
               curvature = curvature),
    ...
  )
    
}


ggplot(cars) +
  aes(speed, dist) + 
  geom_point() + 
  add_callout(data = . %>% slice(3), 
              nudge_y = -10, 
              nudge_x = 1)


gapminder::gapminder %>% 
  filter(year == 2002) %>% 
  ggplot() + 
  aes(x = gdpPercap, y = lifeExp) + 
  geom_point() + 
  add_callout(data = . %>% 
                filter(country == "Japan"),
              nudge_x = 1000,
              nudge_y = 2,
              label = "Japan" 
              ) + 
  add_callout(data = . %>% 
                filter(country == "Australia"),
              nudge_x = 1500,
              nudge_y = -10,
              label = "Here we have Australia",
              hjust = .25,
              curvature = -.2)


last_plot() + 
  aes(color = lifeExp)


gapminder::gapminder %>% 
  filter(year == 2002) %>% 
  ggplot() + 
  aes(x = gdpPercap, y = lifeExp, color = gdpPercap) + 
  geom_point() + 
  add_callout(data = . %>% 
                filter(country == "United States"),
              label = "US has high GDP per capita,\nbut low life expectancy compared with peers")
  



```

## Experiment

```{r}

```



## Closing remarks, Other Relevant Work, Caveats
