---
title: "another experiment"
author: "Evangeline Reynolds"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(tidyverse.quiet = TRUE)
```

```{r}



```


## Intro Thoughts


## Status Quo

```{r cars}
library(tidyverse)

data.frame(x = -1, y = -1, xend = 1, yend = 1) |>
  ggplot() + 
  coord_cartesian(xlim = c(-2,2), ylim = c(-2,2)) +
  aes(x, y, xend = xend, yend = yend) + 
  geom_point(alpha = .15, color = "red") +
  geom_label(label = "Insightful\nComment", 
             label.padding = unit(0.7, "lines"),
             vjust = .5, 
             hjust = 1,
             lineheight = .7,
             alpha = 0, # remove background
             label.size = 0) +
  annotate(geom = "point", x = 1, y = 1, color = "blue")

last_plot() +
  geom_segment(arrow = 
               arrow(ends = "last", length = unit(.1, "inches"), type = "closed"))

ggwipe::last_plot_wipe_last() +
  geom_curve(arrow = 
               arrow(ends = "last", length = unit(.1, "inches")),
             curvature = .25)



ggwipe::last_plot_wipe_last() +
  geom_path(data = data.frame(x = -50:50/50, y = -50:50/50),
            aes(xend = NULL, yend = NULL),
            arrow = 
               arrow(ends = "last", length = unit(.1, "inches")))


# from ggbump
sigmoid <- function(x_from, x_to, y_from, y_to, smooth = 5, n = 100, direction = "x") {
  if(!direction %in% c("x", "y")) {stop("Only the directions x or y is allowed.")}

  if(direction == "x") {
    x <- seq(-smooth, smooth, length = n)
    y <- exp(x) / (exp(x) + 1)
    out <- data.frame(x = (x + smooth) / (smooth * 2) * (x_to - x_from) + x_from,
                      y = y * (y_to - y_from) + y_from)
  }

  if(direction == "y") {
    y <- seq(-smooth, smooth, length = n)
    x <- exp(y) / (exp(y) + 1)
    out <- data.frame(y = (y + smooth) / (smooth * 2) * (y_to - y_from) + y_from,
                      x = x * (x_to - x_from) + x_from)
  }
  out
}

sigmoid(x_from = -1, x_to = 1, y_from = -1, y_to = 1, smooth = 5) ->
  sigmoid_path


ggwipe::last_plot_wipe_last() +
  geom_path(data = sigmoid_path,
            aes(xend = NULL, yend = NULL),
            arrow = 
               arrow(ends = "last", length = unit(.1, "inches")))

```

```{r}
ggplot(cars) + 
  aes(speed, dist) + 
  geom_point() + 
  geom_point(data = . %>% .[1,], color = "red")
  # geom_label_link(data = . %>% [1,],
  #                 label = "a single experiment",
  #                 label_distance_sd = 2, 
  #                 label_direction = "SW",
  #                 exit_position = "SW",
  #                 pointer_pad)
`%||%` <- ggplot2:::`%||%`

compute_labellink <- function(data, scales, label_direction = 180, prop_range = .1, prop_pointer_pad = .01, hjust = NULL, vjust = NULL, which_index = NULL, which_id = NULL){
  
  if(is.null(data$id)){data$id <- "hello world"}
  if(is.null(which_index)){which_index <- which(data$id == which_id)}
  
  data$default_label <- data$id
  
  
  range_x <- diff(range(data$x))
  range_y <- diff(range(data$y)) # look at range of plot?
  data$x_in_range <- (data$x-mean(range(data$x)))/range_x
  data$y_in_range <- (data$y-mean(range(data$y)))/range_y
  
  data$angle_from_midrange_degrees <- sign(data$y_in_range)* 
    atan(data$y_in_range/data$x_in_range)/pi*180
  if(is.null(label_direction)){
    data$label_direction <- data$angle_from_midrange_degrees
    } else {
    data$label_direction <- label_direction
  }
  
  data$xdir <- cos(pi*data$label_direction / 180)
  data$ydir <- sin(pi*data$label_direction / 180)
  data$xpush <- range_x * prop_range * data$xdir
  data$ypush <- range_y * prop_range * data$ydir
  data$hjust_default <- sign(data$xdir) != 1
  data$vjust_default <- sign(data$ydir) != 1

  data$more_x_than_y <- abs(data$xdir) > abs(data$ydir)
  
  if(is.null(hjust)){data$hjust <- ifelse(data$more_x_than_y, data$hjust_default, .5)
  }else{data$hjust <- hjust}
  if(is.null(vjust)){data$vjust <- ifelse(data$more_x_than_y, .5, data$vjust_default)
  }else{data$vjust <- vjust}

  data |> 
    mutate(x = x + xpush) |>
    mutate(y = y + ypush) |>
    mutate(xend = x - (xpush)) |>
    mutate(yend = y - (ypush)) |>
    # mutate(hjust = hjust) |>
    # mutate(vjust = vjust) |> 
    slice(which_index)
  
}

StatLabellink <- ggproto("Labellink",
                         Stat,
                         compute_panel = compute_labellink,
                         default_aes = aes(label = after_stat(default_label))
                         )
```


```{r}
gapminder::gapminder |>
  filter(year == 2002) |> 
  select(id = country, x = lifeExp, y = gdpPercap) |>
  compute_labellink(which_id = "Chile")

gapminder::gapminder |>
  filter(year == 2002) |> 
  select(id = country, x = lifeExp, y = gdpPercap) |>
  compute_labellink(which_index = 3)

gapminder::gapminder |>
  filter(year == 2002) |> 
  select(x = lifeExp, y = gdpPercap) |>
  compute_labellink(which_index = 3)

gapminder::gapminder |>
  filter(year == 2002) |> 
  select(id = country, x = lifeExp, y = gdpPercap) |>
  ggplot() + 
  aes(x = x, y = y, id = id) + 
  geom_point() + 
  layer("label", "labellink", position = "identity",
        params = list(which_id = "Chile")) + 
  layer("segment", "labellink", position = "identity",
        params = list(which_id = "Chile")) + 
  scale_x_log10()

layer_data(i = 2)
```



```{r}
ggplot(cars) + 
  aes(speed, dist) + 
  geom_point() + 
  layer("segment", 
        "labellink", 
        position = "identity", 
        # data = cars[23,], 
        params = list(which_index = 23, arrow = 
                        arrow(ends = "last", 
                              length = unit(.1, "inches"), 
                              type = "closed"))) +
  layer("label", 
        "labellink", 
        position = "identity",  
        # data = cars[23,],
        params = list(which_index = 23, 
                      label = "let me tell you about this point" |> str_wrap(15),
                      alpha = 0,
                      lineheight = .8,
                      label.size = 0,
                      label.padding = unit(0.7, "lines"))) + 
  layer("point",
        "labellink",
        position = "identity",
        # data = cars[23,],
        params = list(which_index = 23, 
                      color = "red"))



```


```{r}
geom_labellink <- function(  mapping = NULL,
  data = NULL,
  position = "identity",
  na.rm = FALSE,
  show.legend = NA,
  inherit.aes = TRUE, ...){

  
  list( 
    
    layer("segment", 
        "labellink", 
        position = position, 
        data = data, 
        mapping = mapping,
            show.legend = show.legend,
    inherit.aes = inherit.aes,
        params = list(arrow = 
                        arrow(ends = "last", 
                              length = unit(.1, "inches"), 
                              type = "closed"), na.rm = na.rm,
                      ...)),
    
  layer("label", 
        "labellink", 
        position = position, 
        data = data, 
        mapping = mapping, 
            show.legend = show.legend,
    inherit.aes = inherit.aes,
        params = list(
                      alpha = 0,
                      lineheight = .8,
                      label.size = 0,
                      label.padding = unit(0.4, "lines"), 
                      na.rm = na.rm,
                      ...)) 
  )

  
}
```


```{r}
ggplot(cars, aes(speed, dist)) +
  geom_point() + 
  geom_labellink(which_index = 23,
                 label = "hello.\nI'm a\nlabel link.",
                 vjust = .5) + 
  geom_labellink(which_index = 29,
                 label = "Here's another\npoint of interest",
                 label_direction = -45,
                 vjust = .5,
                 prop_pointer_pad = .1)


gapminder::gapminder |>
  filter(year == 2002) |>
ggplot() + 
  aes(gdpPercap, lifeExp) +
  geom_point(color = "darkgray") + 
  aes(label = country) + 
  geom_labellink(which_index = 5,
                 label_direction = -54,
                 prop_range = .5, 
                 hjust = .3,
                 prop_pointer_pad = .05)

last_plot() + 
  scale_x_log10()
```


```{r}
gapminder::gapminder |>
  filter(year == 2002) |>
ggplot() + 
  aes(gdpPercap, lifeExp) +
  geom_point(color = "darkgray") + 
  geom_labellink(which_id = "Chile",
                 aes(id = country),
                 label_direction = 45) + 
  geom_labellink(which_id = "United States",
                 aes(id = country),
                 label = "The US is here",
                 label_direction = -100)

last_plot() + 
  scale_x_log10()



gapminder::gapminder |>
  filter(year == 2002) |>
ggplot() + 
  aes(gdpPercap, lifeExp, id = country) +
  geom_point(color = "darkgray") + 
  geom_labellink(which_id = "Brazil",
                 label = "People want to\nknow about Brazil",
                 label_direction = -70,
                 prop_range = .2) + 
  geom_labellink(which_id = "Norway",
                 label = "Here is Norway",
                 label_direction = -120)
```


## Alternative: contributed from Teun Van Den Brand (https://github.com/teunbrand/ggplot-extension-club/discussions/8)


```{r,fig.height=4, fig.width=4}
gapminder::gapminder |>
  filter(year == 2002) |>
  ggplot() +
  aes(gdpPercap, lifeExp) +
  geom_point(colour = "darkgrey") +
  ggrepel::geom_text_repel(
    aes(label = c("Chile" = "Chile", 
                  "United States" = 
                    "The US is here")[as.character(country)]),
    na.rm = TRUE, 
    box.padding = unit(1, "cm"),
    point.padding = unit(5, "mm"),
    arrow = arrow(length = unit(2, "mm"), 
                  type = "closed")
  )

layer_data()
```

