---
title: "broom viz"
author: "Evangeline Reynolds"
date: "2/13/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)

```


```{r cars}
mtcars %>% 
  select(mpg, cyl, hp, disp) %>% 
  remove_missing() %>% 
  mutate(mpg_sd = mpg/sd(mpg)) %>% 
  mutate(cyl_sd = cyl/sd(cyl)) %>% 
  mutate(disp_sd = disp/sd(disp)) %>% 
  mutate(hp_sd = hp/sd(hp)) %>% 
  lm(mpg_sd ~ cyl_sd + disp_sd + hp_sd, data = .) ->
m1 

confint(m1) %>% 
  as_tibble()  ->
confint_m1
  
m1 %>% 
  broom::tidy() %>% 
  bind_cols(confint(m1) %>% as_tibble()) %>% 
  slice(-1) %>% 
  ggplot() + 
  aes(y = term, x = estimate) + 
  geom_point() + 
  geom_segment(aes(x = `2.5 %`, xend = `97.5 %`, yend = term)) +
  geom_vline(xintercept = 0, linetype = "dashed")
```
```{r}


mtcars %>% skimr::skim() %>% 
  data.frame() %>% 
  filter(stat == "sd") ->
skimmed

# mtcars %>% 
#   lm(mpg ~ cyl + disp + hp, data = .) %>% 
#   broom::tidy() %>% 
#   rename(variable = term) %>% 
#   left_join(skimmed) %>% 
#   mutate(estimate_sd = estimate * value) %>% 
#   ggplot() + 
#   aes(y = term, x = estimate_sd) + 
#   geom_point() + 
#   geom_vline(xintercept = 0, linetype = "dashed")

```
