---
title: "Effect size plot OLS"
subtitle: "Using flipbookr and xaringan"
author: "Me"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: [default, hygge, ninjutsu]
    nature:
      ratio: 16:9
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---


```{r, include = F}
# This is the recommended set up for flipbooks
# you might think about setting cache to TRUE as you gain practice --- building flipbooks from scratch can be time consuming
knitr::opts_chunk$set(fig.width = 6, fig.height = 4, message = F, warning = FALSE, comment = "", cache = F)

options(tibble.print_min = 55)
options(knitr.duplicate.label = "allow")
options(width=300) # prevents data wrapping
```


```{css, eval = TRUE, echo = FALSE}
.remark-code{line-height: 1.5; font-size: 70%}

@media print {
  .has-continuation {
    display: block;
  }
}

code.r.hljs.remark-code{
  position: relative;
  overflow-x: hidden;
}


code.r.hljs.remark-code:hover{
  overflow-x:visible;
  width: 500px;
  border-style: solid;
}
```


---


`r flipbookr::chunk_reveal("setup", left_assign = "detect")`


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)

```


---


`r flipbookr::chunk_reveal("cars", left_assign = "detect")`


```{r cars, include = FALSE}
mtcars %>% 
  select(mpg, cyl, hp, disp) %>% 
  remove_missing() %>% 
  mutate(mpg_sd = mpg/sd(mpg)) %>% 
  mutate(cyl_sd = cyl/sd(cyl)) %>% 
  mutate(disp_sd = disp/sd(disp)) %>% 
  mutate(hp_sd = hp/sd(hp)) %>% 
  lm(mpg_sd ~ cyl_sd + disp_sd + hp_sd, data = .) ->
m1 

confint(m1) %>% 
  as_tibble()  ->
confint_m1
  
m1 %>% 
  broom::tidy(conf.int = T) %>% 
  slice(-1) %>% 
  mutate(term = fct_reorder(term, estimate) %>% 
           fct_rev()) %>% 
  ggplot() + 
  aes(y = term, x = estimate) + 
  geom_point() + 
  geom_segment(aes(x = conf.low, xend = conf.high, yend = term)) +
  geom_vline(xintercept = 0, linetype = "dashed")
```

