---
title: "another experiment"
author: "Evangeline Reynolds"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warning = F)
options(tidyverse.quiet = TRUE)
```




## Intro Thoughts


## Status Quo

```{r}
library(tidyverse)

```

## Experiment

```{r}
library(tidyverse)
data_filter <- function(.keep, .by) {
  structure(list(keep_specification = rlang::enquo(.keep), 
                 by_specification = rlang::enquo(.by)), 
            class = "filterobs")
}

ggplot_add.filterobs <- function(object, plot, object_name) {
  
  new_data <- dplyr::filter(plot$data, 
                            !!object$keep_specification, 
                            .by = !!object$by_specification)
  plot$data <- new_data
  plot

}

ggplot(mtcars) + 
  aes(factor(cyl), fill = factor(cyl)) + 
  geom_bar() -> p1

ggplot(mtcars) + 
  aes(id = cyl, fill = factor(cyl)) + 
  ggcirclepack::geom_circlepack() + 
  coord_equal() -> p2

ggplot(mtcars) + 
  aes(wt, mpg, color = factor(cyl)) + 
  geom_point(size = 4) -> p3
  
library(patchwork)
p1 + p2 + p3

(p1 + p2 + p3) * data_filter(cyl != 4)


(p1 + p2 + p3) * aes(alpha = cyl != 4)

```



## Closing remarks, Other Relevant Work, Caveats
