---
title: "another experiment"
author: "Evangeline Reynolds"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(tidyverse.quiet = TRUE)
```




## Intro Thoughts


## Status Quo

```{r cars}
library(tidyverse)

shiny_revdeps <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2024/2024-04-16/shiny_revdeps.csv')
package_details <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2024/2024-04-16/package_details.csv')

library(ggraph)
# package_details %>% 
#   # head() %>% 
#   select(Package, Author)  %>% 
#   mutate(Author = str_split(Author, ",\n ")) %>% 
#   unnest(Author) %>% 
#   mutate(Author = str_remove_all(Author, "\\[.+")) %>%
#   mutate(Author = str_remove_all(Author, "\\<.+")) %>% 
#   mutate(Author = str_trim(Author)) %>% 
#   group_by(Author) %>% 
#   filter(n() > 30) %>% 
#   head(300) %>% 
#   ggedgelist:::ggedgelist_quick(layout = "fr", include_names = T)   


package_details %>% 
  # head() %>% 
  select(Package, Author)  %>% 
  mutate(Author = str_split(Author, ",\n ")) %>% 
  unnest(Author) %>% 
  mutate(Author = str_remove_all(Author, "\\[.+")) %>%
  mutate(Author = str_remove_all(Author, "\\<.+")) %>% 
  mutate(Author = str_trim(Author)) %>% 
  distinct(Author) %>% 
  mutate(first_name = str_extract(Author, "\\w+")) ->
author_df  
  
# author_df %>% 
#   pull(first_name) %>%
#   gender::gender() %>% 
#   distinct() %>% arrange(proportion_male)
#   rename(first_name = name) %>% 
#   left_join(author_df) %>% 
#   ggplot() + 
#   aes(x = proportion_male) + 
#   geom_histogram()
```


```{r}
package_details %>% 
  select(Author, Maintainer) %>% 
  mutate(first_name = str_extract(Maintainer, "\\w+")) %>% 
  pull(first_name) %>% 
  gender::gender() %>% 
  ggplot() + 
  aes(proportion_male) + 
  geom_histogram() +
  aes(fill = proportion_male)

geom_histogram
GeomBar$default_aes
# what vars are created
ggtrace::layer_after_stat() 

last_plot() +
  aes(fill = after_stat(x)) + 
  labs(fill = "Proportion") +
  scale_fill_gradientn(colors = c("blue", "grey", "orange")) + 
  ma206distributions:::geom_fulcrum() + 
  labs(title = "A look at the Shiny-dependant packages' maintainers",
       subtitle = "For the 18,474 are package maintainers first names usually given to male or female children...")
  
```

## Experiment

```{r}

```



## Closing remarks, Other Relevant Work, Caveats
