---
title: "another experiment"
author: "Evangeline Reynolds"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(tidyverse.quiet = TRUE)

# remotes::install_github("yaweige/ggpcp")
library(ggpcp)
library(tidyverse)
data(flea, package = "GGally")


flea %>% 
  mutate(species = factor(species, levels = c("Heptapot.",  "Concinna", "Heikert."))) %>%
  ggplot(aes(vars = vars(1:7))) +
  geom_pcp_box(boxwidth = 0.1, fill="grey70") +
  geom_pcp(aes(colour=species), boxwidth = 0.1) +
  geom_pcp_text(boxwidth = 0.1)


library(ggplot2)
library(dplyr)
data(mtcars)
mtcars %>%
mutate(cyl = factor(cyl),
      vs = factor(vs),
      am = factor(am),
      gear = factor(gear)) %>%
 ggplot(aes(vars = vars(cyl, vs:gear))) +
 geom_pcp(aes(color = vs), boxwidth = 0.2, resort = 2:3) +
 geom_pcp_box(boxwidth = 0.2) +
 geom_pcp_band(boxwidth = 0.2, resort = 2:3) +
 geom_pcp_text(boxwidth = 0.2)

```




## Intro Thoughts


## Status Quo

```{r}
library(tidyverse)

```

## Experiment

```{r}
compute_hibye <- function(data,scales){
  
  data.frame(x = "hi",
             y = "bye")
  
}

library(ggplot2)
library(statexpress)

ggplot(cars) + 
  qlayer(stat = qstat(compute_hibye))

```



## Closing remarks, Other Relevant Work, Caveats
