---
title: "another experiment"
author: "Evangeline Reynolds"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(tidyverse.quiet = TRUE)
```


## Intro Thoughts

## Status Quo



```{r}
library(tidyverse)

# Step 1
compute_panel_circlepack <- function(data, scales){

  data_w_id <- data |>
    mutate(id = row_number())

  if(is.null(data$area)){

    data_w_id <- data_w_id |>
      mutate(area = 1)

  }

  data_w_id |>
    pull(area) |>
    packcircles::circleProgressiveLayout(
      sizetype = 'area') |>
    packcircles::circleLayoutVertices(npoints = 50) |>
    left_join(data_w_id) |>
    mutate(group = id)

}

data.frame(id = 1) |>
  compute_panel_circlepack()


compute_panel_circlepack_centers <- function(data, scales){

  data_w_id <- data |>
    mutate(id = row_number())

  if(is.null(data$area)){

    data_w_id <- data_w_id |>
      mutate(area = 1)

  }

  data_w_id |>
    pull(area) |>
    packcircles::circleProgressiveLayout(
      sizetype = 'area') |>
    mutate(id = row_number()) |>
    left_join(data_w_id) |>
    mutate(group = id)

}

data.frame(id = 1) |>
  compute_panel_circlepack_centers()


StatCirclepack <- ggplot2::ggproto(`_class` = "StatCirclepack",
                                  `_inherit` = ggplot2::Stat,
                                  required_aes = c("id"),
                                  compute_panel = compute_panel_circlepack#,
                                  )


StatCirclepackcenter <- ggplot2::ggproto(`_class` = "StatCirclepackcenter",
                                  `_inherit` = ggplot2::Stat,
                                  required_aes = c("id"),
                                  compute_panel = compute_panel_circlepack_centers#,
                                  )

geom_circlepack <- function(mapping = NULL, data = NULL,
                           position = "identity", na.rm = FALSE,
                           show.legend = NA,
                           inherit.aes = TRUE, ...) {
  ggplot2::layer(
    stat = StatCirclepack, # proto object from Step 2
    geom = ggplot2::GeomPolygon, # inherit other behavior
    data = data,
    mapping = mapping,
    position = position,
    show.legend = show.legend,
    inherit.aes = inherit.aes,
    params = list(na.rm = na.rm, ...)
  )
}


geom_circlepack_text <- function(mapping = NULL, data = NULL,
                           position = "identity", na.rm = FALSE,
                           show.legend = NA,
                           inherit.aes = TRUE, ...) {
  ggplot2::layer(
    stat = StatCirclepackcenter, # proto object from Step 2
    geom = ggplot2::GeomText, # inherit other behavior
    data = data,
    mapping = mapping,
    position = position,
    show.legend = show.legend,
    inherit.aes = inherit.aes,
    params = list(na.rm = na.rm, ...)
  )
}


```



```{r cars, fig.height=12, fig.width=12}
read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2024/2024-02-20/isc_grants.csv") |>
  group_by(proposed_by) |>
  summarize(funded = sum(funded),
            title = paste(title, collapse = ";")
            ) |>
  ggplot() + 
  aes(area = sqrt(funded), id = proposed_by, fill = funded) + 
  geom_circlepack() + 
  geom_circlepack_text(aes(label =
                             str_wrap(paste(proposed_by,
                                            funded, sep = "\n"), 10),
                           size = funded),
                       line_height = .8,
                       check_overlap= T,
                       color = "oldlace"
                      ) +
  coord_equal() + 
  aes(text = title) 
```

```{r, fig.show='hold', out.width="49%", warning=F, message=F}  

palette <- monochromeR::generate_palette("goldenrod4", 
                              modification = "go_lighter",
                              n_colors = 6)

theme_mono <- function(color = "goldenrod4"){
  
  palette <- monochromeR::generate_palette("goldenrod4", 
                              modification = "go_lighter",
                              n_colors = 6)
  
  theme_gray() %+replace%
  theme(panel.background = element_rect(fill = palette[4], color = palette[3]),
        panel.grid = element_line(color = palette[6]),
        plot.background = element_rect(fill = palette[5], color = palette[4]),
        text = element_text(color = palette[1]),
        axis.text = element_text(color = palette[1]),
        axis.ticks = element_line(palette[1]),
        strip.background = element_rect(fill = palette[3], color = palette[2]), 
        strip.text = element_text(color = palette[1]), complete = T)

}

read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2024/2024-02-20/isc_grants.csv") |>
  ggplot() + 
  aes(funded) +
  geom_histogram(alpha = 2, fill = palette[6]) + 
  ggxmean::geom_x_mean(color = palette[1]) + 
  ggxmean::geom_x_mean_label(color = palette[1],
                             fill = palette[6]) + 
  theme_mono()

last_plot() + 
  facet_wrap(~year)

read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2024/2024-02-20/isc_grants.csv") %>% .$funded %>%  mean
```





## Closing remarks, Other Relevant Work, Caveats
