---
title: "another experiment"
author: "Evangeline Reynolds"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(tidyverse.quiet = TRUE)
```




## Intro Thoughts


## Status Quo

```{r}
height_pattern <- c(-1,1, -.5, .5)
hjust_pattern <- c(0,0, 1,1) 

library(tidyverse)
data.frame(x = runif(10)) %>% 
  mutate(event_descr = paste("event", LETTERS[1:10])) ->
timeline_df

timeline_df %>% 
  arrange(x) %>% 
  mutate(xend = x) %>% 
  mutate(yend = 0) %>% 
  mutate(y = rep(height_pattern, nrow(.))[1:nrow(.)]) %>% 
  mutate(hjust = rep(hjust_pattern, nrow(.))[1:nrow(.)]) %>% 
  ggplot() +
  aes(x = x , y = y, xend = xend, yend = yend, label = event_descr ,
      hjust = hjust) + 
  geom_point() +
  geom_point(aes(y = 0)) + 
  geom_segment() + 
  geom_hline(yintercept = 0) + 
  geom_label()
   

compute_timeline <- function(data, scales, height_pattern = c(-1,1, -.5, .5), hjust_pattern = c(0,0, 1,1) ){

  data |> 
  arrange(x) %>% 
  mutate(xend = x) %>% 
  mutate(yend = 0) %>% 
  mutate(y = rep(height_pattern, nrow(.))[1:nrow(.)]) %>% 
  mutate(hjust = rep(hjust_pattern, nrow(.))[1:nrow(.)])
  
}


timeline_df |>
  compute_timeline()

StatTimeline <- ggproto("StatTimeline", Stat, compute_panel = compute_timeline)

timeline_df |>
  ggplot() + 
  aes(x = x, label = event_descr) + 
  geom_hline(yintercept = 0) +
  layer(GeomSegment, StatTimeline, position = "identity") +
  layer(GeomPoint, StatTimeline, position = "identity") + 
  layer(GeomLabel, StatTimeline, position = "identity") + 
  layer(GeomPoint, StatTimeline, position = "identity",
        params = list(y = 0))


geom_timeline_basic <- function(){
  
  list(
    
  geom_hline(yintercept = 0),   
  layer(GeomSegment, StatTimeline, position = "identity"),
  layer(GeomPoint,   StatTimeline, position = "identity"),
  layer(GeomLabel,   StatTimeline, position = "identity"),
  layer(GeomPoint,   StatTimeline, position = "identity", 
        params = list(y = 0))
  )
  
}





timeline_df |>
  ggplot() + 
  aes(x = x, label = event_descr) + 
  geom_timeline_basic()


data.frame(time = hms::as_hms(c("08:30:00", 
                                "09:20:00",
                                "10:00:00")),
           event = c("Arrival",
                     "Drive to Bus Station",
                     "Bus Arrives")) %>% 
  ggplot() + 
  aes(x = time, 
      label = paste(time, event, sep = "\n")) + 
  geom_timeline_basic() + 
  labs(title = "Thurs 27")

```

## Experiment

```{r}
library(tidyverse)
tribble(~ time, ~event,
        "2024-07-05 17:30:00 MDT", "Swim",
        "2024-07-06 09:30:00 MDT", "Story Time",
        "2024-07-06 10:00:00 MDT", "Bus Arrives") %>% 
  mutate(time = as.Date.POSIXlt(time)) %>% 
  ggplot() + 
  aes(x = time, 
      label = paste(time, event, sep = "\n")) + 
  geom_timeline_basic() + 
  labs(title = "Thurs 27")
```



## Closing remarks, Other Relevant Work, Caveats
