---
title: "another experiment"
author: "Evangeline Reynolds"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(tidyverse.quiet = TRUE)
```




## Intro Thoughts


## Status Quo

```{r cars}
library(tidyverse)

compute_group_calendar <- function(data, scales){

  data %>%
    dplyr::mutate(num_day_of_week = lubridate::wday(.data$date)) %>%
    dplyr::mutate(day_of_week = lubridate::wday(.data$date, label = TRUE, abbr = TRUE)) %>%
    dplyr::mutate(week_of_month = (- lubridate::wday(.data$date) + lubridate::day(.data$date)) %/% 7 + 1 +
                    ifelse(lubridate::wday(lubridate::floor_date(lubridate::as_date(.data$date), "month")) == 1, -1, 0)
                  ) %>%
    dplyr::mutate(date_of_month = lubridate::day(.data$date)) %>%
    dplyr::mutate(which_year = lubridate::year(.data$date) - 2018) %>%
    dplyr::mutate(month = lubridate::month(.data$date, abbr = TRUE, label = TRUE)) %>%
    dplyr::mutate(hour = lubridate::hour(.data$date)) %>%
    dplyr::mutate(academic_year =  lubridate::year(.data$date) +
                    ifelse(lubridate::month(date) >
                             6, 1, 0)) %>%
    dplyr::mutate(academic_month = .data$month %>%
                    factor(levels = c("Jul", "Aug", "Sep", "Oct", "Nov", "Dec",
                                      "Jan", "Feb", "Mar", "Apr", "May", "Jun")))

}


ggcalendar::return_dates_year(1999) %>%
  head() %>%
  compute_group_calendar() 

StatCalendar <- ggplot2::ggproto(`_class` = "StatCalendar",
                                 `_inherit` = ggplot2::Stat,
                                 required_aes = c("date"),
                                 compute_group = compute_group_calendar,
                                 default_aes = ggplot2::aes(x = ggplot2::after_stat(day_of_week %>% as.numeric()),
                                                            y = ggplot2::after_stat(week_of_month),
                                                            label = ggplot2::after_stat(date_of_month)))
```

## Experiment

```{r}
x0 = 0
y0 = 0

library(ggstamp)

hspace <- 2
vspace <- 3

ggcalendar::return_dates_year(1999) %>%
  # head() %>%
  compute_group_calendar() %>% 
  mutate(x = day_of_week %>% as.numeric() + (as.numeric(month)-1)%%3*(7+hspace)) %>% 
  mutate(y = week_of_month + (as.numeric(month)-1)%/%3*(5+vspace)) %>% 
  ggplot() + 
  aes(x = x, y = y) + 
  geom_point() +
  scale_y_reverse() +
  geom_label(aes(label = month(date)))
  


ggplot2::CoordCartesian$render_bg

# ggplot2::CoordSf$

```



## Closing remarks, Other Relevant Work, Caveats
