---
title: "Spring 2026 Slides"
author: "Evangeline 'Gina' Reynolds"
output:
  xaringan::moon_reader:
    seal: FALSE
    lib_dir: libs
    css: [default, hygge, ninjutsu]
    nature:
      ratio: 16:9
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---


```{r setup, include = F}
# This is the recommended set up for flipbooks
# you might think about setting cache to TRUE as you gain practice --- building flipbooks from scratch can be time consuming
knitr::opts_chunk$set(fig.width = 6, message = FALSE, warning = FALSE, comment = "", cache = T)
library(flipbookr)
library(tidyverse)
options(tidyverse.quiet = TRUE)
```


class: inverse, bottom
background-image: url(https://images.unsplash.com/photo-1559827260-dc66d52bef19?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80)
background-size: cover

# .Large[Data Science for IR: Introductions]
## .small[Korbel School of International Studies]
## .small[bit.ly/spring-2026-du]
#### .tiny[Dr. Evangeline Reynolds | `r Sys.Date()` | DU, Image credit: Silas Baisch, Upsplash]


???

Title slide
```{r, include = F}
# This is the recommended set up for flipbooks
# you might think about setting cache to TRUE as you gain practice --- building flipbooks from scratch can be time consuming
knitr::opts_chunk$set(fig.width = 6, fig.height = 4.5, message = FALSE, warning = FALSE, comment = "", cache = T)
library(flipbookr)

```



# Hi!


```{r}
us_states_ref <- usmapdata::us_map() |>
  rename(geometry = geom,
         state_name = full,
         state_abbr = abbr) |>
  select(state_name, everything())
  
library(ggregions)
geom_us_state <- write_geom_region_locale(us_states_ref)
stamp_us_state <- write_stamp_region_locale(us_states_ref)
geom_us_state_text <- write_geom_region_text_locale(us_states_ref)
stamp_us_states_text <- write_stamp_region_text_locale(us_states_ref)
```

---

`r chunk_reveal("us")`

```{r us, include = F}

tribble(~state, ~span, 
        "Illinois", .6,
        "Virginia", .1 ,
        "Colorado", .4,
        "New York", .15) |>
  ggplot() + 
  aes(state_name = state,
      fill = span) + 
  stamp_us_state() + 
  geom_us_state() + 
  scale_fill_viridis_c() + 
  scale_fill_viridis_c(end = .8,
                       begin = .3)
```




<!-- adjust font size in this css code chunk, currently 80 -->

```{css, eval = TRUE, echo = FALSE}
.remark-code{line-height: 1.5; font-size: 80%}

@media print {
  .has-continuation {
    display: block;
  }
}

code.r.hljs.remark-code{
  position: relative;
  overflow-x: hidden;
}


code.r.hljs.remark-code:hover{
  overflow-x:visible;
  width: 500px;
  border-style: solid;
}
```


