---
title: "another experiment"
author: "Evangeline Reynolds"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(tidyverse.quiet = TRUE)
```




## Intro Thoughts


## Status Quo

```{r}
library(tidyverse)

```

## Experiment

```{r}
library(tidyverse)
tibble(x = runif(50),
       y = runif(50)) |>
  ggplot() +
  aes(x = x, y = y) +
  ggforce::geom_voronoi_tile() +
  geom_point()

layer_data(i = 1) |> head()
```


# five-ish from TVDB

```{r}
library(igraph)

# Init data
df <- tibble(x = runif(50), y = runif(50))

# Make a graph of delaunay triangulation of the points
delaunay <- deldir::deldir(df$x, df$y)$delsgs
delaunay <- cbind(delaunay$ind1, delaunay$ind2)
g <- igraph::graph_from_edgelist(delaunay, directed = FALSE)

# For every vertex, search an unused colour
for (v in seq_along(V(g))) {
  v <- V(g)[v] # Index to current vertex
  nn <- ego(g, nodes = v)[[1]] # Current vertex to neighbours
  
  # Determine which colours are already in use
  nn_colours <- vertex_attr(g, "colour", index = nn) %||% 0
  nn_colours <- unique(nn_colours[!is.na(nn_colours)])
  if (length(nn_colours) == 0) {
    nn_colours <- 0
  }
  mx <- max(nn_colours)
  
  if (mx == 0) { # When no colours have been assigned to neighbours
    i <- 1L
  } else {
    # Try to find lowest colour that isn't in use by neighbours
    i <- setdiff(seq_len(mx), nn_colours)
    if (length(i) > 0) {
      i <- i[1]
    } else {
      i <- mx + 1 # If not found, increase local maximum
    }
  }
  g <- set_vertex_attr(g, "colour", index = v, value = i)
}

df$colour <- vertex_attr(g, "colour")

ggplot(df) +
  aes(x = x, y = y) +
  ggforce::geom_voronoi_tile(aes(fill = factor(colour), group = 1)) +
  geom_point()


ggplot(df) +
  aes(x = x, y = y, color = factor(colour)) +
  geom_point() + 
  scale_color_viridis_d()
```



## Closing remarks, Other Relevant Work, Caveats
