---
title: "Untitled"
author: "Evangeline Reynolds"
date: "3/15/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Everyday ggplot2 extension: ggplot2 extension myths that might be holding you back, building support for,  

## protect the code base

Motivation:  Fly through a plot with the greatest of ease...

Hadley Wickham  quote:  "This is what I'm picturing ... your the computer, now go and do it!"

# Why isn't there a ggplot2 function that does this for me?




Myths:

- ## I'm only capable of theme extensions
- ## theme extensions are the best starting point for ggplot2 extension journey

## 

- ## I need to have experience with object oriented programming

## ggplot2 extension requires r-package building know-how

- warnings, error messages, testing
- architecture
- cran

## ggplot2 extension, short term promise?

## ggplot2 extensions should be glamorous! 

- ggbump
- ggridges



## extenders community will judge my mistakes/naivete

- h4x
- ggproto
- 'crushing impostor syndrome'
- toddler's welcome

(accidental extension...)

## 



## free play (the experimental badge)



## fly through the air with the greatest of ease...

## expertise comes with practice.

## Super-producers in ggplot2 extension... Explosions of extension functions

- Claus
- Thomas
- 

## I 

## recipe books for getting in and out.  Guided practice. Gives you know-how knowledge.  

## I am a toddler and I have a toddler... 

Help!!  
