---
title: "A minimal flipbook"
subtitle: "With flipbookr and xaringan"
author: "You!"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: [default, hygge, ninjutsu]
    nature:
      ratio: 16:9
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---


```{r, include = F}
# This is the recommended set up for flipbooks
# you might think about setting cache to TRUE as you gain practice --- building flipbooks from scratch can be time consuming
knitr::opts_chunk$set(fig.width = 6, message = FALSE, warning = FALSE, comment = "", cache = F)
library(flipbookr)
library(tidyverse)
```



```{r}
palmerpenguins::penguins %>% 
  ggplot() + 
  aes(x = species) + 
  aes(fill = species) +
  geom_bar() ->
my_plot
```

---

`r flipbookr::chunk_reveal("hi", break_type = "replace", replace = "compute_statistic", replacements  = c("compute_statistic","compute_aesthetics","compute_position", "compute_geom_1", "compute_geom_2"))`

```{r hi, include = F}
ggtrace::ggtrace_inspect_args(
  x = my_plot,
  method = ggplot2:::Layer$compute_statistic
)$data
```

<!-- adjust font size in this css code chunk, currently 80 -->

```{css, eval = TRUE, echo = FALSE}
.remark-code{line-height: 1.5; font-size: 60%}

@media print {
  .has-continuation {
    display: block;
  }
}

code.r.hljs.remark-code{
  position: relative;
  overflow-x: hidden;
}


code.r.hljs.remark-code:hover{
  overflow-x:visible;
  width: 500px;
  border-style: solid;
}
```
