---
title: "another experiment"
author: "Evangeline Reynolds"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(tidyverse.quiet = TRUE)
```




## Intro Thoughts


## Status Quo

```{r}
library(tidyverse)
options(scipen = 10)

gapminder::gapminder |>
  filter(year == 2002) |>
  ggplot() + 
  aes(x = gdpPercap, 
      y = lifeExp) + 
  geom_point() + 
  scale_x_log10(labels = function(x) {paste0("$", x) |> str_replace("000$", "K")}) + 
  scale_y_continuous(labels = function(x) {paste0(x, rep("y", length(x) - 1) |> c(" year life \nexpectancy"))}) + 
  aes(size = pop/1000000) + labs(size = "Population \n(millions)") + 
  aes(color = continent) + labs(color = NULL)

gapminder::gapminder |>
  ggplot() + 
  aes(x = year, 
      y = lifeExp,
      group = country) + 
  geom_line() + 
  scale_x_continuous(labels = function(x) {str_replace(x, "\\d{2}", "'")}) +
  scale_y_continuous(labels = 
                       function(x) {paste0(x, rep("y", length(x) - 1) |> c("-year life \nexpectancy"))}) 
```

## Experiment

```{r}
library(tidyverse)

label_max_diamonds <- function(x){
        ifelse(x == max(x, na.rm = T), paste0(x, '\ndiamonds'), 
          x)}

mtcars |>
  ggplot() +
  aes(x = factor(am)) +
  geom_bar()  + 
  scale_y_continuous(labels = label_max_diamonds)
```



## Closing remarks, Other Relevant Work, Caveats
