---
title: "another experiment"
author: "Evangeline Reynolds"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(tidyverse.quiet = TRUE)
```




## Intro Thoughts

Gonna use this old project, https://evamaerey.github.io/flipbooks/federalist/federalist#1, and explore dimred!


## Status Quo

```{r}
library(tidyverse)

load("../../../../Desktop/federalist.rda")

federalist %>%
  mutate(author = replace_na(author, 
                             "Disputed")) %>% 
  mutate(name = paste(author, 
                      str_remove(name, "eralist"), 
                      sep = "-")) -> 
federalist


federalist %>% 
  quanteda::corpus(text_field = "text", docid_field = "name") |>
  quanteda::tokens(remove_numbers = TRUE, remove_punct = TRUE) |>
  quanteda::dfm() |>
  quanteda::convert(to = "data.frame") |>
  select(-"in", -"for", -"or") ->
federalist_word_count

names(federalist_word_count) |> tail()

library(ggdims)
federalist_word_count |> 
  ggplot() + 
  aes(dims = dims(the:an)) + 
  geom_pca() 

last_plot() + 
  aes(fill = str_extract(doc_id, ".+-"))



library(ggdims)
federalist_word_count |> 
  ggplot() + 
  aes(dims = dims(the:an)) + 
  geom_tsne(perplexity = 25) 

last_plot() + 
  aes(fill = str_extract(doc_id, ".+-"))


library(ggdims)
federalist_word_count |> 
  ggplot() + 
  aes(dims = dims(the:an)) + 
  geom_umap()

last_plot() + 
  aes(fill = str_extract(doc_id, ".+-"))

```

## Experiment

```{r}

```



## Closing remarks, Other Relevant Work, Caveats
