---
title: "Exploded code"
subtitle: "Using flipbookr and xaringan"
author: "Me"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: [default, hygge, ninjutsu]
    nature:
      ratio: 16:9
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---


```{r, include = F}
# This is the recommended set up for flipbooks
# you might think about setting cache to TRUE as you gain practice --- building flipbooks from scratch can be time consuming
knitr::opts_chunk$set(fig.width = 6, fig.height = 4, message = F, warning = FALSE, comment = "", cache = F)

options(tibble.print_min = 55)
options(knitr.duplicate.label = "allow")
options(width=300) # prevents data wrapping
```


```{css, eval = TRUE, echo = FALSE}
.remark-code{line-height: 1.5; font-size: 70%}

@media print {
  .has-continuation {
    display: block;
  }
}

code.r.hljs.remark-code{
  position: relative;
  overflow-x: hidden;
}


code.r.hljs.remark-code:hover{
  overflow-x:visible;
  width: 500px;
  border-style: solid;
}
```


---


`r flipbookr::chunk_reveal("setup", left_assign = "detect")`


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F)
```


---


`r flipbookr::chunk_reveal("e1", left_assign = "detect")`


```{r e1, include = FALSE}
library(tidyverse)
library(ggseg)

ggseg(
  view = "medial",
  ) + 
  theme_darkbrain() + 
  labs(title = "dk",
       subtitle = "medial view")
```



---


`r flipbookr::chunk_reveal("ex2", left_assign = "detect")`


```{r ex2, include = FALSE}
tibble(region = rep(c("transverse temporal",
               "insula",
               "precentral",
               "superior parietal"), 2),
       p = sample(seq(0, .5, .001), 8),
       g = c("A", "B", "C", "D", "B", "A", "C","A"),
       AgeG = c(rep("Young", 4),
                rep("Old", 4 ))
) %>%
  ggseg(.data = .,
        atlas = dk,
        position = "stacked", 
        show.legend = FALSE) +
  aes(fill = p) +
  scale_fill_viridis_c() +
  aes(color = g) +
  scale_colour_viridis_d(option = "magma") + 
  aes(fill = NULL) + 
  facet_wrap(~AgeG, ncol = 3) +
  labs(title = "Ungrouped data") 

layer_data(plot = last_plot()) ->
  hide
  
ggseg ->
  hide

dk ->
  hide

```


---


`r flipbookr::chunk_reveal("ex3", left_assign = "detect")`


```{r ex3, include = FALSE}
ggseg (atlas = aseg) + 
  aes(fill = region) +
  theme(legend.justification = c(1, 0)) +
  theme(legend.position = "bottom") +
  theme(legend.text = element_text(size = 5)) +
  guides(fill = guide_legend(ncol = 3)) 

layer_data(plot = last_plot()) ->
  hide

aseg
```

