---
title: "another experiment"
author: "Evangeline Reynolds"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(tidyverse.quiet = TRUE)
```




## Intro Thoughts


## Status Quo

```{r}
library(tidyverse)
tinypivot <- function(data = data.frame(), rows = NULL, cols = NULL){

  # create s3
  tp <- list(data = data,
                rows = rlang::enquo(rows),
                cols = {{cols}})
  
# declare to be new class
class(tp) <- "tp"

# define print method
print.tp <- function(data, rows, cols){
  
    data %>% 
      group_by(all_of(c({{rows}}, {{cols}}))) %>% 
      count() ->
    out
      
    if(!is.null(cols)){
      out %>% 
        pivot_wider(id_cols = {{rows}}, 
                    names_from == {{cols}},
                    values_from = n) ->
      out
    }
  
  print(out)
  
}

tp

invisible(tp)

}

tinypivot()

tinypivot() |>
  str()
```


## Experiment

```{r}

```



## Closing remarks, Other Relevant Work, Caveats
