---
title: "brain2 with sf manipulation"
author: "Evangeline Reynolds"
date: "3/9/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Example simple feature to data frame...

```{r}
library(tidyverse)
library(sf)
#> Linking to GEOS 3.8.1, GDAL 3.2.1, PROJ 7.2.1

fips_geometries <- readRDS(url("https://wilkelab.org/SDS375/datasets/US_counties.rds")) %>%
  rename(FIPS = GEOID)

US_census <- read_csv("https://wilkelab.org/SDS375/datasets/US_census.csv",
                      col_types = cols(FIPS = "c")
          )

# works
fips_geometries %>%
  left_join(US_census, by = "FIPS") %>%
  ggplot() +
  geom_sf(aes(fill = home_ownership)) + 
  scale_fill_viridis_c()

# from Claus Wilke on ggplot2
```




```{r}
#' Title
#'
#' @param geometries_frame 
#'
#' @return
#' @export
#'
#' @examples
#' geometries_frame_to_id_group(fips_geometries)
geometries_frame_to_id_group <- function(geometries_frame){

    nsubgroup <- geometries_frame$geometry %>% purrr::map_dbl(.f = length)

    tibble(nsubgroup) %>% 
      mutate(major_group = 1:n()) %>% # row number 
      uncount(weights = nsubgroup) %>% 
      group_by(major_group) %>% 
      mutate(subgroup = 1:n()) %>% 
      mutate(major_and_minor = paste0(major_group,'.', subgroup)) %>% 
      ungroup() %>% 
      mutate(polygon = 1:n()) %>% 
      ungroup()

}



#' Title
#'
#' @param geometries_frame 
#'
#' @return
#' @export
#'
#' @examples
#' geometries_frame_to_df(nc) 
geometries_frame_to_df <- function(geometries_frame = ){

      polygons_flat <- data.frame()
    
      polygons <- geometries_frame$geometry %>% purrr::flatten() %>% purrr::flatten()
      
    for (i in 1:length(polygons)){
      
      temp <- polygons[[i]] %>% 
        data.frame() %>% 
        mutate(polygon = i)
      
      polygons_flat = bind_rows(polygons_flat, temp)
  

    }
      

  names(polygons_flat)[1] <- "x"
  names(polygons_flat)[2] <- "y"

  polygons_flat
  
}
  

geometries_frame_to_df <- function(geometries_frame){

      polygons_flat <- data.frame()
    
      geometries_list <- geometries_frame$geometry
      
    for (i in 1:length(geometries_list)){
      
      polygons_list <- geometries_list[[i]][[1]]
      fips <- geometries_frame$FIPS[i]
      
      for (j in 1:length(polygons_list)){
      temp <- polygons_list[[j]] %>% 
        data.frame() %>% 
        mutate(major_group = i) %>% 
        mutate(subgroup = j) %>% 
        mutate(fips = fips)
      
      polygons_flat = bind_rows(polygons_flat, temp)
  
      }
      
    }

  names(polygons_flat)[1] <- "x"
  names(polygons_flat)[2] <- "y"

  polygons_flat %>% 
    mutate(polygon = paste0(major_group, ".", subgroup))
  
}


fips_geometries %>% geometries_frame_to_df() -> reference


```  



```{r}
#' Title
#'
#' @param geometries_frame 
#'
#' @return
#' @export
#'
#' @examples
#' geometries_frame_to_id_group(fips_geometries) %>% 
#' count(major_group)
geometries_frame_to_ggplot_reference <- function(geometries_frame = aseg_geometries_frame){
  
  keep_frame <- geometries_frame
  
  keep_frame$geometry = NULL
  
  keep_frame %>% 
    data.frame() %>% 
    janitor::clean_names() %>% 
    # mutate(major_group = row_number()) %>% 
    left_join(geometries_frame_to_df(geometries_frame))
  
}
  


  
fips_ggplot2_reference <- fips_geometries %>% select(FIPS, geometry) %>% 
  geometries_frame_to_ggplot_reference()  

# 3142 fips_geometries %>% count(FIPS)
# geometries_frame_to_id_group(geometries_frame = fips_geometries) %>% count(major_group)
# 3225 geometries_frame_to_id_group(geometries_frame = fips_geometries) %>% count(polygon) 
# 3239 geometries_frame_to_df(geometries_frame = fips_geometries)  %>% count(polygon)
geometries_frame_to_df(geometries_frame = fips_geometries)  %>% count(major_group)

fips_ggplot2_reference %>% count(polygon)
fips_ggplot2_reference %>% count(fips)


compute_county <- function(data, scales){
 
  data %>% 
    # inner_join(fips_ggplot2_reference, multiple = "all") 
    inner_join(reference)

}


```


# Step 2: pass to ggproto

```{r}
StatCounty <- ggplot2::ggproto(`_class` = "StatCounty",
                                  `_inherit` = ggplot2::Stat,
                                  # required_aes = c("fips"),
                                  # setup_data = my_setup_data,
                                  compute_panel = compute_county,
                                  default_aes = aes(group = after_stat(polygon))
                                  )
```


# Step 3: write geom_* function

```{r}
geom_polygon_county <- function(
  mapping = NULL,
  data = NULL,
  position = "identity",
  na.rm = FALSE,
  show.legend = NA,
  inherit.aes = TRUE, ...) {
  ggplot2::layer(
    stat = StatCounty,  # proto object from step 2
    geom = ggplot2::GeomPolygon,  # inherit other behavior
    data = data,
    mapping = mapping,
    position = position,
    show.legend = show.legend,
    inherit.aes = inherit.aes,
    params = list(na.rm = na.rm, ...)
  )
}
```

# step 4: test geom_* function, celebrate!

```{r, eval = T}
us_census <- read_csv("https://wilkelab.org/SDS375/datasets/US_census.csv",
                      col_types = cols(FIPS = "c")
          )  

us_census %>% 
  ggplot() + 
  aes(fips = FIPS) +
  geom_polygon_county(linewidth = .02, color = "darkgrey") +
  aes(fill = mean_work_travel) + 
  scale_fill_viridis_c(option = "magma")

layer_data(last_plot())

fips_geometries %>%
  left_join(US_census, by = "FIPS") %>%
  ggplot() +
  geom_sf(aes(fill = mean_work_travel), linewidth = .1) + 
  scale_fill_viridis_c(option = "magma")

layer_data(last_plot())

geom_sf


```
