---
title: "Untitled"
author: "Evangeline Reynolds"
date: "11/5/2021"
output: html_document
---

```{r drafting}
library(tidyverse)
library(ggstamp)
myalpha = .5
ggcanvas() + 
  stamp_text_ljust(label = "Counting Fish",
                   x = -.75,
                   y = 1.5,
                   color = "gray30") +
  stamp_text(x = 0:3*2,
                   y = .75,
                   label = paste0(c("one","two","red","blue"), 
                                 "\nfish"),
                   size = 6,
                   color = "gray30") +
  stamp_png(png = "noun_Fish_2459037.png", 
            x0y0 = pos_wrap_multi(ncol = 1, 
                               n = c(1,2,1,1)),
            width = 1.4,
            reduce = 30,
              alpha = myalpha) + 
  stamp_text(label = "It's always 'fish'",text_wrap = T,char_width = 30,
              
              
             x = 1.5,
             y = -2.75,
             size = 6,
             color = "gray39"
             ) +
  # theme_void_fill() +
  NULL ->
plot_sketch

plot_sketch
```


```{r highres}
my_pos <- pos_wrap_multi(ncol = 1, 
                               n = c(1,2,1,1))

# api a little awkward but works
myalpha = 0 
reduce(
  1:nrow(my_pos),
  ~ .x + stamp_png2(png = "noun_Fish_2459037.png", 
                    width = 1.4,
                    color = c("gray30","gray30","gray30","darkred","navy")[.y],
                    x0y0 = my_pos[.y,]),
  .init = plot_sketch
)  + 
  theme_void_fill(margin.top = 30,
                  margin.left = 40,
                  margin.right = 40) 
```

