---
title: "another experiment"
author: "Evangeline Reynolds"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(tidyverse.quiet = TRUE)
```




## Intro Thoughts


## Status Quo


```{r}
library(tidyverse)


coord_radar <- function(theta = "x", start = 0, direction = 1, ...) {
theta <- match.arg(theta, c("x", "y"))
r <- ifelse(theta == "x", "y", "x")

ggplot2::ggproto(
"CordRadar",
CoordPolar,
theta = theta,
r = r,
start = start,
direction = sign(direction),
is_linear = function(coord) {
TRUE
},
...
)
}

diamonds |> 
  count(cut) |>
  ggplot() + 
  aes(x = cut, y = n, group = -1) + 
  coord_radar() + 
  geom_polygon(color = "black", alpha = .2) + 
  geom_point()


library(statexpress)

compute_to_cartesian <- function(data, scales){
  
  data |>
    mutate(y = r)
  
}

geom_web <- function(){
  
  
  qlayer(geom = GeomPolygon,
         stat = qstat(compute_to_cartesian))
  
  
}


diamonds |> 
  count(cut) |>
  ggplot() + 
  aes(x = cut, r = n, group = -1) + 
  coord_radar() + 
  geom_web()


```





## Closing remarks, Other Relevant Work, Caveats
