---
title: "another experiment"
author: "Evangeline Reynolds"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, error = T)
options(tidyverse.quiet = TRUE)
```




## Intro Thoughts


## Status Quo

```{r cars}
library(tidyverse)
geom_point

ggplot(cars) + 
  aes(speed, dist) + 
  layer(stat = StatIdentity, 
        geom = GeomPoint, 
        position = "identity")

StatIdentity
GeomPoint

GeomPoint2 <- ggproto("GeomPoint2", GeomPoint)


GeomPoint2$required_aes
GeomPoint2$required_aes <- c("x", "y")
GeomPoint2$default_aes
GeomPoint2$default_aes <- aes(y = NULL)
GeomPoint$draw_group
GeomPoint$draw_panel
GeomPoint$draw_layer

ggplot(cars) + 
  aes(speed, dist) + 
  layer(stat = StatIdentity, 
        geom = GeomPoint2, 
        position = "identity")



```

## Experiment

```{r}
compute_group_point2 <- function(data, scales){
  
  if(is.null(data$y)){data$y <- factor("all") }
  if(is.null(data$x)){data$x <- 0}
  
  data
  
} 


ggtemp:::create_layer_temp(fun_name = "geom_point2",
                           compute_group = compute_group_point2,
                           required_aes = character(),
                           default_aes = aes(x = NULL, y = NULL),
                           geom_default = "point"
                           )


ggplot(cars) + 
  aes(speed, dist) +
  geom_point2()

```



## Closing remarks, Other Relevant Work, Caveats
