---
title: "another experiment"
author: "Evangeline Reynolds"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(tidyverse.quiet = TRUE)
```




## Intro Thoughts


## w ggraph()

```{r}
library(tidyverse)
library(tidygraph)
library(ggraph)

set.seed(9876)
as_tbl_graph(highschool) %>% 
  activate("edges") %>% 
  filter(year == 1957) %>% 
  ggraph() + 
  geom_node_point() + 
  geom_edge_link()

layer_data(i = 2) %>% tibble()
```


# preprocessing and piping into ggplot()

```{r}
set.seed(9876)
as_tbl_graph(highschool) %>%
  activate("edges") %>% 
  tidygraph::as_tibble() %>% 
  filter(year == 1957) ->
edgelist  


edgelist %>% # edgelist
  tidygraph::as_tbl_graph() %>% 
  create_layout(layout = "stress") ->
node_layout

edgelist %>% 
  left_join(node_layout %>% 
              select(from = .ggraph.orig_index, 
                     x, y)) %>% 
  left_join(node_layout %>% 
              select(to = .ggraph.orig_index,
                     xend = x,
                     yend = y)) %>% 
  ggplot() + 
  aes(x = x, y = y) + 
  geom_point() + 
  aes(xend = xend, yend = yend) +
  geom_segment()

layer_data()  %>% tibble()  
```



# trying to make some Stats... 

```{r, eval = T}
compute_panel_edgelist_nodes <- function(data = edgelist, scales, layout = "stress", seed = 12345){
  
set.seed(seed)
    
node_names <- unique(c(data$from, data$to))

data %>% # edgelist
  select(from, to, everything()) %>% 
  tidygraph::as_tbl_graph() ->
graph    
    
graph %>% 
  ggraph::create_layout(layout = layout) ->
node_layout


node_layout$name <- node_names
node_layout$is_from <- node_names %in% data$from
node_layout$is_to <- node_names %in% data$to
node_layout$is_from_and_to <- node_layout$is_from & node_layout$is_to
node_layout$node_type <- case_when(node_layout$is_from_and_to ~ "both",
                                     node_layout$is_from ~ "from",
                                     node_layout$is_to ~ "to", TRUE ~ "neither")

node_layout
  
}


StatEdgelistNodes <- ggproto("StatEdgelistNodes", 
                        Stat,
                        compute_panel = compute_panel_edgelist_nodes,
                        required_aes = c("from", "to"),
                        default_aes = aes(label = after_stat(name)))


edgelist %>% 
  ggplot() + 
  aes(from = from, to = to) + 
  geom_point(stat = StatEdgelistNodes, color = "grey") + 
  geom_text(stat = StatEdgelistNodes) + 
  aes(size = after_stat(node_type) == "both")
```


```{r}
compute_panel_edgelist_edges <- function(data = edgelist, scales, layout = "stress", seed = 12345){
  
  set.seed(seed)
  
data %>% # edgelist
  select(from, to, everything()) %>% 
  tidygraph::as_tbl_graph() %>% 
  ggraph::create_layout(layout = layout) ->
node_layout
  
data %>% 
  select(from, to, everything()) %>% 
  # group_by(PANEL, group) %>% 
  tidygraph::as_tbl_graph() %>% 
  activate("edges") %>% 
  as_tibble() %>% 
  left_join(node_layout %>% 
              select(from = .ggraph.orig_index, 
                     x, y)) %>% 
  left_join(node_layout %>% 
              select(to = .ggraph.orig_index,
                     xend = x,
                     yend = y)) %>% 
   mutate(group = 1, 
          PANEL = 1) %>% 
  mutate(node_type = "both")
  
}

edgelist %>% 
  compute_panel_edgelist_edges()

StatEdgelistEdges <- ggproto("StatEdgelistEdges", 
                        Stat,
                        compute_panel = compute_panel_edgelist_edges,
                        required_aes = c("from", "to"))

last_plot() + 
  geom_segment(stat = StatEdgelistEdges, size = .5, color = "grey") #uh oh!

layer_data(i = 2) %>% head()

```

```{r}
user_repo_fun <- read_csv("https://raw.githubusercontent.com/EvaMaeRey/mytidytuesday/refs/heads/main/2024-11-19-gg-prefixes/exported_funs_exts_ggplot2_tidyverse_org.csv")

user_repo_fun |>
  mutate(prefix_short = fun_exported %>% str_extract(".*?_")) %>% 
  mutate(prefix_long = fun_exported %>% str_extract(".+_")) ->
user_repo_fun_prefix
  
user_repo_fun_prefix |>
  filter(!is.na(prefix_short)) |> 
  filter(n() > 20, .by = prefix_short) |>
  filter(prefix_short != "easy_") |>
  ggplot() +
  aes(from = repo, to = prefix_short) + 
  geom_point(stat = StatEdgelistNodes, color = "grey") + 
  geom_segment(stat = StatEdgelistEdges, color = "grey", size = .2) +
  geom_text(stat = StatEdgelistNodes) + 
  aes(size = after_stat(node_type) == "to") + 
  theme(legend.position = "none") 

last_plot() + 
  aes(from = user)

last_plot() + 
  aes(id = fun_exported %>% str_extract(".+_"))

last_plot()



```



```{r, eval = T, include = T}
cran_20230905 <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-09-19/cran_20230905.csv')
package_authors <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-09-19/package_authors.csv')


cran_20230905 %>%
  filter(Package %>%
           str_detect("^gg|^GG")) %>%
  filter(Imports %>%
           str_detect("ggplot2")|
         Depends %>% str_detect("ggplot2")) %>%
  select(Package) %>%
  left_join(package_authors %>%
              mutate(authorsR = authorsR %>%
                       str_replace(" ", "\n"))) %>% 
  ggplot() + 
  aes(from = Package, to = authorsR) + 
  geom_point(stat = StatEdgelistNodes) + 
  geom_segment(stat = StatEdgelistEdges)


gapminder::gapminder %>% 
  ggplot() + 
  aes(from = continent, to = country) + 
  geom_point(stat = StatEdgelistNodes) + 
  geom_segment(stat = StatEdgelistEdges)

layer_data() %>% head()


gapminder::gapminder %>% 
  ggplot() + 
  aes(from = continent, to = country) + 
  geom_point(stat = StatEdgelistNodes, layout = "circlepack") + 
  geom_segment(stat = StatEdgelistEdges, layout = "circlepack")

layer_data()

graph <- tbl_graph(flare$vertices, flare$edges)
set.seed(1)
ggraph(graph, 'circlepack', weight = size) + 
  geom_node_circle(aes(fill = depth), size = 0.25, n = 50) + 
  coord_fixed()

gapminder::gapminder %>% 
  select(continent, country) %>% 
  tidygraph::as_tbl_graph() %>% 
  ggraph(layout = "circlepack") + 
  geom_node_circle()

```


```{r}


library(tidyverse)
pkgs <- as_tibble(tools::CRAN_package_db())
gg_pkgs <- pkgs %>% 
  select(Package, Depends, Imports, Suggests) %>% 
  filter(
    str_detect(Package, "^gg"),
    if_any(-Package, ~ str_detect(.x, "ggplot2"))
  ) %>% 
  mutate(
    dep_grid = str_detect(Depends, "\\bgrid\\b") | str_detect(Imports, "\\bgrid\\b"),
    dep_dplyr = str_detect(Depends, "\\bdplyr\\b") | str_detect(Imports, "\\bdplyr\\b")
  ) %>% 
  drop_na()

gg_pkgs %>%
pivot_longer(cols = dep_grid:dep_dplyr) %>%
filter(value == T) %>%
  ggplot() + 
  aes(from = Package, to = name) + 
  geom_point(stat = StatEdgelistNodes) + 
  geom_segment(stat = StatEdgelistEdges)
```



## Experiment

```{r}

```



## Closing remarks, Other Relevant Work, Caveats
