---
title: "another experiment"
author: "Evangeline Reynolds"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(tidyverse.quiet = TRUE)
```




## Intro Thoughts


## Status Quo

```{r}
library(tidyverse)

```

## Experiment

```{r, plot}
library(ggplot2)

ggplot(data = mtcars) + # this is what I'm thinking
  aes(x = wt) + # I want weight on the x axis
  aes(y = mpg) + # and I want miles per gallon on the y axis
  geom_point() + # 
  facet_wrap(vars(cyl))
```


```{r, plot2}
library(ggplot2)

ggplot(data = mtcars) + # this is what I'm thinking
  aes(x = wt) + # I want weight on the x axis
  aes(y = mpg) + # and I want miles per gallon on the y axis
  geom_point() + # and we'll mark these with points
  facet_wrap(vars(cyl)) # and group them by this other variable cyl
```






```{r}
knitrExtra::chunk_code_get("plot2") |>
  data.frame(comment = _) |>
  mutate(comment = str_extract(comment, "#.+") |> str_wrap(15)) |>
  mutate(row_number = row_number())

library(tidyverse)
knitrExtra::chunk_code_get("plot") |>
  data.frame(code = _) |>
  ggplot() + 
  aes(code = code) +
  geom_text(stat = ggram:::StatCode) + 
  scale_y_reverse() +
  geom_text()


```



## Closing remarks, Other Relevant Work, Caveats
