---
title: "another experiment"
author: "Evangeline Reynolds"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(tidyverse.quiet = TRUE)
```






## Status Quo... From https://www.youtube.com/watch?v=nTbzO-RjABo&t=4s

```{r}
library(tidyverse)
original_dat <- tribble(
  ~cat, ~group, ~strongly_oppose, ~somewhat_oppose, ~somewhat_favor, ~strongly_favor, ~neither, ~no_experience,

  'High school or less', 'education', 23, 16, 13, 9, 32, 7,
  'Some college', 'education', 21, 18, 15, 9, 35, 2,
  'Bachelor\'s degree', 'education', 20, 20, 20, 8, 31, 1,
  'Postgraduate', 'education', 23, 19, 20, 8, 30, 1,

)




## # A tibble: 14 ×
dat_longer <- original_dat |> 
  pivot_longer(
    cols = strongly_oppose:no_experience,
    values_to = 'percentage',
    names_to = 'response'
  )

dat_diverging <- dat_longer |> 
  filter(!(response %in% c('neither', 'no_experience'))) 


computed_values <- dat_diverging |> 
  mutate(
    middle_shift = sum(percentage[1:2]),
    lagged_percentage = lag(percentage, default = 0),
    left = cumsum(lagged_percentage) - middle_shift,
    right = cumsum(percentage) - middle_shift,
    middle_point = (left + right) / 2,
    width = right - left,
    .by = cat
  )

computed_values


bar_width <- 0.75
computed_values |> 
  ggplot() +
  geom_tile(
    aes(
      x = middle_point, 
      y = cat,
      width = width,
      fill = response
    ),
    height = bar_width
  )

```

## Experiment: Stat Experiment... geom_tile(StatDivergent)




```{r}
compute_panel_likert <- function(data, scales){
  
  data |> 
  mutate(
    middle_shift = sum(x[1:2]),
    lagged_percentage = lag(x, default = 0),
    left = cumsum(lagged_percentage) - middle_shift,
    right = cumsum(x) - middle_shift,
    x = (left + right) / 2,
    width = right - left,
    .by = y
  )
  
}

dat_diverging %>% 
  select(x = percentage, 
         y = cat,
         color = response) %>% 
  compute_panel_likert()


StatDivergent <- ggproto("StatDivergent", 
                         Stat,
                         compute_panel = compute_panel_likert)


dat_diverging |> 
  ggplot() +
  aes(x = percentage, 
      y = cat,
      fill = response) + 
  geom_tile(stat = StatDivergent, height = .75)


last_plot() + 
  aes(fill = NULL)


last_plot() + 
  aes(alpha = response)

last_plot() + 
  aes(color = response) + 
  aes(linewidth = I(.5))

```


# w/ ggstats::position_likert()

```{r ggstats-likert}
dat_diverging |>
  ggplot() + 
  aes(y = cat) + 
  aes(weight = percentage) + 
  aes(fill = response) +
  geom_bar() +
  labs(tag = 1)

last_plot() + 
  aes(fill = response %>% 
        fct_inorder()) + 
  labs(tag = 2)
  
ggwipe::last_plot_wipe() + 
  geom_bar(position = 
             ggstats::position_likert()) +
  labs(tag = 3)

custom_label <- function(x) {
  p <- scales::percent(x, accuracy = 1)
  p[x < .075] <- ""
  p
}

last_plot() + 
  geom_text(
    aes(by = as.factor(cat), 
        label = custom_label(after_stat(prop))),
    stat = ggstats::StatProp,
    position = ggstats::position_likert(vjust = .5)
  ) +
  scale_x_continuous(label = ggstats::label_percent_abs()) +
  labs(tag = 4)
```



```{r}
age_cats <- c("18-29", "30-49"," 50-64", "65+")
sex_cats <- c("Male", "Female")
edu_cats <- c('High school or less',  "Some college", "Bachelor's Degree",
              "Postgraduate")
income_cats <- c("Lower Income", "Middle Income", "Upper Income")
likert_cats <- c("strongly oppose", "somewhat_oppose", "neither",
                 "somewhat_favor", "strongly_favor")
likertforce_cats <- c("strongly oppose", "somewhat_oppose", 
                 "somewhat_favor", "strongly_favor")

sample40replaceT <- function(x){
  sample(x, size = 40, replace = T) %>% factor(levels = x)
}

survey <- data.frame(c1 = sample40replaceT(age_cats),
                     c2 = sample40replaceT(sex_cats),
                     c3 = sample40replaceT(edu_cats),
                     c4 = sample40replaceT(income_cats),
                     q1 = sample40replaceT(likert_cats),
                     q2 = sample40replaceT(likert_cats),
                     q3 = sample40replaceT(likert_cats),
                     q4 = sample40replaceT(likertforce_cats))

original_dat

survey %>% 
  ggplot() + 
  aes(y = c1, fill = q1) + 
  geom_bar() +
  scale_fill_brewer(palette = "PiYG")




library(ggstats)
survey %>% 
  ggplot() + 
  aes(y = c1, fill = q1) + 
  geom_bar(position = ggstats::position_likert(vjust = .5),
           stat = ggstats::StatProp,
           complete = "fill")
  

last_plot() + 
  aes(fill = q4)


custom_label <- function(x) {
  p <- scales::percent(x, accuracy = 1)
  p[x < .075] <- ""
  p
}

last_plot() +
  aes(by = c1, label = custom_label(after_stat(prop))) +
  geom_text(
    stat = ggstats::StatProp,
    position = ggstats::position_likert(vjust = .5),
    complete = "fill"
  ) +
  scale_x_continuous(label = label_percent_abs()) 


layer_data(i = 2)

```


```{r}




geom_likert <- function (mapping = NULL, data = NULL,  stat = StatProp, position = ggstats::position_likert(vjust = .5), 
    ..., just = 0.5, width = NULL, na.rm = FALSE, orientation = NA, 
    show.legend = NA, inherit.aes = TRUE) 
{
    layer(data = data, mapping = mapping, stat = stat, geom = GeomBar, 
        position = position, show.legend = show.legend, inherit.aes = inherit.aes, 
        params = rlang::list2(just = just, width = width, na.rm = na.rm, 
            orientation = orientation, complete = "fill", ...))
}


StatProp <- ggstats::StatProp
# 
# StatProp$default_aes <- aes(by = after_stat(y), 
#                             label = custom_label(after_stat(prop)))



geom_likert_text <- function (mapping = NULL, data = NULL,  
                              stat = StatProp, 
                              position = ggstats::position_likert(vjust = .5),
                            
    ..., parse = FALSE, nudge_x = 0, nudge_y = 0, check_overlap = FALSE, 
    size.unit = "mm", na.rm = FALSE, show.legend = NA, inherit.aes = TRUE) 
{
    if (!missing(nudge_x) || !missing(nudge_y)) {
        if (!missing(position)) {
            cli::cli_abort(c("Both {.arg position} and {.arg nudge_x}/{.arg nudge_y} are supplied.", 
                i = "Only use one approach to alter the position."))
        }
        position <- position_nudge(nudge_x, nudge_y)
    }
    layer(data = data, mapping = mapping, stat = stat, geom = GeomText, 
        position = position, show.legend = show.legend, inherit.aes = inherit.aes, 
        params = rlang::list2(parse = parse, check_overlap = check_overlap, 
            size.unit = size.unit, na.rm = na.rm, complete = "fill", ...))
}


survey %>% 
  ggplot() + 
  aes(y = c1, fill = q1) + 
  geom_bar() 

survey %>% 
  ggplot() + 
  aes(y = c1, fill = q1) +
  geom_likert() 


last_plot() + 
  geom_likert_text(aes(by = c1)) + 
  aes(label = custom_label(after_stat(prop)))





ggplot(data = data.frame(x = runif(100)^.5, y = 1:100) ) +
  aes(area = x, id = y) + 
  ggcirclepack::geom_circlepack() 

last_plot() %+%
  (data.frame(x = runif(100)^3 %>% sort(), y = 1:100))


```



```{r}
library(tidyverse)
age_cats <- c("18-29", "30-49"," 50-64", "65+")
sex_cats <- c("Male", "Female")

sample40replaceT <- function(x){
  sample(x, size = 40, replace = T) %>% factor(levels = x)
}

survey <- data.frame(c1 = sample40replaceT(age_cats),
                     c2 = sample40replaceT(sex_cats))

survey %>% 
  ggplot() + 
  aes(y = c1, fill = c2) + 
  geom_bar(position = ggstats::position_likert_count())


# drop shadow layer (if MF counts were equal) attempt
last_plot() + 
  aes(fill = NULL)

# drop shadow layer attempt 2
last_plot() + 
  aes(fill = "All")


```


