---
title: "geom smooth"
author: "Evangeline Reynolds"
date: "9/1/2023"
output: 
  html_document:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, error = T)
```


# Proposal: Can we allow categorical values in model?

## Target code

```{r, eval = F}
mtcars %>% 
  ggplot() + 
  aes(x = wt, y = mpg, cat = am) + 
  geom_smooth_cat()
```



```{r}
library(tidyverse)
# This function exists to silence an undeclared import warning
gam_method <- function() mgcv::gam
data_frame0 <- function(...) data_frame(..., .name_repair = "minimal")
predictdf <- function(model, xseq, catseq, se, level) UseMethod("predictdf")
```

# prediction mechanisms

```{r}
#' @export
predictdf.default <- function(model, xseq, catseq, se, level) {
  pred <- stats::predict(
    model,
    newdata = data_frame0(x = xseq, cat = catseq),
    se.fit = se,
    level = level,
    interval = if (se) "confidence" else "none"
  )

  if (se) {
    fit <- as.data.frame(pred$fit)
    names(fit) <- c("y", "ymin", "ymax")
    base::data.frame(x = xseq, cat = catseq, fit, se = pred$se.fit)
  } else {
    base::data.frame(x = xseq, cat = catseq, y = as.vector(pred))
  }
}

#' @export
predictdf.glm <- function(model, xseq, catseq, se, level) {
  pred <- stats::predict(
    model,
    newdata = data_frame0(x = xseq, cat = catseq),
    se.fit = se,
    type = "link"
  )

  if (se) {
    std <- stats::qnorm(level / 2 + 0.5)
    base::data.frame(
      x = xseq,
      cat = catseq,
      y = model$family$linkinv(as.vector(pred$fit)),
      ymin = model$family$linkinv(as.vector(pred$fit - std * pred$se.fit)),
      ymax = model$family$linkinv(as.vector(pred$fit + std * pred$se.fit)),
      se = as.vector(pred$se.fit)
    )
  } else {
    base::data.frame(x = xseq, cat = catseq, y = model$family$linkinv(as.vector(pred)))
  }
}

#' @export
predictdf.loess <- function(model, xseq, catseq, se, level) {
  pred <- stats::predict(
    model,
    newdata = data_frame0(x = xseq, cat = catseq),
    se = se
  )

  if (se) {
    y <- pred$fit
    ci <- pred$se.fit * stats::qt(level / 2 + .5, pred$df)
    ymin <- y - ci
    ymax <- y + ci
    base::data.frame(x = xseq, cat = catseq, y, ymin, ymax, se = pred$se.fit)
  } else {
    base::data.frame(x = xseq, cat = catseq, y = as.vector(pred))
  }
}

#' @export
predictdf.locfit <- function(model, xseq, se, level) {
  pred <- stats::predict(
    model,
    newdata = data_frame0(x = xseq),
    se.fit = se
  )

  if (se) {
    y <- pred$fit
    ci <- pred$se.fit * stats::qt(level / 2 + .5, model$dp["df2"])
    ymin <- y - ci
    ymax <- y + ci
    base::data.frame(x = xseq, cat = catseq, y, ymin, ymax, se = pred$se.fit)
  } else {
    base::data.frame(x = xseq, cat = catseq, y = as.vector(pred))
  }
}
```

# compute_group_smooth

```{r}
# would be intersted in changeing the x sequence to observed values of x, for drawing fitted and residuals

compute_cat_model_smooth <- function(data, scales, method = NULL, formula = NULL,
                           se = TRUE, n = 80, span = 0.75, fullrange = FALSE,
                           xseq = NULL, catseq = NULL,
                           level = 0.95, method.args = list(),
                           na.rm = FALSE, flipped_aes = NA) {
    data <- flip_data(data, flipped_aes)
    if (vctrs::vec_unique_count(data$x) < 2) {
      # Not enough data to perform fit
      return(data_frame0())
    }

    if (is.null(data$weight)) data$weight <- 1

    the_cats <- unique(data$cat)
    num_cats <- length(the_cats)
    
    if(is.null(catseq)){catseq <- sort(rep(the_cats, n))}
    if(is.null(xseq)){
      
      xsequences <- list() 
      xseq <- c()
      
      for(i in 1:num_cats){
        
        subset <- data %>% filter(cat == the_cats[i])
        
        xsequences[[i]] <- seq(min(subset$x),max(subset$x), length.out = n)
        
        xseq <- c(xseq, xsequences[[i]])

      }
      
      
    }
    
    
    # # which values of x should we predict for ? 
    # if (is.null(xseq)) {
    #   if (is.integer(data$x)) {
    #     if (fullrange) {
    #       xseq <- scales$x$dimension()
    #     } else {
    #       xseq <- sort(unique0(data$x))
    #     }
    #   } else {
    #     if (fullrange) {
    #       range <- scales$x$dimension()
    #     } else {
    #       range <- range(data$x, na.rm = TRUE)
    #     }
    #     xseq <- seq(range[1], range[2], length.out = n)
    #   }
    # }
# 
#     # Special case span because it's the most commonly used model argument
#     if (identical(method, "loess")) {
#       method.args$span <- span
#     }
# 
#     if (is.character(method)) {
#       if (identical(method, "gam")) {
#         method <- gam_method()
#       } else {
#         method <- match.fun(method)
#       }
#     }
#     # If gam and gam's method is not specified by the user then use REML
#     if (identical(method, gam_method()) && is.null(method.args$method)) {
#       method.args$method <- "REML"
#     }
# 
    model <- rlang::inject(method(
      formula,
      data = data,
      weights = weight,
      !!!method.args
    ))

    prediction <- predictdf(model, xseq, catseq, se, level)
    prediction$flipped_aes <- flipped_aes
    flip_data(prediction, flipped_aes)
}



```



# test compute group 

```{r}
library(dplyr)
mtcars %>%
  rename(x = wt, y = mpg) %>% 
  mutate(cat = am) %>%
  slice(1:5) %>% 
  compute_cat_model_smooth(method = lm, formula = y ~ x + cat, n = 7)

mtcars %>%
  rename(x = wt, y = mpg) %>% 
  mutate(cat = am) %>%
  slice(1:15) %>% 
  ggplot() + 
  aes(x, y) + 
  geom_point(aes(color = factor(cat))) + 
  geom_point(data = . %>% 
            compute_cat_model_smooth(method = lm, 
                                    formula = y ~ x + cat, 
                                    n = 10), color = "blue")

```


```{r}

setup_smooth <- function(data, params) {
    params$flipped_aes <- has_flipped_aes(data, params, ambiguous = TRUE)
    msg <- character()
    if (is.null(params$method) || identical(params$method, "auto")) {
      # Use loess for small datasets, gam with a cubic regression basis for
      # larger. Based on size of the _largest_ group to avoid bad memory
      # behaviour of loess
      max_group <- max(table(interaction(data$group, data$PANEL, drop = TRUE)))

      if (max_group < 1000) {
        params$method <- "loess"
      } else {
        params$method <- "gam"
      }
      msg <- c(msg, paste0("method = '", params$method, "'"))
    }

    if (is.null(params$formula)) {
      if (identical(params$method, "gam")) {
        params$formula <- y ~ s(x, bs = "cs")
      } else {
        params$formula <- y ~ x + cat
      }
      msg <- c(msg, paste0("formula = '", deparse(params$formula), "'"))
    }
    if (identical(params$method, "gam")) {
      params$method <- gam_method()
    }

    if (length(msg) > 0) {
      cli::cli_inform("{.fn geom_smooth} using {msg}")
    }

    params
  }



#' @rdname ggplot2-ggproto
#' @format NULL
#' @usage NULL
#' @export
StatSmoothcat <- ggplot2::ggproto("StatSmoothcat", ggplot2::Stat,
  # setup_params = setup_smooth,
  extra_params = c("na.rm", "orientation"),
  compute_layer = compute_cat_model_smooth,
  dropped_aes = c("weight"),
  required_aes = c("x", "y", "cat")
)



stat_smooth_cat <- function(mapping = NULL, data = NULL,
                        geom = "point", position = "identity",
                        method = "lm",
                        formula = y ~ x + cat,
                        se = TRUE,
                        n = 80,
                        span = 0.75,
                        fullrange = FALSE,
                        level = 0.95,
                        method.args = list(),
                        na.rm = FALSE,
                        orientation = NA,
                        show.legend = NA,
                        inherit.aes = TRUE,                        ...
) {
  layer(
    data = data,
    mapping = mapping,
    stat = StatSmoothcat,
    geom = ggplot2::GeomPoint,
    position = position,
    show.legend = show.legend,
    inherit.aes = inherit.aes,
    params = rlang::list2(
      method = method,
      formula = formula,
      se = se,
      n = n,
      fullrange = fullrange,
      level = level,
      na.rm = na.rm,
      orientation = orientation,
      method.args = method.args,
      span = span,
      ...
    )
  )
}





```


New...

```{r}
mtcars %>% 
  ggplot() +
  aes(x = wt, y = mpg, cat = am) + 
  geom_point(aes(color = am)) +
  stat_smooth_cat(
                  n = 5,
                  color = "red", method = lm)


```

