---
title: "flipper estimation"
subtitle: ""
author: ""
output:
  xaringan::moon_reader:
    seal: FALSE
    lib_dir: libs
    css: [default, hygge, ninjutsu]
    nature:
      ratio: 16:9
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---



```{r, include = F}
options(knitr.duplicate.label = "allow")
knitr::opts_chunk$set(fig.width = 6, fig.height = 5,message = FALSE, warning = FALSE, comment = "", cache = F)
library(flipbookr)
library(tidyverse)
load("current_image.Rdata")
```


```{r, echo = F, eval = FALSE , message = F, warning = F}
xaringanExtra::use_share_again()
```


```{r the_chunk, include = F}
palmerpenguins::penguins %>% 
  head(2)

ggplot(palmerpenguins::penguins) +
  aes(y = flipper_length_mm, x = bill_depth_mm) +
  geom_point() +
  aes(bill_depth_mm = bill_depth_mm) +
  geom_lm(alpha = .2) +
  geom_text(stat = StatLmGlance, size = 5) +
  stat_lm(geom = 'segment', alpha = .2) +
  aes(color = species) +
  aes(shape = sex) +
  aes(island = island) +
  aes(body_mass_g = body_mass_g)


```

`r chunk_reveal(chunk_name = "the_chunk", break_type = "auto")`

---


```{r}
return_model()

```

```{css, eval = TRUE, echo = FALSE}
.remark-code{line-height: 1.5; font-size: 70%}

@media print {
  .has-continuation {
    display: block;
  }
}

code.r.hljs.remark-code{
  position: relative;
  overflow-x: hidden;
}


code.r.hljs.remark-code:hover{
  overflow-x:visible;
  width: 500px;
  border-style: solid;
}
```

