---
title: "another experiment"
author: "Evangeline Reynolds"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(tidyverse.quiet = TRUE)
```



```{r}
library(tidyverse)

compute_panel_lm <- function(data, scales, drop_x = FALSE, formula = y ~ . ){
  
  data %>% 
    remove_missing() ->
  data
  
  data %>% 
    select(-PANEL) ->
  lmdata
  
  if(drop_x){
    
    lmdata %>% 
      select(-x) ->
    lmdata
    
  }
  
  lm <- lm(data = lmdata, formula = formula)
  
  data$yend = data$y
  data$y = lm$fitted.values
  data$xend = data$x

  data$residuals <- lm$residuals
  
  data$model <- NA
  data$model[1] <- list(lm)
  
  data
  
}

palmerpenguins::penguins %>% 
  remove_missing() %>% 
  select(y = flipper_length_mm, 
         x = bill_depth_mm,
         p1 = sex) %>% 
  mutate(PANEL = 1) %>% 
  compute_panel_lm() %>% 
  .$model %>%
  .[[1]] %>% 
  summary()

palmerpenguins::penguins %>% 
  remove_missing() %>% 
  select(y = flipper_length_mm, 
         x = bill_depth_mm,
         p1 = sex) %>% 
  lm(data = ., formula = y ~ x + p1) %>% 
  summary()

StatLm <- ggproto("StatLm",
                  Stat,
                  compute_panel = compute_panel_lm)

palmerpenguins::penguins %>% 
  ggplot() + 
  aes(y = flipper_length_mm, x = bill_depth_mm) + 
  geom_point() + 
  geom_point(stat = StatLm, alpha = .25) +
  geom_segment(stat = StatLm, alpha = .25) + NULL 
last_plot() + aes(color = species) + aes(species = species) + NULL
last_plot() + aes(shape = sex) + NULL
last_plot() + aes(body_mass_g = body_mass_g) + NULL
last_plot() + aes(bill_length_mm = bill_length_mm) + NULL
last_plot() + aes(island = island)  + NULL
last_plot() + aes(year = year)

layer_data()
```

```{r}
palmerpenguins::penguins %>% 
  ggplot() + 
  aes(y = flipper_length_mm, x = bill_depth_mm, sex = sex) + 
  geom_point() + 
  geom_point(stat = StatLm, alpha = .05, formula = y ~ x) + 
  geom_point(stat = StatLm, alpha = .25, formula = y ~ x + sex) 

palmerpenguins::penguins %>% lm(data = ., formula = flipper_length_mm ~ .)

palmerpenguins::penguins %>% 
  ggplot() + 
  aes(y = flipper_length_mm, x = bill_depth_mm, sex = sex) + 
  geom_point() +
  geom_smooth(formula = y ~ x + x^2)
```


```{r}
last_plot() + 
  aes(p4 = bill_length_mm)

last_plot() + 
  aes(p5 = island)

last_plot() + 
  aes(p6 = year)


compute_square = function(data, scales){
  
  data %>% mutate(y = x, xmax = x, ymax = y, xmin = 0, ymin = 0)
  
}

StatSquare <- ggproto("StatSquare", Stat, compute_group = compute_square)

# residuals
layer_data(i = 2) %>% 
  ggplot() + 
  aes(x = residuals) + 
  geom_rug() +
  scale_x_continuous(limits = c(-40, 40)) + 
  geom_rect(stat = StatSquare, alpha = .2) + 
  coord_equal()

layer_data(i = 2) %>% 
  ggplot() + 
  aes(id = "All", area = x^2) +
  ggcirclepack::geom_circlepack(alpha = .25) + 
  ggcirclepack::geom_circlepack_text() + 
  aes(label = round(after_stat(area))) + 
  labs(title = "Residual Sum of Squares")

# Diff from mean
palmerpenguins::penguins %>% 
  remove_missing() %>% 
  mutate(index = row_number()) %>% 
  ggplot() + 
  aes(y = flipper_length_mm, x = index) + 
  geom_point() + 
  geom_point(stat = StatLm, alpha = .25, drop_x = T) + 
  geom_segment(stat = StatLm, alpha = .25, drop_x = T) 
  

layer_data(i = 2) %>% 
  ggplot() + 
  aes(x = residuals) + 
  geom_rug() + 
  geom_rect(stat = StatSquare, alpha = .2) +
  scale_x_continuous(limits = c(-40, 40)) + 
  coord_equal()

layer_data(i = 2) %>% 
  ggplot() + 
  aes(id = "All", area = x^2) +
  ggcirclepack::geom_circlepack(alpha = .25) + 
  ggcirclepack::geom_circlepack_text() + 
  aes(label = round(after_stat(area))) + 
  labs(title = "Total Sum of Squares")



(65219-7567)/66219  # R-squared 0.884

lm(flipper_length_mm ~ ., data = palmerpenguins::penguins) %>% 
  summary()

```


```{r}
knitr::knit_exit()


```

