---
title: "penguinseval"
subtitle: ""
author: ""
output:
  xaringan::moon_reader:
    seal: FALSE
    lib_dir: libs
    css: [default, hygge, ninjutsu]
    nature:
      ratio: 16:9
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---



```{r, include = F}
options(knitr.duplicate.label = "allow")
knitr::opts_chunk$set(fig.width = 6, message = FALSE, warning = FALSE, comment = "", cache = F)
library(flipbookr)
library(tidyverse)
load("current_image.Rdata")
```


```{r, echo = F, eval = FALSE , message = F, warning = F}
xaringanExtra::use_share_again()
```


```{r the_chunk, include = F}
palmerpenguins::penguins %>% 
  ggplot() + 
  aes(y = flipper_length_mm, x = bill_depth_mm) + 
  geom_point() + 
  geom_point(stat = StatLm, alpha = .45) + 
  geom_segment(stat = StatLm, alpha = .45) +
  aes(color = species) + aes(species = species) + 
  aes(shape = sex) + 
  aes(body_mass_g = body_mass_g) + 
  aes(bill_length_mm = bill_length_mm) + 
  aes(island = island)  + 
  aes(year = year)
```

`r chunk_reveal(chunk_name = "the_chunk", break_type = "auto")`



```{css, eval = TRUE, echo = FALSE}
.remark-code{line-height: 1.5; font-size: 80%}

@media print {
  .has-continuation {
    display: block;
  }
}

code.r.hljs.remark-code{
  position: relative;
  overflow-x: hidden;
}


code.r.hljs.remark-code:hover{
  overflow-x:visible;
  width: 500px;
  border-style: solid;
}
```

