---
title: "ggkids demo, mouse over"
author: "Evangeline Reynolds"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,  dev = "ragg_png"
)
options(tidyverse.quiet = TRUE)

library(dplyr)
```


```{r, fig.width=9}
library(tidyverse)

set.seed(12345)

'
library(ggkids)

mood_data <- 
   write_table(~day, ~feeling,
                1,      "😩",
                2,      "😞",
                3,      "😕",
                4,      "😐",
                5,      "😏",
                6,      "😊",
                7,      "😁")
                
ggkids(data = mood_data) +
  use_x(day) + 
  use_y(feeling) + 
  chart_point() + 
  chart_line() + 
  scale_x_counting() + 
  theme_kids(ink = "darkblue")' |> 
  ggram::ggram(code = _, title = "Mood improves over 7 days! 😃")
```

```{r, echo = F}
library(ggkids)

mood_data <- 
   write_table(~day, ~feeling,
                1,      "😩",
                2,      "😞",
                3,      "😕",
                4,      "😐",
                5,      "😏",
                6,      "😊",
                7,      "😁")
  

codehover::ch_hover({          
ggkids(data = mood_data) +
  use_x(day) + 
  use_y(feeling) + 
  chart_point() + 
  chart_line() + 
  scale_x_counting() + 
  theme_kids(ink = "darkblue")
}
)
```


