---
title: "statistically speaking slopes"
author: "Evangeline Reynolds"
date: "9/18/2023"
output: 
  html_document:
    toc: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Aspect ratio



```{r cars}
library(tidyverse)
stdzd <- function(x) (x-mean(x))/sd(x)
ggplot(mtcars, aes(x = wt, y = mpg)) +
  geom_point() +
  scale_y_continuous(sec.axis = sec_axis(stdzd, name = "Standard Deviations")) + 
  scale_x_continuous(sec.axis = sec_axis(stdzd, name = "Standard Deviations"))

scale_y_sd <- function(){
  scale_y_continuous(sec.axis = sec_axis(stdzd, name = "Standard Deviations"))
  } 
scale_x_sd <- function(){
  scale_x_continuous(sec.axis = sec_axis(stdzd, name = "Standard Deviations")) 
  }


ggplot(mtcars, aes(x = wt, y = mpg)) +
  geom_point() +
  scale_y_sd() + 
  scale_x_sd()

scale_xy_sd <- function(){
  
  list(scale_y_sd(),
    scale_x_sd())
  
}


last_plot() + 
  coord_fixed(ratio = sd(mtcars$wt)/sd(mtcars$mpg))

last_plot() + 
  ggxmean::geom_xy_means(shape = 4, size = 120, alpha = .3)


library(tidyverse)
mtcars |>
  ggplot() + 
  aes(x = wt, y = mpg) + 
  coord_fixed(ratio = sd(mtcars$wt)/sd(mtcars$mpg)) + 
  geom_point() + 
  geom_smooth(method = lm) + 
  geom_smooth(method = lm, formula = y ~ 1) + 
  ggxmean::geom_xy_means(shape = 4, size = 100, alpha = .5) +
  scale_y_sd() + 
  scale_x_sd() ->
p1; p1

cars %>% 
  ggplot() + 
  aes(x = speed, y = dist) + 
  coord_fixed(ratio = sd(cars$speed)/sd(cars$dist)) + 
  geom_point() + 
  geom_smooth(method = lm) + 
  geom_smooth(method = lm, formula = y ~ 1) + 
  ggxmean::geom_xy_means(shape = 4, size = 100, alpha = .5)+
  scale_y_sd() + 
  scale_x_sd() ->
p2; p2

corrr::correlate(cars)

mtcars %>% 
  select(wt, mpg) %>% 
  corrr:::correlate()

```

---

```{r}
library(patchwork)
(p1 + 
  scale_x_reverse() ) + p2

```


```{r}

library(tidyverse)
library(palmerpenguins)
penguins %>% 
  filter(species == "Adelie") ->
adelie

adelie %>% 
  ggplot() + 
  aes(bill_length_mm, bill_depth_mm) + 
  geom_point()  + 
  geom_smooth(method = "lm") + 
  coord_fixed(ratio = sd(adelie$bill_length_mm, na.rm = T)/
                sd(adelie$bill_depth_mm, na.rm = T))
 

palmerpenguins::penguins %>% 
  filter(species == "Gentoo") ->
gentoo

gentoo %>% 
  ggplot() + 
  aes(bill_length_mm, bill_depth_mm) + 
  geom_point() + 
  geom_smooth(method = "lm") + 
  coord_fixed(ratio = sd(gentoo$bill_length_mm, na.rm = T)/
                sd(gentoo$bill_depth_mm, na.rm = T))
 
```
# minimal example

```{r fig.show='hold', fig.height = 6, fig.width = 6, message=FALSE, out.width="33%"}
theme_set(theme_gray(base_size = 18))
ggplot(mtcars, aes(x = wt, y = mpg)) +
  labs(title = "step 1. plot and 'square up' on sd") + 
  geom_point() + 
  geom_smooth(method = lm) + 
  coord_fixed(ratio = sd(mtcars$wt)/
                sd(mtcars$mpg))

last_plot() + 
  labs(title = "step 2. add 'empty model' for reference") +
  geom_smooth(method = lm, formula = y ~ 1, se = F) 

last_plot() +
  labs(title = "step 3. add slope logical limits\nw/ point shape '4' hack") +
  annotate(geom = "point", 
           x = mean(mtcars$wt),
           y = mean(mtcars$mpg),
           shape = 4, # 'x' shape
           size = 140, # make it giant
           alpha = .75  # a little transparent - it's reference
           )
```


```{r}
library(tidyverse)





```



```{r}
dat <- tibble(temp = c(0, 100), time = 1:2)

ctof <- function(x){x*9/5 + 32}
ctof(0)
ctof(100)

ggplot(dat) + 
  aes(x = time, y = temp) +
  geom_point() +
  scale_y_continuous(sec.axis = sec_axis(trans = ctof))  +
  scale_y_continuous(sec.axis = sec_axis(trans = ~.*9/5 + 32))  
```


```{r, message=F}
ggplot(mtcars, aes(x = wt, y = mpg)) +
  geom_point() +
  coord_fixed(ratio = sd(mtcars$wt)/sd(mtcars$mpg)) + 
  geom_smooth(method = lm)  + 
  scale_y_continuous(sec.axis = 
                       sec_axis(~ (. -mean(mtcars$mpg))/ 
                                  sd(mtcars$mpg), 
                        name = "Standard deviations (Z)")) +
  scale_x_continuous(sec.axis = 
                       sec_axis(~ (. -mean(mtcars$wt))/ 
                                  sd(mtcars$wt), 
                        name = "Standard deviations (Z)"))


mtcars %>% 
  mutate(sd_wt = wt/sd(wt),
         sd_mpg = mpg/sd(mpg)) %>% 
lm(data = ., formula = sd_mpg ~ sd_wt) %>% 
  summary()

0.86766^2

cor(mtcars$mpg, mtcars$cyl) # corr with basel correction
```
