---
title: "another experiment"
author: "Evangeline Reynolds"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(tidyverse.quiet = TRUE)
```


## Intro Thoughts

- ggplot2 lets you speak plots into existence

- this allows for some powerful data viz and statistical story telling, build up your plot bit by bit...

- just like rock star Hans Rosling...

- and more (geom_smooth)

- except you will run into a wall... where you don't have the vocab.

- promise is ggplot2 extension... (vignette, Thomas Pederson)

- but you may run into a wall... because you don't have the background to translate this stuff to action

- OOP, holding all the pieces together, inability to practice demonstrated mechanisms.

- New approach for 'a new wave of ggplot2 extenders'...

- extension-ready population; ggplot2 super-users

- easy geom recipes

- population description

- results

- 'It's not gonna be that easy'

- support group

- 'so now I need to write a package...? and test and message?' 

- ggtedious


The problems for the 'new wave' quoting June bunch... 0. 'users aren't developers' 1) 'scary ggproto methods' (less experience with oop) 2) hard to reason about the big chunk of codes that defined a new ggroto object  3) even if we master all of this, then we have to become package developers? 

My proposed solutions, promoting 'easy geom recipes',  0) maybe users have got no choice but to be developers, because 0a. they are sick of precalculation that ggplot2 can just do and 0.b want the mental match of geom_x_mean() and the vline mean appears and 0c. ggplot2 base can't be responsible for working on all my unique problems. 1) make ggproto as ignorable as possible at first. 2) pull out all the pieces that define the ggproto and handle separately. 3) work on package development best practices: https://github.com/EvaMaeRey/ggtedious - this is where I'm definitely currently failing and know it. I never formally test anything.  

