---
title: "another experiment"
author: "Evangeline Reynolds"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(tidyverse.quiet = TRUE)
```


## Intro Thoughts

- ggplot2 lets you speak plots into existence

- this allows for some powerful data viz and statistical story telling, build up your plot bit by bit...

- just like rock star Hans Rosling...

- and more (geom_smooth)

- except you will run into a wall... where you don't have the vocab.

- promise is ggplot2 extension... (vignette, Thomas Pederson)

- but you may run into a wall... because you don't have the background to translate this stuff to action

- OOP, holding all the pieces together, inability to practice demonstrated mechanisms.

- New approach for 'a new wave of ggplot2 extenders'...

- extension-ready population; ggplot2 super-users

- easy geom recipes

- population description

- results

- 'It's not gonna be that easy'

- support group

- 'so now I need to write a package...? and test and message?' 

- ggtedious


