---
title: "Using R6 under the hood"
subtitle: "piping more than is printed"
author: "Gina Reynolds"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: [default, hygge, ninjutsu]
    nature:
      ratio: 16:9
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---


```{r, include = F}
# This is the recommended set up for flipbooks
# you might think about setting cache to TRUE as you gain practice --- building flipbooks from scratch can be time consuming
knitr::opts_chunk$set(fig.width = 6, fig.height = 4, message = F, warning = FALSE, comment = "", cache = F)

options(tibble.print_min = 55)
options(knitr.duplicate.label = "allow")
options(width=300) # prevents data wrapping
```


```{css, eval = TRUE, echo = FALSE}
.remark-code{line-height: 1.5; font-size: 70%}

@media print {
  .has-continuation {
    display: block;
  }
}

code.r.hljs.remark-code{
  position: relative;
  overflow-x: hidden;
}


code.r.hljs.remark-code:hover{
  overflow-x:visible;
  width: 500px;
  border-style: solid;
}
```



---




```{r newclass}
library(R6)
library(magrittr)
Fibonnacci <- R6Class("Fibonnacci",
                       public = list(
                         
                         # objects
                         init = c(0, 1),
                         last = 1,
                         current = 1,

                         # functions
                         fib_next = function(){ # a method
                           
                           x <- self$last
                           y <- self$current
                           
                           self$last <- y
                           self$current <- x + y
                           invisible(self)          #returns
                           
                                     },
                         
                         fib_init = function(x1, x2){
                           
                           self$init <- c(x1, x2)
                           self$last <- x2
                           self$current <- x1 + x2
                           invisible(self)            #returns
                           
                         }
                      
                       )
                      
                  
)
```



---


`r flipbookr::chunk_reveal("r6", left_assign = TRUE)`


```{r r6, include = FALSE}
my_fib <- Fibonnacci$new()
my_fib$fib_next()
my_fib$fib_next() 
my_fib$fib_next() 
my_fib$fib_next() 
my_fib$fib_next() 
my_fib$fib_next() 
my_fib$fib_next() 
my_fib$fib_init(5,4) 
my_fib$fib_next() 
my_fib$fib_next() 
my_fib$fib_next() 
my_fib$fib_next() 
```



---


```{r newclass2}
library(R6)
library(magrittr)
Fibonnacci_quiet <- R6Class("Fibonnacci_quiet",
                       public = list(
                         
                         # objects
                         init = c(0, 1),
                         last = 1,
                         current = 1,

                         # functions
                         fib_next = function(){ # a method
                           
                           x <- self$last
                           y <- self$current
                           
                           self$last <- y
                           self$current <- x + y
                           invisible(self)          #returns
                           
                                     },
                         
                         fib_init = function(x1, x2){
                           
                           self$init <- c(x1, x2)
                           self$last <- x2
                           self$current <- x1 + x2
                           invisible(self)            #returns
                           
                         },
                         
                         # print method; default is to print everything
                         print = function() { print(self$current) }
                       )
                      
                  
)
```



---


`r flipbookr::chunk_reveal("r6quiet", left_assign = TRUE)`


```{r r6quiet, include = FALSE}
my_fib_quiet <- Fibonnacci_quiet$new()
my_fib_quiet$fib_next()
my_fib_quiet$fib_next() 
my_fib_quiet$fib_next() 
my_fib_quiet$fib_next() 
my_fib_quiet$fib_next() 
my_fib_quiet$fib_next() 
my_fib_quiet$fib_next() 
my_fib_quiet$fib_init(5,4) 
my_fib_quiet$fib_next() 
my_fib_quiet$fib_next() 
my_fib_quiet$fib_next() 
my_fib_quiet$fib_next() 
```



---

`r flipbookr::chunk_reveal("wrapandpipe")`


```{r wrapandpipe, include = FALSE}
## wrap and pipe
fibi_init <- function(x1 = 0, x2 = 1){
  
  my_fib <- Fibonnacci_quiet$new()
  
  my_fib$fib_init(x1,x2)
  
  my_fib
  
}

fibi_advance <- function(my_fib){
  
  my_fib <- my_fib
  
  my_fib$fib_next()
  
  my_fib
  
}

fibi_collect <- function(my_fib){
  
  my_fib <- my_fib
  
  my_fib$current
  
  
}

```


---


`r flipbookr::chunk_reveal("chain")`


```{r chain, include = FALSE}
fibi_init() %>% 
  fibi_advance() %>% 
  fibi_advance() %>% 
  fibi_advance() %>% 
  fibi_advance() %>% 
  fibi_advance() %>% 
  fibi_advance() %>% 
  fibi_collect()
```



---

`r flipbookr::chunk_reveal("collect", break_type = 2)`


```{r collect, include = F}
fibi_init() %>% 
  str()


fibi_init() %>% 
  fibi_advance() %>% 
  str()


fibi_init() %>% 
  fibi_advance() %>%
  fibi_collect() %>% 
  str()
```
