---
title: "Exploded code"
subtitle: "Using flipbookr and xaringan"
author: "Me"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: [default, hygge, ninjutsu]
    nature:
      ratio: 16:9
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---


```{r, include = F}
# This is the recommended set up for flipbooks
# you might think about setting cache to TRUE as you gain practice --- building flipbooks from scratch can be time consuming
knitr::opts_chunk$set(fig.width = 6, fig.height = 4, message = F, warning = FALSE, comment = "", cache = F)

options(tibble.print_min = 55)
options(knitr.duplicate.label = "allow")
options(width=300) # prevents data wrapping
```


```{css, eval = TRUE, echo = FALSE}
.remark-code{line-height: 1.5; font-size: 70%}

@media print {
  .has-continuation {
    display: block;
  }
}

code.r.hljs.remark-code{
  position: relative;
  overflow-x: hidden;
}


code.r.hljs.remark-code:hover{
  overflow-x:visible;
  width: 500px;
  border-style: solid;
}
```



- https://www.datacamp.com/tutorial/r-objects-and-classes
- https://adv-r.hadley.nz/oo.html
- https://www.youtube.com/watch?v=3GEFd8rZQgY Winston Chang


---


`r flipbookr::chunk_reveal("AccumulatorNew0", left_assign = "detect")`


```{r AccumulatorNew0, include = FALSE}
library(R6)
Accumulator <- R6Class("Accumulator",
                       public = list(
                         sum = 0, # value that can evolve
                         add = function(x){ # a method
                           
                           self$sum <- self$sum + x
                           invisible(self) #returns
                           
                                     },
                         refresh = function(x){
                           
                           self$sum <- 0
                           invisible(self) #returns

                           
                         }
                       )
)
```


---


`r flipbookr::chunk_reveal("AccumulatorNew")`


```{r AccumulatorNew, include = FALSE}
x <- Accumulator$new()

x$add(4)
x$sum
x$refresh()
x$add(10)$add(12)
x$sum                                    
x$refresh()
x$sum
```



---


`r flipbookr::chunk_reveal("example2", left_assign = "detect")`


```{r example2, include = FALSE}
library(R6)

Person <- R6Class("Person",
  public = list(
    name = NULL,
    hair = NULL,
    initialize = function(name = NA, hair = NA) {
      self$name <- name
      self$hair <- hair
      self$greet()
    },
    set_hair = function(val) {
      self$hair <- val
    },
    greet = function() {
      cat(paste0("Hello, my name is ", self$name, ".\n"))
    }
  )
)
```

---


`r flipbookr::chunk_reveal("example2demo")`


```{r example2demo, include = FALSE}
ann <- Person$new(name = "Ann", hair = "black")
ann
ann$hair
ann$greet()
ann$set_hair("red")
ann$hair
```


---



```{r tpspecify}
library(R6)
library(magrittr)
TPSpecify <- R6Class("TPSpecify",
      public = list(
          
        sum = 0, # value that can evolve
        add = function(x){ self$sum <- self$sum + x ; invisible(self)},
        source_data = NULL,
        set_source_data = function(df) { self$source_data <- df },
        rows = NULL,
        set_rows = function(rows){ self$rows <- rows},
        cols = NULL,
        set_cols = function(cols){ self$cols <- cols},
        fun = NULL,
        set_fun = function(cols){ self$fun <- fun},
        out_data = NULL,
        compute_out_data = function(){ 
          self$out_data <- self$source_data %>% dplyr::count()
          },
        refresh = function(x){
          self$source_data <-  NULL
                         }
                       )
)
```


---


`r flipbookr::chunk_reveal("tpspecify2", left_assign = "detect")`


```{r tpspecify2, include = FALSE}
df_plus <- TPSpecify$new()
  
df_plus$set_source_data(df = cars)
df_plus$compute_out_data()
df_plus$refresh()
```
