---
title: "another experiment"
author: "Evangeline Reynolds"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(tidyverse.quiet = TRUE)
```




## Intro Thoughts

```{r}

compute_layer_rank <- function(data, scales, top = 20){
  
  data|>
    mutate(rank = rank(-x) |> as.numeric(), .by = facet) |>
    mutate(y_labels = fct_cross(facet, ranked, rank)) |>
    
    
}


gapminder::gapminder |>
  filter(continent == "Americas") |>
  filter(year > 2000) |>
  ggplot() +
  aes(x = pop,
      ranked = country,
      facet = year) + # also null
  geom_col() +
  facet_wrap(~ year, scales = "free_y") + 
  geom_point(stat = ggproto("", Stat, 
                            compute_layer = compute_layer_rank,
                            default_aes = aes(y = after_stat(rank)))) +  
  coord_trans(y = "reverse")





```



## Status Quo

```{r}
library(tidyverse)

gapminder::gapminder |>
  filter(continent == "Americas") |>
  filter(year > 2000) |>
  ggplot() +
  aes(x = pop,
      ranked = country,
      facet = year) +
  geom_col() +
  facet_wrap(~ year, scales = "free_y") + 
  scale_y_discrete(labels = function(x) str_remove(x, "\\.\\d+?$"), ) +
  coord_trans(y = "reverse")

```

## Experiment

```{r}
library(ggplot2)
library(dplyr)

compute_layer_rank <- function(data, scales, top = 20){
  
  data|>
    mutate(rank = rank(-x) |> as.numeric()) |>
    filter(rank <= 10)
    
}

gapminder::gapminder |>
  filter(year >= 2002) |> 
  filter(continent == "Americas") |>
  ggplot() + 
       aes(x = pop, 
           ranked = country,
           facet) + # <<  the ranked variable, to be interacted with x to create an ordered factor to compute y
  geom_point(stat = ggproto("", Stat, 
                            compute_layer = compute_layer_rank,
                            default_aes = aes(y = after_stat(rank)))) +
  scale_y_reverse() +
  facet_wrap(~year)


layer_data()



```


```{r}

library(tidyverse)

aes_y_by_x <- function(x, y){
  
  aes(x = {{x}}, 
      y = interaction(rank({{x}}), {{y}}, lex.order = T))
  
}



gapminder::gapminder |>
  filter(year %in% c(1967, 2007)) |> 
  filter(continent == "Americas") |>
  ggplot() + 
  aes_y_by_x(x = pop, y = country) +
  geom_col() + 
  facet_wrap(facets = vars(year), 
             scales = "free_y") 

last_plot() +
  scale_y_discrete(labels = function(x) str_remove(x, "^\\d+?\\."))

last_plot() +
  ggplyr::data_slice_max(pop, by = year)


facet_wrap_ranked <- function(vars){
  
    facet_wrap(facets = vars({{vars}}), scales = "free_y") 
  
}


scale_y_remove_rank <- function(){
  
  scale_y_discrete(labels = function(x) str_remove(x, "^\\d+?\\."))
  
}


gapminder::gapminder |>
  filter(year >= 2002) |> 
  ggplot() + 
  aes_y_by_x(x = pop, y = country) +
  geom_col() + 
  facet_wrap_ranked(~ year) +
  scale_y_remove_rank() +
  ggplyr::data_slice_max(pop, by = year)


```



```{r}

library(tidyverse)

aes_y_by_x_within <- function(x, y, within, n){
  
  aes(x = {{x}}, 
      y = interaction({{within}}, {{y}}, sep = "____") |>
        fct_reorder({{x}}) |>
        fct_reorder({{within}})
      )
  
}



gapminder::gapminder |>
  filter(year >= 2002) |> 
  filter(continent == "Americas") |>
  ggplot() + 
  aes_y_by_x_within(x = pop, y = country, within = year) +
  geom_col() + 
  facet_wrap(~ year, 
             scales = "free_y") +
  scale_y_discrete(labels = function(x) str_remove(x, "^.+?____"))

last_plot() +
  ggplyr::data_slice_max(pop, by = year, n = 10)



```



```{r}
library(tidyverse)
compute_panel_multi_response <- function(data, 
                                         scales, 
                                         cat_levels = NULL, 
                                         sep = ";"){
  
  # data = data.frame(responses = survey$q09)
  nrespondents <- nrow(data)

  data %>%
    summarise(responses = paste0(responses, collapse = sep)) %>% 
    mutate(response = str_split(responses, sep)) %>% 
    select(-responses) %>% 
    unnest(response) %>% 
    filter(response != "NA") %>% 
    count(response) %>%
    mutate(x = response %>% factor() %>%
             as.numeric() %>% as.double()
             ) %>%
    mutate(y = as.double(n)) %>% 
    mutate(num_respondents = nrespondents)
  
}

data.frame(selected_fruit = 
             c("banana;apple;pear", 
               "apple;pear", 
               "banana;pear")) %>%
  select(responses = selected_fruit) %>% 
  compute_panel_multi_response(cat_levels = fruit_cats)


aes_x_split <- function(x){
  
  
  aes(x = factor({{x}} |> paste(collapse = ";") |> str_split(";") |> _[[1]] |> unique() |> _[1:length({{x}})], 
              levels = {{x}} |> paste(collapse = ";") |> str_split(";") |> _[[1]] |> unique()),
      responses = {{x}})
  
  
}


StatMulticat <- ggplot2::ggproto(
  `_class` = "StatMulticat",
  `_inherit` = ggplot2::Stat,  
  compute_panel = compute_panel_multi_response,
  default_aes = aes(label = ggplot2::after_stat(paste0(n, "/", num_respondents))))

data.frame(selected_fruit = 
             c("apple;banana;pear", 
               "apple;peach", 
               "banana;pear",
               "banana",
               "anana",
               "banana")) |> 
  ggplot() + 
  aes_x_split(selected_fruit) + 
  aes(responses = selected_fruit) +
  layer(geom = "col", 
        stat = StatMulticat, 
        position = "identity")










```


## Closing remarks, Other Relevant Work, Caveats
