---
title: "another experiment"
author: "Evangeline Reynolds"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(tidyverse.quiet = TRUE)
```




## Intro Thoughts


## Status Quo

```{r cars, error=T}
library(ggplot2)

compute_line_end <- function(data, scales){
  
  data |>
    dplyr::filter(x == max(x))
  
}


gapminder::gapminder |>
  filter(continent == "Oceania") |>
  rename(x = year, y = gdpPercap, color = country, label = country) |> 
  compute_line_end()

StatLineend <- ggproto(`_class` = "StatLineend",
                       `_inherit` = Stat, 
                       compute_group = compute_line_end,
                       )

gapminder::gapminder |>
  filter(continent == "Oceania") |>
  ggplot() + 
  aes(x = year, y = gdpPercap, color = country, label = country) +
  geom_line(show.legend = F,) + 
  layer("point", "lineend", position = "identity" , show.legend = F) + 
  layer("text", "lineend", position = "identity", show.legend = F,
        params = list(hjust = 1, vjust = 0, color = "black"))

last_plot() + 
  layer("label", "lineend", position = "identity")

gapminder::gapminder |>
  filter(continent == "Oceania") |>
  ggplot() + 
  aes(x = year, y = gdpPercap, 
      color = country, label = country) + 
  geom_label() + 
  geom_label(data = . %>% filter(year == max(year)), color = "black")

sessionInfo()


```

## Experiment

```{r}

```



## Closing remarks, Other Relevant Work, Caveats
