---
title: "another experiment"
author: "Evangeline Reynolds"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(tidyverse.quiet = TRUE)
```




## Intro Thoughts


## Status Quo

```{r cars}
library(tidyverse)

Titanic %>% 
  data.frame() %>% 
  uncount(weights = Freq) ->
titanic

```

## Experiment

```{r}
titanic %>% 
  ggplot() +
  aes(x = Sex) + 
  geom_bar()

last_plot() + 
  facet_grid(~Age)

geom_bar

ggplot2::StatCount

ggplot2::StatCount$compute_group

titanic %>% 
  rename(x = Sex) %>% 
  ggplot2::StatCount$compute_group()


titanic %>% 
  rename(x = Sex, fill = Age) %>% 
  ggplot2::StatCount$compute_group()


titanic %>% 
  rename(x = Sex) %>% 
  ggplot2::StatCount$compute_group()

titanic %>% 
  ggplot() +
  aes(x = Sex) + 
  geom_bar() + 
  geom_text(stat = StatCount, 
            aes(label = after_stat(count)),
            vjust = -.15)
```


uh-oh...  saw different behavior w/ mtcars.

```{r}
titanic %>% 
  ggplot() +
  aes(x = Sex) + 
  geom_bar() + 
  geom_text(stat = StatCount, 
            aes(label = after_stat(100*prop)),
            vjust = -.15)


```



## Closing remarks, Other Relevant Work, Caveats
