---
title: "Exploded code"
subtitle: "Using flipbookr and xaringan"
author: "Me"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: [default, hygge, ninjutsu]
    nature:
      ratio: 16:9
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---


```{r, include = F}
# This is the recommended set up for flipbooks
# you might think about setting cache to TRUE as you gain practice --- building flipbooks from scratch can be time consuming
knitr::opts_chunk$set(fig.width = 6, message = F, warning = FALSE, comment = "", cache = F)

options(tibble.print_min = 55)
options(knitr.duplicate.label = "allow")
options(width=300) # prevents data wrapping
```


```{css, eval = TRUE, echo = FALSE}
.remark-code{line-height: 1.5; font-size: 70%}

@media print {
  .has-continuation {
    display: block;
  }
}

code.r.hljs.remark-code{
  position: relative;
  overflow-x: hidden;
}


code.r.hljs.remark-code:hover{
  overflow-x:visible;
  width: 500px;
  border-style: solid;
}
```


---


`r flipbookr::chunk_reveal("first", left_assign = "detect")`


```{r first, include = FALSE}
library(ggstamp)
library(ggplot2)
library(tidyverse)

major = c("C", "G", "D", "A", "E", "B", 
            "Gb","Db", "Ab", "Eb", "Bb", "F")
minor = c("Am", "Em", "Bm", "F#m", "C#m", "G#m", "Ebm",
            "Bbm", "Fm", "Cm", "Gm", "Dm")
spot = 1:12

ggcanvas() + 
  stamp_polygon(n_vertices = 12) + 
  stamp_circle(radius = 1.4) +
  stamp_text(xy = pos_polygon(n = 12,
             radius = 1.1), 
             label = major,
             size = 6) + 
  stamp_circle(radius = .8) +
  stamp_text(xy = pos_polygon(n = 12, radius = .5),
             label = minor,
             size = 5) +
  stamp_spoke(radius = 1.4, 
              angle = pi*1:12/6 + 
                1/12*pi) 
```

---


`r flipbookr::chunk_reveal("another", left_assign = "detect")`


```{r another, include = FALSE}
ggcanvas() + 
  stamp_tile(x = 1:12) +
  stamp_text(x = 1:12, 
             label = major) + 
  stamp_tile(x = 1:12, y = -1) +
  stamp_text(x = 1:12, y = -.8, 
             label = minor,
             size = 4) +
  coord_polar(start = -.25) + 
  theme_void_fill() + 
  stamp_tile(x = 1, alpha = .25, 
             fill = "red")
```

