---
title: "another experiment"
author: "Evangeline Reynolds"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(tidyverse.quiet = TRUE)
```




## Intro Thoughts


## Status Quo

```{r}
library(tidyverse)
library(palmerpenguins)
penguins_clean <- remove_missing(penguins) 
glimpse(penguins_clean)

library(ggram)


clearhistory()

# Compute.
mpg_medians <- mpg |> 
  summarize(cty_median = median(cty),
            hwy_median = median(hwy))
#
# Plot.
ggplot(data = mpg) + 
  aes(x = cty, y = hwy) + 
  geom_point() + 
  geom_point(data = mpg_medians,
             aes(x = cty_median,
                 y = hwy_median),
             size = 8, color = "red")

ggram("Step 0: Get the job done with base ggplot2")

```



```{r}
clearhistory()
#
# Define compute.
compute_group_medians <-  #<<
  function(data, scales){ 
  data |> 
    summarize(x = median(x),
              y = median(y))
}
#
# Test compute. 
mpg |>
  select(x = cty, y = hwy) |>  
  compute_group_medians()  #<<

ggram::ggram_df_output("Step 1: Define compute. Test.")
```





```{r}
clearhistory()

####### Define Stat ##########
StatMedians <- ggplot2::ggproto(`_class` = "StatMedians",
                   `_inherit` = ggplot2::Stat,
                   compute_group = #<<
                     compute_group_medians, #<<
                   required_aes = c("x", "y"))
#
###### Test ########
ggplot(data = mpg) + 
  aes(x = cty, y = hwy) + 
  geom_point() + 
  geom_point(
    stat = StatMedians, #<<
    size = 7)

ggram("Step 2: Define Stat. Test.")
```





```{r}
clearhistory()
##### use stat_identity() as a model #####
stat_identity #<< for reference... 

ggram_text_output("Assist to Step 3: Consult stat_identity definition.")

```


```{r}
clearhistory()


##### Define user-facing stat_* function #####
stat_medians <- function(
    mapping = NULL, data = NULL, 
    geom = "point", #<<
    position = "identity", 
    ..., show.legend = NA, inherit.aes = TRUE) 
{
    layer(data = data, mapping = mapping, 
          stat = StatMedians, #<<
        geom = geom, position = position, 
        show.legend = show.legend, 
        inherit.aes = inherit.aes, 
        params = rlang::list2(na.rm = FALSE, ...))
}
#
###### Alias if desired #########
geom_medians <- stat_medians
#



ggram_text_output("Step 3: Define user-facing function() usable in Step 00. ", widths = c(2, 0))

ggsave("hi.png", width = 4, height = 5)
```



```{r}
clearhistory()


###### Done! Use the geom_medians ###############
ggplot(data = mpg) + 
  aes(x = cty, y = hwy) + 
  geom_point() + 
  geom_medians(size = 7) 


ggram("Done! Use your extension")


```



## Closing remarks, Other Relevant Work, Caveats
