---
title: "another experiment"
author: "Evangeline Reynolds"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, dev = "ragg_png", message = F, warning = F)
options(tidyverse.quiet = TRUE)
```

```{r}
state_ref <- usmapdata::us_map() |> 
  select(state = full, 
         state_fips = fips, 
         state_abb = abbr, 
         geometry = geom)

head(state_ref)

geom_state <- ggregions::write_geom_region_locale(state_ref)
stamp_state <- ggregions::write_stamp_region_locale(state_ref)


USArrests |>
  rownames_to_column(var = "state") |> 
  ggplot() + 
  aes(state = state,
      fill = Assault) + 
  geom_state()
```


# gganatogram's data experiment

https://github.com/jespermaag/gganatogram

The data isn't stored w/ sf format which the ggregions process requires.. Can't seem to figure how it works in the original api, but not well when translated...

```{r, warning=F}
library(tidyverse)
library(gganatogram)



gganatogram::mmFemale_list |> 
  bind_rows() |>
  remove_missing() |>
  ggplot() + 
  aes(x, -y, group = group, color = id) + 
  geom_polygon(show.legend = F) + 
  coord_equal()
```






```{r}
to_sf_routine <- function(data){
  
  data |>
  mutate(y = -y) |>
  sf::st_as_sf(coords = c("x", "y"), agr = "constant") |>
  group_by(id, group) |>
  summarize(do_union = F) |> 
  ungroup() |> 
  group_by(id, group) |>
  summarise() |>
  mutate(geometry = geometry |> sf::st_cast("POLYGON")) |> 
  mutate(geometry = geometry |> sf::st_cast("MULTIPOLYGON")) |> 
  ungroup() 
  
}

mm_female_sf <- gganatogram::mmFemale_list |> 
  bind_rows() |>
  # filter(x != 0, y != 0, y < -2) |>
  remove_missing() |>
  to_sf_routine() |> 
  rename(organ = id)




mm_female_sf |> 
  ggplot()  + 
  geom_sf(aes(geometry = geometry)) + 
  coord_sf()

```






```{r}
# compare
ggseg::aseg$data$geometry

geom_organ <- ggregions::write_geom_region_locale(mm_female_sf)
stamp_organ <- ggregions::write_stamp_region_locale(mm_female_sf)

mm_female_sf$organ |> sample(20)

ggplot() + 
  stamp_organ() + 
  stamp_organ(keep = "aorta", fill = "darkred") +
  stamp_organ(keep = "brain", fill = "darkseagreen") + 
  stamp_organ(keep = "blood_vessel", fill = "orange")
```

# original mouse gganatogram api

It looks great, but maybe the hard-ish thing is navigating it?

```{r}
# original api
gganatogram(data = mmFemale_key, 
            outline = T, 
            fillOutline='#440154FF', 
            organism = 'mouse', 
            sex='female', 
            fill="value")  + 
  theme_void()   +  
  scale_fill_viridis_c() +
  coord_equal()
```

```{r}
cell_sf <- gganatogram::cell_list[[1]] |> 
  bind_rows() |>
  # filter(x != 0, y != 0, y < -2) |>
  remove_missing() |>
  to_sf_routine() |> 
  rename(organelle = id)


cell_sf |> 
  ggplot()  + 
  geom_sf(aes(geometry = geometry), alpha = .2) + 
  coord_sf()
```


```{r}
geom_organelle <- ggregions::write_geom_region_locale(cell_sf)
stamp_organelle <- ggregions::write_stamp_region_locale(cell_sf)

cell_sf

ggplot() + 
  stamp_organelle(alpha = .2) + 
  stamp_organelle(keep = "actin_filaments", fill = "orange", alpha = .1) +
  stamp_organelle(keep = "endoplasmic_reticulum", fill = "darkred") 


```


# Trying human anatomy with same routing 

```{r, error = T}

length(gganatogram::hgFemale_list)

# fix so that all data frames can be combined with bind_rows
# the groups are numeric and character so using bind_rows fails
female_sf <- gganatogram::hgFemale_list[c(1:156, 180:195)] |> # return to this!!
  bind_rows() |>
  remove_missing() |>
  to_sf_routine() 
  
stamp_organ <- ggregions::write_stamp_region_locale(female_sf)

ggplot() + 
  stamp_organ(alpha = .2) + 
  stamp_organ(keep = "lung", 
              fill = "plum3") + 
  stamp_organ(keep = "stomach",
              fill = "cornsilk") + 
  stamp_organ(keep = "heart", 
              fill = "coral") + 
  stamp_organ(keep = "brain", 
              fill = "pink3")


male_sf <- gganatogram::hgMale_list[2:155] |>  
  bind_rows() |>
  # filter(x != 0, y != 0, y < -2) |>
  remove_missing() |>
  to_sf_routine() 

ggplot(female_sf) + 
  aes(geometry = geometry) +
  geom_sf(alpha = .2)

ggplot(male_sf) + 
  aes(geometry = geometry) +
  geom_sf(alpha = .2)
```

## teethr's data experiment

https://github.com/bbartholdy/teethr

```{r}
library(tidyverse)
library(teethr)
teeth_ref_data <- dental_arcade_mapping |> 
  as_tibble() |> 
  left_join(tooth_notation |> 
  select(tooth = text, fdi = FDI, standard = standards) 
  )
```

```{r}  
head(teeth_ref_data)  # are there other ids?  like just number of tooth?

library(ggregions)
geom_tooth <- ggregions::write_geom_region_locale(teeth_ref_data)
geom_tooth_text <- write_geom_region_text_locale(teeth_ref_data)
stamp_tooth <- write_stamp_region_locale(teeth_ref_data)
stamp_tooth_text <- write_stamp_region_text_locale(teeth_ref_data)



ggplot() + 
  stamp_tooth()

last_plot() + 
  stamp_tooth_text(size = 2)


ggplot() + 
  stamp_tooth() + 
  stamp_tooth_text(size = 2,
                   aes(label = after_stat(fdi)))

ggplot() + 
  stamp_tooth() + 
  stamp_tooth_text(size = 2,
                   aes(label = after_stat(standard)))


caries_ratios <- mb11_caries %>% 
  dental_longer(-id) %>%
  dental_join() %>% 
  count_caries(caries = score, no_lesion = "none") %>% # convert location to lesion count
  group_by(tooth) %>% 
  dental_ratio(count = caries_count) %>%
  dental_recode(tooth, "FDI", "text") 

head(caries_ratios)

caries_ratios |> 
  ggplot() + 
  stamp_tooth() + 
  aes(tooth = tooth, 
      fill = ratio) + 
  geom_tooth()

last_plot() + 
  geom_tooth(keep = c("LLM1", "URM3")) |> 
    ggfx::with_outer_glow("red") + 
  geom_tooth_text(keep = c("LLM1", "URM3"),
                  label = "😬",
                  hjust = -0.5) 

```


# aseg X data

```{r}
library(ggseg)

coronal_ref_data <- ggseg::aseg$data |> 
  filter(side == "coronal") |>     # just look at coronal for the nuttiness.
  group_by(region) |> 
  summarise(geometry = sf::st_combine(geometry)) |> 
  select(region = region, everything())
  
coronal_ref_data |> pull(region)

library(ggregions)
geom_region <- write_geom_region_locale(ref_data = coronal_ref_data)
stamp_region <- write_stamp_region_locale(ref_data = coronal_ref_data)
geom_region_text <- write_geom_region_text_locale(ref_data = coronal_ref_data)
stamp_region_text <- write_stamp_region_text_locale(ref_data = coronal_ref_data)


ggplot() + 
  stamp_region() + 
  stamp_region(keep = "hippocampus", fill = "blue")


ggplot() + 
  stamp_region() + 
  stamp_region_text(check_overlap = T)


tribble(~activity, ~segment,
       .2, "hippocampus",
       .5, "amygdala",
       .7, "thalamus proper") |>
ggplot() + 
  stamp_region() + 
  aes(region = segment,
      fill = activity) + 
  geom_region() 

```

