---
title: "another experiment"
author: "Evangeline Reynolds"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(tidyverse.quiet = TRUE)
```




## Intro Thoughts


## Status Quo

```{r}
library(tidyverse)
library(mall)

options(.mall_chat = ellmer::chat_google_gemini())

#' @export
scale_fill_semantic <- function(palette = function(){llm_vec_classify(x, c("green", "red"))}, ...){
 
  scale_fill_discrete(palette = palette, ...)
   
}

diamonds |> 
  ggplot() + 
  aes(x = cut, 
      fill = cut) + 
  geom_bar() + 
  scale_fill_discrete() +
  scale_fill_semantic(palette = c("green", "red", "orange", "pink", "grey")) + 
  scale_fill_semantic()


scale_x

scale_fill_identity <- function (name = waiver(), ..., guide = "none", aesthetics = "fill") 
{
    discrete_scale(aesthetics, name = name, palette = pal_identity(), 
        ..., guide = guide, super = ScaleDiscreteIdentity)
}

scales::pal_identity

ScaleDiscreteIdentity$get_transformation

ScaleDiscrete$get_breaks

```

## Experiment

```{r}

```



## Closing remarks, Other Relevant Work, Caveats
