---
title: "a ggplot2 layer tabulation demonstration"
author: "Evangeline Reynolds"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(tidyverse.quiet = TRUE)
```

## Save information about the entire data set (not panel-wise) in compute_layer_prop.

Seems 

```{r}
library(tidyverse)
compute_layer_prop <- function(data = mtcars, ...){
  
  if(is.null(data$value)){data$value <- 1}
  
  global_sum <- sum(data$value)
  
  data %>% 
    group_by(PANEL) %>% 
    summarize(sum = sum(value)) %>% 
    mutate(prop = sum/global_sum) %>% 
    mutate(label = round(100 * prop, 1) %>% paste0("%")) %>% 
    mutate(x = 0, y = 0)

}

Titanic %>% 
  data.frame() %>%  
  uncount(Freq) %>% 
  group_by(Sex, Survived) %>% 
  mutate(cell = paste(Sex, Survived, sep = "-")) %>%  
  mutate(PANEL = paste(as.numeric(Sex), as.numeric(Survived), sep = "-")) %>%
  compute_layer_prop()

StatProp <- ggproto(`_class` = "StatProp",
                    `_inherit` = Stat,
                    compute_layer = compute_layer_prop)

Titanic %>% 
  data.frame() %>%  
  uncount(Freq) %>% 
  ggplot(aes(fill = after_stat(prop))) + 
  facet_grid(Sex ~ Survived) + 
  layer(geom = "tile", 
        stat = StatProp, 
        position = "identity") +
  layer(geom = "text", 
        stat = StatProp, 
        position = "identity")

layer_data()



```

```{r, eval = T}
library(tidyverse)

Titanic %>% 
  data.frame() %>%  
  uncount(Freq) ->
tidy_titanic

compute_layer_prop_by <- function(data = tidy_titanic, ...){
  
  if(is.null(data$value)){data$value <- 1}
  if(is.null(data$prop_by)){data$prop_by <- 1}
  if(is.null(data$wt)){data$wt <- 1}
  
  data$value <- data$value * data$wt
  
  data %>% 
    group_by(prop_by) %>% 
    summarize(group_sum = sum(.data$value)) ->
  group_sum_df
  
  data %>% 
    left_join(group_sum_df, by = "prop_by") %>% 
    group_by(PANEL, prop_by) %>% 
    summarize(sum = sum(.data$value),
              group_sum = mean(.data$group_sum)) %>% 
    mutate(prop = sum/group_sum) %>% 
    mutate(prop_label = round(prop, 3)) %>% 
    mutate(percent_label = paste0(prop_label * 100, "%")) %>% 
    mutate(count_percent_label = paste0(sum, "\n(", percent_label, ")" )) %>% 
    mutate(percent_count_label = paste0(percent_label, "\n(", sum, ")" )) %>% 
    mutate(x = 0, y = 0) 

}


aes_label_count_percent <- function(){ 
  aes(label = after_stat(paste0(sum, "\n(", percent_label, ")" ))) 
  }


aes_label_percent_count <- function(){
  aes(label = after_stat(paste0(percent_label, "\n(", sum, ")" ))) 
  }


# test compute layer
tidy_titanic %>% 
  mutate(prop_by = Sex) %>% 
  mutate(PANEL = paste(as.numeric(Sex), 
                       as.numeric(Survived), sep = "-")) %>%
  ungroup() %>% 
  compute_layer_prop_by()


StatPropby <- ggproto(`_class` = "StatPropby",
                    `_inherit` = Stat,
                    compute_layer = compute_layer_prop_by,
                    default_aes = aes(label = after_stat(sum),
                                      fill = after_stat(prop_by)))

stat_tableprop <- function(geom = "text"){
  
    layer(geom = geom, 
        stat = StatPropby, 
        position = "identity",
        params = list(size = 8, color = "whitesmoke"))
  
}

and <- paste  # not super careful category combos


```


```{r demo}
tidy_titanic %>% 
  ggplot() + 
  theme(axis.text = element_blank(),
        axis.ticks = element_blank(),
        panel.grid = element_blank(),
        text = element_text(size = 22)) +
  guides(fill = "none") +
  stat_tableprop(geom = "tile") + 
  stat_tableprop() + 
  facet_grid(~ Sex) + # specify table layout
  facet_grid(Sex ~ Survived) + 
  aes(label = after_stat(prop_label)) +
  aes(label = after_stat(percent_label)) + 
  aes(prop_by = Sex) + 
  aes(label = after_stat(count_percent_label)) +
  aes(label = after_stat(percent_count_label)) +
  facet_grid(rows = vars(Sex),
             cols = vars(Age, Survived)) + 
  aes(prop_by = Sex) + 
  aes(prop_by = Age) +
  facet_grid(rows = vars(Age)) +
  aes(prop_by = NULL) + 
  aes(label = after_stat(sum))


layer_data()
```

```{r}
knitr::knit_exit()


```



```{r}
ggtable <- function(data){

data %>% 
  ggplot() + 
  theme(axis.text = element_blank(),
        axis.ticks = element_blank(),
        panel.grid = element_blank(),
        text = element_text(size = 22)) +
  guides(fill = "none") +
  stat_tableprop(geom = "tile") + 
  stat_tableprop()
  
}


display <- function(var){
  
  aes(label = after_stat({{vars}}))
  
}

prop_scope <- function(var){
  
  aes(prop_by = {{vars}})
  
}
```



```{r demo2}
tidy_titanic %>% 
  ggtable() + 
  facet_grid(~ Sex) + # specify table layout
  facet_grid(Sex ~ Survived) + 
  display(prop_label) +
  display(percent_label) + 
  prop_scope(Sex) + 
  aes_label_count_percent() +
  prop_scope(Survived) + 
  aes_label_percent_count() + 
  facet_grid(rows = vars(Sex),
             cols = vars(Age, Survived)) + 
  prop_scope(Sex) + 
  prop_scope(Age) +
  facet_grid(rows = vars(Age)) +
  prop_scope(NULL)


```


```{r, eval = F}
flipbookr:::embed_flipbook("demo", font_size = "80%")
```


```{r}
last_plot() + 
  stat_tableprop(geom = "tile") + 
  aes(fill = after_stat(prop)) +
  scale_fill_gradient2(low = alpha("magenta4", .2), 
                       high = alpha("magenta4", .6))
```


## Closing remarks, Other Relevant Work, Caveats
