---
title: "another experiment: base ggplot2, draw x = mean(x_var) line"
author: "Evangeline Reynolds"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = T, error = T)
options(tidyverse.quiet = TRUE)
```



## Traditional approach, pre-computation w/ vline

```{r cars}
library(tidyverse)
```

```{r}
mean_wt <- data.frame(cyl = c(4, 6, 8), 
                      wt = c(2.28, 3.11, 4.00))

ggplot(mtcars, aes(wt,mpg,  colour = wt)) +
  geom_point() +
  geom_vline(aes(xintercept = wt, colour = wt), mean_wt) +
  facet_wrap(~ cyl,
             ncol = 1)
```


## Auto compute experiments.  Use base ggplot2 to give compute the xmean

### Use geom_smooth, w/ 'y' orientation and formula y~1

```{r}
ggplot(mtcars) + 
  aes(x = wt, y = mpg, color = factor(am)) + 
  geom_rug() + 
  geom_point() + 
  geom_smooth(orientation = "y", xseq = c(10,35),
              method = lm, se = F,
              formula = y ~ 1)

# can fullrange be used?  Unsure of what's going on here, maybe x and y got switched
ggplot(mtcars) + 
  aes(x = wt, y = mpg, color = factor(am)) + 
  geom_rug() + 
  geom_point() + 
  geom_smooth(orientation = "y", 
              method = lm, se = T,
              formula = y ~ 1,
              fullrange = TRUE)


# can fullrange be used?  Unsure of what's going on here, maybe x and y got switched
ggplot(mtcars) + 
  aes(x = mpg, y = wt, color = factor(am)) + 
  geom_rug() + 
  geom_point() + 
  geom_smooth(orientation = "x", 
              method = lm, se = FALSE,
              formula = y ~ 1,
              fullrange = TRUE)



# seems true...
last_plot() + 
  coord_flip()

```

#### univariate (no y) gets more hacky

```{r}
ggplot(mtcars) + 
  aes(x = wt) + 
  geom_rug() + 
  geom_histogram() +
  geom_smooth(
    orientation = "y", 
              method = lm, 
              formula = y ~ 1,
              se = F, 
              aes(y = new_var), # it a required aesthetic - you can kind of put any var so we just put x again...      
              data = . %>% mutate(new_var = row_number()), # so you can use the genaric new_var...
              xseq = c(0, Inf) # determined looking histogram first
              )

# not good cause of the row numbers 'randomly' covering different groups
last_plot() + 
  aes(color = factor(am))

geom_x_mean <- function(...){
  
    geom_smooth(
    orientation = "y", 
              method = lm, 
              formula = y ~ 1,
              se = F, 
              aes(y = new_var), # it a required aesthetic - you can kind of put any var so we just put x again...
              data = . %>% mutate(new_var = row_number()),
              xseq = c(0, Inf), # determined looking histogram first
    ...
              )
  
}


ggplot(mtcars) + 
  aes(x = wt) + 
  geom_rug() + 
  geom_histogram() +
  geom_x_mean(linetype = "dotted")

# not good cause of the row numbers 'randomly' covering different groups
last_plot() + 
  aes(color = factor(am))

# Not very hopeful about fullrange at present but maybe after bug fix?
```


## Use stat_summary w/ geom = "point", shape = 3 (cross hairs)

a terrible(ly fun?) hack

```{r, out.width="45%", fig.show='hold'}
ggplot(mtcars) + 
  aes(x = wt) +
  geom_rug() + 
  geom_histogram() +
  stat_summary(fun = "mean", # calculate the mean
               orientation = "y", # for x
               geom = "point", # place a point there
               aes(y = 0), # with the value 0 for y
               shape = 3, # use the 'cross hairs' shape
               size = 300, # make the cross hairs huge
               show.legend = F # legend with will overwhelm plot because of size
               ) 

last_plot() +
  aes(color = factor(am)) + 
  aes(fill = factor(am)) +
  facet_wrap(~factor(am),
             ncol = 1) 
```

---


# use geom_segment with stage, after_stat?

```{r}
library(tidyverse)
ggplot(mtcars) + 
  aes(x = wt) +
  geom_rug() + 
  geom_histogram() + 
  geom_segment(aes(xend = wt, y = -Inf, yend = Inf))

layer_data(last_plot())


ggtrace::ggtrace_inspect_args(
  x = last_plot(),
  method = ggplot2:::Layer$compute_statistic
)$data %>% head()


# computes for all data, after_stat alone errors
ggplot(mtcars) + 
  aes(x = wt) +
  geom_rug() + 
  geom_histogram() + 
  geom_segment(aes(x = stage(start = wt, after_stat = mean(x)),
                   xend = stage(start = wt, after_stat = mean(x)),
                   y = -Inf, yend = Inf))


# does not work as expected
last_plot() + 
  aes(color = factor(am))
```

# other notes



```{r}
# also, expect 2 rows of data, but get 32
layer_data(last_plot(), 3) %>%
  head()
  

# a knock against segment shown below..
# requires y, whereas vline will draw without, via range back computation
ggplot(mtcars) + 
  aes(x = wt) +
  geom_rug() + 
  geom_segment(aes(xend = wt, y = -Inf, yend = Inf))
```

## Closing remarks, Other Relevant Work, Caveats
