---
title: "another experiment"
author: "Evangeline Reynolds"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(tidyverse.quiet = TRUE)
```




## Intro Thoughts


## Status Quo

```{r}
library(tidyverse)
data(peng, package = "heplots")
# use all numeric variables
DSQ <- heplots::Mahalanobis(peng[, 3:6], )
ids <- order(DSQ, decreasing = TRUE)[1:3] |> print()
#> [1] 283  10  35

# augment the dataset to add `note` variable for selecting labels
peng_plot <- peng |>
  tibble::rownames_to_column(var = "id") |> 
  mutate(note = id %in% ids)

```

## Experiment

```{r}
ggplot(peng_plot, 
       aes(x = bill_length, y = bill_depth,
           color = species, shape = species, fill=species)) +
  geom_point(aes(size=note), show.legend = FALSE) +
  scale_size_manual(values = c(1.5, 4)) +
  geom_text(data = subset(peng_plot, note==TRUE),
            aes(label = id),
            nudge_y = .4, color = "black", size = 5) +
  geom_smooth(method = "lm", formula = y ~ x,
              se=FALSE, linewidth=2) +
  stat_ellipse(geom = "polygon", level = 0.95, alpha = 0.1) +
  # theme_penguins() +
  theme_bw(base_size = 14) +
  theme(legend.position = "inside",
        legend.position.inside=c(0.85, 0.15))


StatNoteworthy <- ggproto(
  "StatNoteworthy", Stat,
  
  required_aes = c("x", "y"),
  
  compute_panel = function(data, scales, method = "dsq", n = 10) {
    
    data <- data |>
      mutate(id = row_number())
    
    id_rows <- heplots::noteworthy(x = data$x, y = data$y, n = n, method = method)
    
    data[id_rows, , drop = FALSE]
    
  },
  default_aes = aes(label = after_stat(id))
)

peng |> 
  select(x = bill_length, y = bill_depth) |>
  StatNoteworthy$compute_panel()


ggplot(peng, 
       aes(x = bill_length, 
           y = bill_depth,
           color = species, 
           shape = species, 
           fill = species)) +
  geom_point() +
  geom_smooth(method = "lm", 
              formula = y ~ x,
              se = FALSE, 
              linewidth = 2) +
  stat_ellipse(geom = "polygon", level = 0.95, alpha = 0.1) +
  geom_text(stat = StatNoteworthy, method = "dsq", n = 3, color = "black") + 
  geom_text(stat = StatNoteworthy, method = "mahal", n = 3, color = "red")



```



## Closing remarks, Other Relevant Work, Caveats
