---
title: "another experiment"
author: "Evangeline Reynolds"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, dev = "ragg_png", dpi = 300)
options(tidyverse.quiet = TRUE)
```




## Intro Thoughts


## Status Quo

```{r}
library(tidyverse)

```

## Experiment

```{r}
library(mall)
options(.mall_chat = ellmer::chat_google_gemini())
```

```{r, cache = T}
emoji_palette <- str_split_1("🥵🔥❄️🥶🐻","")

temp <- c("30C", "88F", "20F")

emoji_for_temps <- temp |> 
  llm_vec_classify(emoji_palette)

emoji_for_temps
```


```{r}
emoji_for_temps

ggplot() + 
  aes(x = temp, 
      y = c(86, 88, 20),  # to Fahrenheit
      label = emoji_for_temps) +
  labs(y = "Temp in Fahrenheit",
       x = "Different ways to talk temperature") +
  geom_col() + 
  geom_text(size = 12)

```


```{r, cache=T}
palette()

animals <- c("elephant", "turtle", "goldfish") 

colors_for_animals <- animals |>
  llm_vec_classify(palette())
```


```{r}
colors_for_animals

ggplot() + 
  aes(x = animals, 
      y = c(1,2,3),
      fill = colors_for_animals |> I()) + 
  geom_col() + 
  theme_gray(base_size = 15) + 
  labs(x = NULL)
```



## Closing remarks, Other Relevant Work, Caveats
