---
title: "another experiment"
author: "Evangeline Reynolds"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(tidyverse.quiet = TRUE)
```




## Intro Thoughts





---

## stat_rasa

https://eliocamp.github.io/codigo-r/en/2018/05/how-to-make-a-generic-stat-in-ggplot2/

```{r cars}
library(tidyverse)
```

## Experiment

```{r}
StatRasa <- ggplot2::ggproto("StatRasa", ggplot2::Stat,
  compute_group = function(data, scales, fun, fun.args) {
     # Change default arguments of the function to the 
     # values in fun.args
     args <- formals(fun)
     for (i in seq_along(fun.args)) {
        if (names(fun.args[i]) %in% names(fun.args)) {
           args[[names(fun.args[i])]] <- fun.args[[i]]
        } 
     }
     formals(fun) <- args
     
     # Apply function to data
     fun(data)
})

# stat function used in ggplot
stat_rasa <- function(mapping = NULL, data = NULL,
                      geom = "point", 
                      position = "identity",
                      fun = NULL,
                      ...,
                      show.legend = NA,
                      inherit.aes = TRUE) {
   # Check arguments 
   if (!is.function(fun)) stop("fun must be a function")
   
   # Pass dotted arguments to a list
   fun.args <- match.call(expand.dots = FALSE)$`...`
   
   ggplot2::layer(
      data = data,
      mapping = mapping,
      stat = StatRasa,
      geom = geom,
      position = position,
      show.legend = show.legend,
      inherit.aes = inherit.aes,
      check.aes = FALSE,
      check.param = FALSE,
      params = list(
         fun = fun, 
         fun.args = fun.args,
         na.rm = FALSE,
         ...
      )
   )
}


# using .75 span to match ggplot2 geom_smooth
Detrend <- function(data, method = "lm", span = 0.75) {
   if (method == "lm") {
      data$y <- resid(lm(y ~ x, data = data))
   } else {
      data$y <- resid(loess(y ~ x, span = span, data = data))
   }
   as.data.frame(data)
   }
   
   
library(ggplot2)
set.seed(42)
x <- seq(-1, 3, length.out = 30)
y <- x^2 + rnorm(30)*0.5
df <- data.frame(x = x, y = y)

ggplot(df, aes(x, y)) +
  geom_line()

last_plot() +
   stat_rasa(geom = "line", 
             fun = Detrend, 
             method = "smooth",
             color = "steelblue") +
  geom_hline(yintercept = 0, 
             linetype = "dashed") + 
  labs(title = "detrending with loess smoothing")


ggplot(df, aes(x, y)) +
  geom_line(aes(color = "original")) +
  geom_smooth(aes(color = "loess smoothing")) + 
  stat_smooth(geom = "point", aes(color = "loess smoothing"),
              xseq = df$x) +
  stat_rasa(geom = "line", 
             fun = Detrend, 
             method = "smooth",
             aes(color = "detrended")) +
  geom_hline(yintercept = 0, 
             linetype = "dashed") + 
  labs(title = "detrending with loess smoothing")
  
  
stat_detrend <- function(...) {
   stat_rasa(fun = Detrend, geom = "line", ...)
}

ggplot(df, aes(x, y)) + 
  geom_line(aes(color = "raw data")) +
  geom_smooth(method = "lm", 
              aes(color = "linear model")) +
  stat_smooth(method = "lm", geom = "segment",
              xend = df$x, yend = df$y,
              xseq = df$x, alpha = .2
              ) +
  stat_detrend(method = "lm", 
                aes(color = "detrended")) +
  geom_hline(yintercept = 0, 
             linetype = "dashed") + 
  scale_color_discrete(breaks = 
                         fct_inorder(c("raw data",
                                       "linear model",
                                       "detrended"))) + 
  labs(title = "Linear detrending",
       color = NULL)
```

## Simpler example for reach...

```{r}
summarize_xy <- function(data, sum_fun = mean){
  
  data |>
    summarize(
      x = sum_fun(x),
      y = sum_fun(y)
    )
  
}


mtcars |>
  ggplot() + 
  aes(x = wt,
      y = mpg) + 
  geom_point() + 
  stat_rasa(fun = summarize_xy, 
            size = 8,
            aes(color = "means")) + 
  stat_rasa(fun = summarize_xy, 
            sum_fun = median, 
            size = 8, 
            aes(color = "medians")) + 
  labs(color = "centroid")

```


### Compare with ggtemp/ggexpress formulation

```{r}
define_layer_temp <- function(
  compute_group = NULL,
  compute_panel = NULL, 
  required_aes = NULL,
  geom = ggplot2::GeomPoint, 
  mapping = NULL,
  data = NULL,
  position = "identity",
  na.rm = FALSE,
  show.legend = NA,
  inherit.aes = TRUE, 
  ...) {

  if(is.null(compute_group)){compute_group <- ggplot2::Stat$compute_group}
  if(is.null(compute_panel)){compute_panel <- ggplot2::Stat$compute_panel}
  if(is.null(required_aes)) {required_aes  <- ggplot2::Stat$required_aes}
     
     
StatTemp <- ggproto(
  `_class` = "StatTemp",
  `_inherit` = ggplot2::Stat,
  compute_group = compute_group,
  compute_panel = compute_panel,
  required_aes  = required_aes)
  
  ggplot2::layer(
    stat = StatTemp,  # proto object from Step 2
    geom = geom,  # inherit other behavior
    data = data,
    mapping = mapping,
    position = position,
    show.legend = show.legend,
    inherit.aes = inherit.aes,
    params = list(na.rm = na.rm, ...)
  )
}


compute_panel_circle <- function(data, scales, n_vertices = 15){
  
  data |> 
    mutate(group = row_number()) |> 
    crossing(tibble(z = 0:n_vertices)) |>
    mutate(around = 2*pi*z/max(z)) |> 
    mutate(x = x0 + cos(around)*r,
           y = y0 + sin(around)*r) 
  
}

geom_circle <- function(...){
  
  define_layer_temp(
    compute_panel = compute_panel_circle,
    ...)
  
}

library(ggplot2)
data.frame(x0 = 0:1, y0 = 0:1, r = 1:2/3) |>
  ggplot() +
  aes(x0 = x0, y0 = y0, r = r) +
  geom_circle(n_vertices = 5) +
  aes(fill = r)
```


```{r}
compute_group_xy_summary <- function(data, scales){
  
  data |> 
    summarize(x = mean(x),
              y = mean(y))
  
}

geom_xy_summary <- function(...){
  
  define_layer_temp(
    compute_panel = compute_group_xy_summary,
    ...)
  
}

mtcars |>
  ggplot() +
  aes(x = wt, y = mpg) +
  geom_point() + 
  geom_xy_summary(size = 8)

last_plot() + 
  aes(color = factor(gear))


```

### On the fly Stat mutation?

```{r}
StatIdentity2 <- ggproto(NULL, ggplot2::StatIdentity)


mtcars |>
  ggplot() + 
  aes(x = wt,
      y = mpg) + 
  geom_point(stat = StatIdentity2) 



StatIdentity2$compute_group <- function(data, scales){
  
  data |>
    summarize(x = mean(x),
              y = mean(y))
  
}

mtcars |>
  ggplot() + 
  aes(x = wt,
      y = mpg) + 
  geom_point(stat = StatIdentity2) 
```



### pipe note from Teun vd Brand


```{r}
piped <- . %>% summarise(x = mean(x)) %>%
  mutate(x = x + 1)

piped
```




## Closing remarks, Other Relevant Work, Caveats
