---
title: "another experiment"
author: "Evangeline Reynolds"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(tidyverse.quiet = TRUE)
```




## Intro Thoughts


## Status Quo

```{r}
library(tidyverse)

```

## Experiment

```{r}

library(mall)
options(.mall_chat = ellmer::chat_google_gemini())


library(tidyverse)
example_palette <- c("grey9", "hotpink", "darkgreen", "midnightblue", 
                     "turquoise", "darkorange", "grey", "brown", 
                     "darkred", "burlywood", "goldenrod2") 

example_palette |> 
  tibble(pal_colors = _) |> 
  ggplot() + 
  aes(x = pal_colors, y = "all",
      fill = I(pal_colors)) + 
  geom_tile()

df <- tribble(~item, ~times, 
        "parrot", 11,
        "peacock", 20,
        "dolphin", 30,
        "sloth", 22) |> 
  llm_classify(item, 
               labels = example_palette,
               pred_name = ".color")

df

df |> 
  ggplot() + 
  aes(x = item) +
  geom_bar() + 
  aes(fill = I(.color))


```



## Closing remarks, Other Relevant Work, Caveats
