---
title: "another experiment"
author: "Evangeline Reynolds"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(tidyverse.quiet = TRUE)
```




## Intro Thoughts


## Status Quo

```{r}
library(tidyverse)

```

## Experiment

```{r}
library(R6)

Person <- R6Class("Person",
  public = list(
    name = NULL,
    hair = NULL,
    initialize = function(name = NA, hair = NA) {
      self$name <- name
      self$hair <- hair
      self$greet()
    },
    set_hair = function(val) {
      self$hair <- val
    },
    greet = function() {
      cat(paste0("Hello, my name is ", self$name, ".\n"))
    }
  )
)


Pivot <- R6Class("Pivot",
  public = list(
    data = NULL,
    rows = NULL,
    cols = NULL,
    initialize = function(data, rows = NULL, cols = NULL){
      self$data <- data
      self$rows <- rows
      self$cols <- cols
      self$return_table()
    }, 
    set_data = function(val){
      self$data <- val
    },
    set_rows = function(val){
      self$rows <- val
    },
    set_cols = function(val){
      self$cols <- val
    },
    return_table = function(){
      "my table!"

      self$data %>% #group_by(across(c({{rows}}, {{cols}}))) %>% 
         count() #%>% 
         # pivot_wider(cols = cols)
      
    }
    
    )
  )


mutablething <- Pivot$new(data = tidytitanic::tidy_titanic, rows = "sex")
mutablething
mutablething$set_cols("survived")
mutablething$cols
mutablething$initialize(data = tidytitanic::tidy_titanic)
mutablething
mutablething$return_table()
```

```{r}
ann <- Person$new("Ann", "black")
ann
ann$hair
ann$greet()
ann$set_hair("red")
ann$hair
```

```{r}
knitr::knit_exit()

```


```{r}
Queue <- R6Class("Queue",
  public = list(
    initialize = function(...) {
      for (item in list(...)) {
        self$add(item)
      }
    },
    add = function(x) {
      private$queue <- c(private$queue, list(x))
      invisible(self)
    },
    remove = function() {
      if (private$length() == 0) return(NULL)
      # Can use private$queue for explicit access
      head <- private$queue[[1]]
      private$queue <- private$queue[-1]
      head
    }
  ),
  private = list(
    queue = list(),
    length = function() base::length(private$queue)
  )
)

q <- Queue$new(5, 6, "foo")

```




## Closing remarks, Other Relevant Work, Caveats
