---
title: "another experiment"
author: "Evangeline Reynolds"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, error = T)
options(tidyverse.quiet = TRUE)
```




## A slightly different approach to what's currently in ggdims. 

```{r}
library(tidyverse)

dims <- function(...){}


dims_expand2 <- function(select) {

  structure(
    list(), 
    class = "dims_expand2"
    )

}


#' @import ggplot2
#' @importFrom ggplot2 ggplot_add
#' @export
ggplot_add.dims_expand2 <- function(object, plot, object_name) {
  
  # get expression inside of dims parentheses in `aes(dims = dims(var1:var10))`
  # would return "var1:var10"
  select_specs <- plot$mapping$dims[[2]] |> 
    as.character() |> 
    _[-1] |> 
    paste(collapse = ", ")
  
  # from plot data point to the select_specs variables that are specified 
  # and save a data frame, in features_df
  features_df <- paste0("select(plot$data,",  select_specs, ")") |> 
    rlang::parse_expr() |> 
    eval()

  # create a vector added to the plot data
  plot$data$.dims_stasher <- vector("list", nrow(plot$data))

  for (i in 1:nrow(features_df)){
  # store the features data as a 1 row data frame in vector .dims_stasher...
  plot$data$.dims_stasher[[i]] <- features_df[i,]
  }
  
  # overwrite dims mapping to point to new vector that contains features_df
  plot$mapping <- modifyList(plot$mapping, aes(dims = .dims_stasher))
  
  plot
  
}

dims <- function(){}

ggplot(mtcars) + 
  aes(dims = dims(mpg:drat, qsec), x = 1, y = 1) + 
  geom_point() + 
  dims_expand2()

p <- last_plot()

p$mapping

p$data$.dims_stasher[[1]]

p$data$.dims_stasher |>
  bind_rows() |>
  ggdims:::pca_layout()
```

# then a new compute...

```{r}
compute_pca_rows <- function (data, scales){
  
    data_for_reduction <- data$dims |> bind_rows()

    clean_data <- remove_missing(bind_cols(data_for_reduction,
        data |> select(-"dims")))
    
    # set.seed(1345)
    
    clean_data[names(data_for_reduction)] |>
      ggdims:::pca_layout() |>
      bind_cols(clean_data)
    
}



StatPca <- ggproto("StatPca", Stat, compute_panel = compute_pca_rows,
                   default_aes = 
                             aes(x = after_stat(PC1), 
                                 y = after_stat(PC2)))

ggplot(mtcars) +
  aes(dims = dims(mpg:drat, qsec)) +
  dims_expand2() +
  geom_point(stat = StatPca)

layer_data()

ggplot(iris) +
  aes(dims = dims(Sepal.Length:Petal.Width),
      color = Species) +
  # --------- the following gets wrapped up to geom_pca ------------
  dims_expand2() +
  geom_point(stat = StatPca)
```

```{r}
knitr::knit_exit()


```


# More examples...

```{r, eval = F}
download.file("https://github.com/patperry/r-corpus/raw/refs/heads/master/data/federalist.rda", destfile = "federalist.rda")
```

```{r}
library(tidyverse)

load("federalist.rda")

federalist |> tibble()
```

```{r}

federalist %>%
  mutate(author = replace_na(author, 
                             "Disputed")) %>% 
  mutate(name = paste(author, 
                      str_remove(name, "eralist"), 
                      sep = "-")) -> 
federalist


federalist %>%
  mutate(author = replace_na(author, "disputed")) |>
  select(doc_name = name, author, text, title) %>% 
  tidytext::unnest_tokens(output = word, input = text) %>% 
  # stop word are good for stylometry - keep them only
  inner_join(tidytext::stop_words) %>%
  group_by(doc_name, word, author) %>% 
  count() %>% 
  ungroup() %>%
  arrange(-n) %>% 
  # group_by(word) |> 
  # mutate(n = n/sum(n)) |>
  # ungroup() |> 
  pivot_wider(values_from = n, names_from = word, values_fill = 0) |>
  select(-group) ->
federalist_stopwords_freq

names(doc_token_freq) |> tail()

federalist_stopwords_freq |> 
  ggplot() + 
  aes(dims = dims(the:lest),
      color = author) + 
  dims_expand2() +
  geom_point(stat = compute_pca_rows |> 
               qstat_panel(default_aes = 
                             aes(x = after_stat(PC1), 
                                 y = after_stat(PC2))))# + 
  # facet_wrap(~author)


compute_umap <- function (data, scales){
  
    data_for_reduction <- data$dims |> bind_rows()

    clean_data <- remove_missing(bind_cols(data_for_reduction,
        data |> select(-"dims")))
    
    # set.seed(1345)
    
    clean_data[names(data_for_reduction)] |>
      ggdims:::umap_layout_2d() |>
      bind_cols(clean_data)
    
}

StatUmap <- ggproto("StatUmap", Stat,
                    compute_panel = compute_umap)

geom_umap0 <- make_constructor(ggdims::GeomPointFill, stat = StatUmap)

geom_umap <- function(...){
  
  list(geom_umap0(...),
       dims_expand2())
  
  
}

federalist_stopwords_freq |>
  ggplot() + 
  aes(dims = dims(the:lest),
      fill = author) + 
  geom_umap()



compute_tsne <- function (data, scales, perplexity = 30){
  
    data_for_reduction <- data$dims |> bind_rows()

    clean_data <- remove_missing(bind_cols(data_for_reduction,
        data |> select(-"dims")))
    
    # set.seed(1345)
    
    clean_data[names(data_for_reduction)] |>
      ggdims:::tsne_layout_2d(perplexity = perplexity) |>
      bind_cols(clean_data)
    
}

StatTsne <- ggproto("StatTsne", Stat,
                    compute_panel = compute_tsne)

geom_tsne0 <- make_constructor(ggdims::GeomPointFill, stat = StatTsne)

geom_tsne <- function(...){
  
  list(geom_tsne0(...),
       dims_expand2())
  
  
}


federalist_stopwords_freq |>
  ggplot() + 
  aes(dims = dims(the:lest),
      fill = author) + 
  geom_tsne(perplexity = 20)

```


```{r}

unvotes::un_votes |> 
  filter(rcid >= 679) |> 
  arrange(rcid) |>
  # mutate(rcid = paste0("rc",rcid) |> fct_inorder()) |>
  mutate(num_vote = case_when(vote == "yes" ~ 1,
                              vote == "abstain" ~ .5,
                              vote == "no" ~ 0,
                              TRUE ~ .5 )) |>
  # filter(rcid %in% 1:30) |>
  pivot_wider(id_cols = c(country, country_code),
    names_from = rcid, 
              values_from = num_vote,
              values_fill = .5
            ) |>
  mutate(continent = country_code |> 
           countrycode::countrycode(origin = "iso2c", destination = "continent")) |>
  mutate(continent = continent |> is.na() |> ifelse("unknown", continent)) ->
unga_rcid_wide

names(unga_rcid_wide) |> head()
names(unga_rcid_wide) |> tail()


ggplot(unga_rcid_wide) + 
  aes(dims = dims(`679`:`9147`),
      color = continent) + 
  dims_expand2() +
  geom_point(stat = compute_pca_rows |> 
               qstat_panel(default_aes = 
                             aes(x = after_stat(PC1), 
                                 y = after_stat(PC2))))

```






## Just noodling, what I started with, but moving it out of the way.

```{r}
library(tidyverse)
library(ggdims) # Feb 2, 2026

ggplot(iris) + 
  aes(dims = dims(Sepal.Length:Petal.Width))

p <- last_plot()

p$mapping

last_plot() + 
  geom_pca()

p1 <- last_plot() 

p1$mapping


ggplot(iris) + 
  aes(dims = dims_listed("Sepal.Length", "Petal.Width")) + 
  geom_pca0()


ggplot(iris) + 
  aes(dims = dims_listed(Sepal.Length, Petal.Width)) + 
  geom_pca()

p <- last_plot()

p$mapping

last_plot() + 
  geom_pca()


varnames <- c("hi", "by",  "go")

for(i in 1:length(varnames)){
  
  p1$mapping <- modifyList(p1$mapping, aes_string(temp = varnames[i]))
  names(p1$mapping)[which(names(p1$mapping) == "temp")] <- paste0(".v", i)
  
}

p1$mapping


varnames <- c("hi", "by",  "go")

for(i in 1:length(varnames)){
  
  p1$mapping <- modifyList(p1$mapping, aes_string(temp = varnames[i]))
  names(p1$mapping)[which(names(p1$mapping) == "temp")] <- paste0(".v", i)
  
}

tribble(~go, ~`for`, ~hi, 1,1,1,2,2,3) |>  
ggplot() + 
  aes(x = `for`, 
      y = hi) 

make_list_with_data_frame_in_first_spot <- function(){
  
  
  
  
  
}

cars$dims <- vector("list", nrow(cars))

cars$dims[[1]] <- mtcars

cars$dims[[1]]

```

