---
title: "legendry"
subtitle: ""
author: ""
output:
  xaringan::moon_reader:
    seal: FALSE
    lib_dir: libs
    css: [default, hygge, ninjutsu]
    nature:
      ratio: 16:9
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      message = F, 
                      warning = F, 
                      dpi = 300,
                      cache = F)
library(codehover)
library(tidyverse)
library(ggcube)


library(tidyverse)
PAIR_code_umap_mammoth_url <- "https://raw.githubusercontent.com/PAIR-code/understanding-umap/refs/heads/master/raw_data/mammoth_3d.json"

library(jsonlite)
mammoth_df <- PAIR_code_umap_mammoth_url |>
  fromJSON() |>
  as_tibble() 

confetti <- sample(colors(), 
                     nrow(mammoth_df),
                     replace = T) |> alpha(.5)

```

`r flipbookr::chunk_reveal(chunk_name = "my_cars")`


```{r my_cars, eval=FALSE, echo=FALSE}
library(tidyverse)
library(ggcube)

ggplot(data = mammoth_df) +
  aes(x = V1) + 
  aes(y = V2) + 
  geom_point() +
  aes(shape = I(21)) + 
  aes(fill = I(confetti)) +
  aes(color = I("white")) +
  aes(stroke = .2) +
  aes(z = V3) +
  coord_3d(expand = FALSE,
           ratio = c(2,1.4,1),
           yaw = 0, 
           roll = 10, 
           pitch = 5) +
  geom_point_3d() + 
  theme_void() +
  labs(title = "A Muse of ML and dim-red: Max Noichl's Mammoth!",
       subtitle = "Visualized with {ggplot2} x {ggcube}",
       caption = "Data from github.com/PAIR-code/understanding-umap") ->
ggcubed_mammoth


ggcubed_mammoth |> 
  animate_3d(pitch = c(0, 360))
```








```{css, echo = F}
.column {
  float: left;
  width: 50%;
  padding: 10px;
  background-color:white;
}
```


```{css, echo = F, eval = F}
table {
  cursor: pointer; 
  cursor: hand;
  border: none;
  margin-left: auto;
  margin-right: auto;
  width:"80%";
  border:"0"; 
  cellspacing:"0"; 
  cellpadding:"0";
  font-family: "Lucida Console";
}

.hover {
  background-color: #F1D95A92;
}

.image-crop {
  height: 600px;;
}

tab1 { padding-left: 4em; }
tab2 { padding-left: 8em; }
tab3 { padding-left: 12em; }
tab4 { padding-left: 16em; }
tab5 { padding-left: 20em; }
tab6 { padding-left: 24em; }
tab7 { padding-left: 28em; }
tab8 { padding-left: 32em; }
tab9 { padding-left: 36em; }
tab10 { padding-left: 40em; }
tab11 { padding-left: 44em; }
tab12 { padding-left: 48em; }
tab13 { padding-left: 52em; }
tab14 { padding-left: 56em; }
tab15 { padding-left: 60em; }
tab16 { padding-left: 64em; }



```



