---
title: "ML mammoth"
subtitle: ""
author: ""
output:
  xaringan::moon_reader:
    seal: FALSE
    lib_dir: libs
    css: [default, hygge, ninjutsu]
    nature:
      ratio: 16:9
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      message = F, 
                      warning = F, 
                      dpi = 300,
                      cache = F, 
                      dev = "ragg_png")
```

```{r}
library(tidyverse)
PAIR_code_umap_mammoth_url <- "https://raw.githubusercontent.com/PAIR-code/understanding-umap/refs/heads/master/raw_data/mammoth_3d.json"

library(jsonlite)
mammoth_df <- PAIR_code_umap_mammoth_url |>
  fromJSON() |>
  as_tibble() |> 
  slice_sample(n = 539)


```

---

`r flipbookr::chunk_reveal(chunk_name = "my_cars")`


```{r my_cars, eval=FALSE, echo=FALSE}
library(tidyverse)
library(ggcube)

ggplot(data = mammoth_df) +
  aes(x = V1) + 
  aes(y = V2) + 
  geom_point() +
  aes(shape = I(21)) + 
  aes(color = I("white")) +
  aes(stroke = .2) +
  aes(z = V3) +
  coord_3d(ratio = c(2,1.4,1),
           yaw = 0, 
           roll = 10, 
           pitch = 5) +
  geom_surface_3d(fill = "#8a2900", color = "#8a2900",
                   light = light(method = "direct", mode = "hsl", 
                                 direction = c(0, 0, 1)))

+
  
  geom_point_3d() + 
  labs(
    title = "A Muse of ML, Max's Mammoth...",
    subtitle = "Max Noichl popularized mammoth data, a 3D scan of a Smithsonian \nMammoth.  ML and AI researchers have turned to it in explorations like \n'Understanding UMAP' and beyond.",
    caption = "Visualized with {ggplot2} and {ggcube} - new on CRAN!\nData as curated by Coenen and Pearce at github.com/PAIR-code/understanding-umap"
    )

ggplot(sphere_points) +
  aes(x, y, z) +
      coord_3d(scales = "fixed") +
      scale_fill_viridis_c() +
      scale_color_viridis_c() +
      theme_dark() +
      theme(legend.position = "none") +
      # apply shading to solid color/fill
      geom_hull_3d(fill = "#8a2900", color = "#8a2900",
                   light = light(method = "direct", mode = "hsl", 
                                 direction = c(0, 0, 1)))



animate_3d(
    plot + theme_void(), 
    pitch = c(0, 360)
    )
```





```{css, eval = TRUE, echo = FALSE}
.remark-code{line-height: 1.5; font-size: 80%}

@media print {
  .has-continuation {
    display: block;
  }
}

code.r.hljs.remark-code{
  position: relative;
  overflow-x: hidden;
}


code.r.hljs.remark-code:hover{
  overflow-x:visible;
  width: 500px;
  border-style: solid;
}
```
